// Copyright 2022 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.1
// source: chromiumos/config/api/software/nnpalm_config.proto

package software

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The configuration of neural network palm rejection.
// For more details, see:
// https://source.chromium.org/chromiumos/chromiumos/codesearch/+/HEAD:src/platform2/chromeos-config/README.md
type NnpalmConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model            string `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	RadiusPolynomial string `protobuf:"bytes,2,opt,name=radius_polynomial,json=radiusPolynomial,proto3" json:"radius_polynomial,omitempty"`
	TouchCompatible  bool   `protobuf:"varint,3,opt,name=touch_compatible,json=touchCompatible,proto3" json:"touch_compatible,omitempty"`
}

func (x *NnpalmConfig) Reset() {
	*x = NnpalmConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_config_api_software_nnpalm_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NnpalmConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NnpalmConfig) ProtoMessage() {}

func (x *NnpalmConfig) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_config_api_software_nnpalm_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NnpalmConfig.ProtoReflect.Descriptor instead.
func (*NnpalmConfig) Descriptor() ([]byte, []int) {
	return file_chromiumos_config_api_software_nnpalm_config_proto_rawDescGZIP(), []int{0}
}

func (x *NnpalmConfig) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *NnpalmConfig) GetRadiusPolynomial() string {
	if x != nil {
		return x.RadiusPolynomial
	}
	return ""
}

func (x *NnpalmConfig) GetTouchCompatible() bool {
	if x != nil {
		return x.TouchCompatible
	}
	return false
}

var File_chromiumos_config_api_software_nnpalm_config_proto protoreflect.FileDescriptor

var file_chromiumos_config_api_software_nnpalm_config_proto_rawDesc = []byte{
	0x0a, 0x32, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65,
	0x2f, 0x6e, 0x6e, 0x70, 0x61, 0x6c, 0x6d, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73,
	0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x6f, 0x66, 0x74,
	0x77, 0x61, 0x72, 0x65, 0x22, 0x7c, 0x0a, 0x0c, 0x4e, 0x6e, 0x70, 0x61, 0x6c, 0x6d, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x2b, 0x0a, 0x11, 0x72, 0x61,
	0x64, 0x69, 0x75, 0x73, 0x5f, 0x70, 0x6f, 0x6c, 0x79, 0x6e, 0x6f, 0x6d, 0x69, 0x61, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x72, 0x61, 0x64, 0x69, 0x75, 0x73, 0x50, 0x6f, 0x6c,
	0x79, 0x6e, 0x6f, 0x6d, 0x69, 0x61, 0x6c, 0x12, 0x29, 0x0a, 0x10, 0x74, 0x6f, 0x75, 0x63, 0x68,
	0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x69, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0f, 0x74, 0x6f, 0x75, 0x63, 0x68, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x69, 0x62,
	0x6c, 0x65, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x6f, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75,
	0x6d, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73,
	0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x67, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73,
	0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chromiumos_config_api_software_nnpalm_config_proto_rawDescOnce sync.Once
	file_chromiumos_config_api_software_nnpalm_config_proto_rawDescData = file_chromiumos_config_api_software_nnpalm_config_proto_rawDesc
)

func file_chromiumos_config_api_software_nnpalm_config_proto_rawDescGZIP() []byte {
	file_chromiumos_config_api_software_nnpalm_config_proto_rawDescOnce.Do(func() {
		file_chromiumos_config_api_software_nnpalm_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_chromiumos_config_api_software_nnpalm_config_proto_rawDescData)
	})
	return file_chromiumos_config_api_software_nnpalm_config_proto_rawDescData
}

var file_chromiumos_config_api_software_nnpalm_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_chromiumos_config_api_software_nnpalm_config_proto_goTypes = []interface{}{
	(*NnpalmConfig)(nil), // 0: chromiumos.config.api.software.NnpalmConfig
}
var file_chromiumos_config_api_software_nnpalm_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chromiumos_config_api_software_nnpalm_config_proto_init() }
func file_chromiumos_config_api_software_nnpalm_config_proto_init() {
	if File_chromiumos_config_api_software_nnpalm_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chromiumos_config_api_software_nnpalm_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NnpalmConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chromiumos_config_api_software_nnpalm_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chromiumos_config_api_software_nnpalm_config_proto_goTypes,
		DependencyIndexes: file_chromiumos_config_api_software_nnpalm_config_proto_depIdxs,
		MessageInfos:      file_chromiumos_config_api_software_nnpalm_config_proto_msgTypes,
	}.Build()
	File_chromiumos_config_api_software_nnpalm_config_proto = out.File
	file_chromiumos_config_api_software_nnpalm_config_proto_rawDesc = nil
	file_chromiumos_config_api_software_nnpalm_config_proto_goTypes = nil
	file_chromiumos_config_api_software_nnpalm_config_proto_depIdxs = nil
}
