# syntax=docker/dockerfile:1.4
# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

##############################################################################
FROM node:25 AS protogen_node

RUN apt-get update && apt-get install --no-install-recommends -yq \
    npm

WORKDIR /workspace

COPY dockerfiles/utilities/package*.json .
RUN npm install

ENV PATH="$PATH:/workspace/node_modules/.bin"

RUN mkdir -p generated/python
RUN mkdir -p generated/typescript
RUN mkdir -p server
COPY src/common/protos/*.proto server/
RUN npx protoc --plugin=protoc-gen-ng=$(which protoc-gen-ng) --ng_out=./generated/typescript server/*.proto

##############################################################################

FROM python:3-trixie AS protogen_python

WORKDIR /workspace
COPY dockerfiles/utilities/requirements.txt .
RUN python3 -m pip install -r requirements.txt --require-hashes --break-system-packages

RUN mkdir -p generated/python
RUN mkdir -p generated/typescript
RUN mkdir -p server/generated
COPY src/common/protos/*.proto server/generated/
RUN python3 -m grpc_tools.protoc -I. -I=$(python3 -c 'import site; print(site.getsitepackages()[0])')/grpc_tools/_proto/ --python_out=./generated/python --grpc_python_out=./generated/python server/generated/*.proto
RUN touch ./generated/python/server/generated/__init__.py


#######################################################################
FROM scratch AS copytohost

COPY --link --from=protogen_node /workspace/generated/typescript /typescript
COPY --link --from=protogen_python /workspace/generated/python /python
