#!/bin/bash
#
# Copyright 2021 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -e

readonly script_dir="$(dirname "$(realpath -e "${BASH_SOURCE[0]}")")"
cd "${script_dir}"

config/bin/build_config --output-dir config dut_attributes.star

# Replace tabs with spaces for easier diff.
sed -i 's/\t/  /g' "${script_dir}"/config/generated/dut_attributes.jsonproto
