# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_GPIO=y
CONFIG_MINIMAL_LIBC=y

CONFIG_I2C=y
CONFIG_ADC=y
# enable logs
CONFIG_LOG=y
# enable shell
CONFIG_SHELL=y
CONFIG_SHELL_TAB=y
CONFIG_SHELL_TAB_AUTOCOMPLETION=y
CONFIG_SHELL_BACKEND_SERIAL_INTERRUPT_DRIVEN=y
CONFIG_SHELL_BACKEND_SERIAL_RX_RING_BUFFER_SIZE=256
CONFIG_SHELL_PROMPT_UART="maui$ "
CONFIG_I2C_SHELL=y
# enable state machine framework
#CONFIG_SMF=y
# enable LED API
CONFIG_LED=y
# enable system reboot
CONFIG_REBOOT=y

CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_CLOCK_CONTROL=y

CONFIG_REGULATOR=y # This should have been selected by adc driver

CONFIG_LOG_BUFFER_SIZE=2048

# Enable Base64 for TPS FW update
CONFIG_BASE64=y

CONFIG_SBU_MUX_TYPE_PDC=y

CONFIG_TPS6699X_INTERRUPTS=y
