# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "dut_proto",
    srcs = ["dut.proto"],
    visibility = ["//visibility:public"],
    deps = ["//chromiumos/config/api:api_proto"],
)

go_proto_library(
    name = "dut_go_proto",
    importpath = "go.chromium.org/chromiumos/config/go/api/test/dut/v1",
    proto = ":dut_proto",
    visibility = ["//visibility:public"],
    deps = ["//chromiumos/config/api"],
)

go_library(
    name = "dut",
    embed = [":dut_go_proto"],
    importpath = "go.chromium.org/chromiumos/config/go/api/test/dut/v1",
    visibility = ["//visibility:public"],
)
