# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

description     "Run BOLS on labstation."
author          "seewaifu@chromium.org"

# Disable OOM killer, labstation should never kill servod.
oom score never

# Stop bols_labstation while shutting down.
stop on stopped system-services

start on started system-services

script
  exec >>/usr/local/tmp/${UPSTART_JOB}.log 2>&1
  set -x
  set +e

  /usr/local/bin/bols_labstation server
end script
