# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

description     "Start data part of servod"
author          "chromium-os-dev@chromium.org"

# Disable OOM killer, labstation should never kill servod.
oom score never

# Stop servod while shutting down.
start on started servod_core PORT=$PORT
stop on stopped system-services or stopping servod_core PORT=$PORT

respawn

# If you change the respawn limit, change the log rotation, below.
respawn limit 3 10

# This upstart job takes in 1 argument, PORT.
#  * Default PORT is 9999.
#  * The config file is determined by the port, and contains settings for
#    BOARD (mandatory) and SERIAL (optional, unless there's more than one
#    servo) and CONFIG (optional) used for passing an extra overlay file
#    to load.

env PORT=9999
env CONFIG_FILE_DIR="/var/lib/servod"
# Maximum log file number to keep around per log-level/port
# Each file is at most ~5MB, the occupancy should not exceed
# 5 * 100 = ~500MB.
env LOG_BACKUP_COUNT=100

import PORT

instance $PORT


pre-start script
  LOG="/var/log/servod_data_$PORT.STARTUP.log"
  {
    . /usr/share/cros/servod_utils.sh

    log_output \
        "Pre-start PORT=$PORT BOARD=$BOARD MODEL=$MODEL SERIAL=$SERIAL."

    CONFIG_FILE=$CONFIG_FILE_DIR/config_$PORT

    # Load all config values, especially the SERIAL, from the latest config file
    # in case of missing from command line.
    eval "$(cat $CONFIG_FILE)"

    log_output "Pre-start complete."
  } > $LOG 2>&1
end script

script
  LOG="/var/log/servod_data_$PORT.STARTUP.log"
  SERVO_MICRO_VIDPID=18d1:501a
  SERVO_V4_VIDPID=18d1:501b

  logger -t "${UPSTART_JOB}" "servod_data.conf start."
  . /usr/share/cros/servod_utils.sh
  logger -t "${UPSTART_JOB}" "Loaded servod_utils.sh."

  { log_output "Load config file."
    CONFIG_FILE=$CONFIG_FILE_DIR/config_$PORT
    if [ ! -f $CONFIG_FILE ]; then
      log_output "No configuration file ($CONFIG_FILE); terminating"
      stop
      exit 0
    fi

    # Config file must have the board and serial (in multi-servo environment)
    # declared like so:
    # BOARD=veyron_minnie
    # SERIAL=1234
    eval "$(cat $CONFIG_FILE)"

    GRPC_CORE_PORT="1${PORT}"
    GRPC_DATA_PORT="2${PORT}"

    GRPC_DATA_FLAGS="--grpc-core-host localhost \
      --grpc-core-port ${GRPC_CORE_PORT} --grpc-data-port ${GRPC_DATA_PORT}"
    PYTHON_DATA_PATH="/usr/lib/python3.11/site-packages/servo/data"
    GRPC_DATA_PATH="${PYTHON_DATA_PATH}/grpc_server/grpc_server_setup.py"

    if ([ -n "$SERVO_REBOOT" ] && [ -n "$SERIAL" ]); then
      servodtool device -s $SERIAL reboot || true
      sleep 5
    fi
  } >>$LOG 2>&1

  echo "Starting DATA $GRPC_DATA_PATH $GRPC_DATA_FLAGS" >> $LOG
  export GRPC_POLL_STRATEGY=epoll1
  export PYTHONPATH="/usr/lib/python3.11/site-packages"
  exec /usr/bin/python3 $GRPC_DATA_PATH $GRPC_DATA_FLAGS >> $LOG 2>&1
end script

pre-stop script
  # Log that the turn-down is coming from upstart rather than another source.
  dut-control -p $PORT "log_msg:Turning down servod from upstart script."
end script
