# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

description     "Run the Cambrionix firmware updater."
author          "chromium-os-dev@chromium.org"

start on started system-services

# It is exceedingly unlikely to OOM, as it's a simple dbus-send call,
# but better to kill it than to panic the system.
oom score -100


script
  exec >>/usr/local/tmp/${UPSTART_JOB}.log 2>&1
  set -x
  set +e

  /usr/local/bin/command-line-updater --path /usr/share/cambrionix/ --auto
end script
