# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from chromiumos.longrunning import operations_pb2 as chromiumos_dot_longrunning_dot_operations__pb2
from chromiumos.test.api import devboard_service_pb2 as chromiumos_dot_test_dot_api_dot_devboard__service__pb2


class DevboardServiceStub(object):
    """Provides the ability to start/stop DevboardService daemon and execute
    devboard dutcontrol commands on it. DevboardService daemon can be running
    either inside a Docker container or directly on the host.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartDevboardService = channel.unary_unary(
                '/chromiumos.test.api.DevboardService/StartDevboardService',
                request_serializer=chromiumos_dot_test_dot_api_dot_devboard__service__pb2.StartDevboardServiceRequest.SerializeToString,
                response_deserializer=chromiumos_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.StopDevboardService = channel.unary_unary(
                '/chromiumos.test.api.DevboardService/StopDevboardService',
                request_serializer=chromiumos_dot_test_dot_api_dot_devboard__service__pb2.StopDevboardServiceRequest.SerializeToString,
                response_deserializer=chromiumos_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )


class DevboardServiceServicer(object):
    """Provides the ability to start/stop DevboardService daemon and execute
    devboard dutcontrol commands on it. DevboardService daemon can be running
    either inside a Docker container or directly on the host.
    """

    def StartDevboardService(self, request, context):
        """StartDevboardService runs a gsc_dev_board Docker container and starts the
        service daemon inside the container.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopDevboardService(self, request, context):
        """StopDevboardService stops the daemon inside the container.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DevboardServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartDevboardService': grpc.unary_unary_rpc_method_handler(
                    servicer.StartDevboardService,
                    request_deserializer=chromiumos_dot_test_dot_api_dot_devboard__service__pb2.StartDevboardServiceRequest.FromString,
                    response_serializer=chromiumos_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'StopDevboardService': grpc.unary_unary_rpc_method_handler(
                    servicer.StopDevboardService,
                    request_deserializer=chromiumos_dot_test_dot_api_dot_devboard__service__pb2.StopDevboardServiceRequest.FromString,
                    response_serializer=chromiumos_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chromiumos.test.api.DevboardService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DevboardService(object):
    """Provides the ability to start/stop DevboardService daemon and execute
    devboard dutcontrol commands on it. DevboardService daemon can be running
    either inside a Docker container or directly on the host.
    """

    @staticmethod
    def StartDevboardService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chromiumos.test.api.DevboardService/StartDevboardService',
            chromiumos_dot_test_dot_api_dot_devboard__service__pb2.StartDevboardServiceRequest.SerializeToString,
            chromiumos_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopDevboardService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chromiumos.test.api.DevboardService/StopDevboardService',
            chromiumos_dot_test_dot_api_dot_devboard__service__pb2.StopDevboardServiceRequest.SerializeToString,
            chromiumos_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
