# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/test/api/devboard_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromiumos.longrunning import operations_pb2 as chromiumos_dot_longrunning_dot_operations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='chromiumos/test/api/devboard_service.proto',
  package='chromiumos.test.api',
  syntax='proto3',
  serialized_options=b'Z-go.chromium.org/chromiumos/config/go/test/api',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n*chromiumos/test/api/devboard_service.proto\x12\x13\x63hromiumos.test.api\x1a\'chromiumos/longrunning/operations.proto\"\xb6\x01\n\x1bStartDevboardServiceRequest\x12\x16\n\x0e\x63ontainer_name\x18\x01 \x01(\t\x12\x14\n\x0ctestbed_type\x18\x02 \x01(\t\x12\x12\n\ngsc_serial\x18\x03 \x01(\t\x12\x17\n\x0f\x64\x65\x62ugger_serial\x18\x04 \x01(\t\x12\x14\n\x0cservice_port\x18\x05 \x01(\t\x12\x17\n\x0f\x63ontainer_image\x18\x06 \x01(\t\x12\r\n\x05\x64\x65\x62ug\x18\x07 \x01(\x08\"\xf1\x01\n\x1cStartDevboardServiceResponse\x12L\n\x07success\x18\x01 \x01(\x0b\x32\x39.chromiumos.test.api.StartDevboardServiceResponse.SuccessH\x00\x12L\n\x07\x66\x61ilure\x18\x02 \x01(\x0b\x32\x39.chromiumos.test.api.StartDevboardServiceResponse.FailureH\x00\x1a\t\n\x07Success\x1a \n\x07\x46\x61ilure\x12\x15\n\rerror_message\x18\x01 \x01(\tB\x08\n\x06result\"\x1e\n\x1cStartDevboardServiceMetadata\"4\n\x1aStopDevboardServiceRequest\x12\x16\n\x0e\x63ontainer_name\x18\x01 \x01(\t\"\xee\x01\n\x1bStopDevboardServiceResponse\x12K\n\x07success\x18\x01 \x01(\x0b\x32\x38.chromiumos.test.api.StopDevboardServiceResponse.SuccessH\x00\x12K\n\x07\x66\x61ilure\x18\x02 \x01(\x0b\x32\x38.chromiumos.test.api.StopDevboardServiceResponse.FailureH\x00\x1a\t\n\x07Success\x1a \n\x07\x46\x61ilure\x12\x15\n\rerror_message\x18\x01 \x01(\tB\x08\n\x06result\"\x1d\n\x1bStopDevboardServiceMetadata2\xeb\x02\n\x0f\x44\x65vboardService\x12\xac\x01\n\x14StartDevboardService\x12\x30.chromiumos.test.api.StartDevboardServiceRequest\x1a!.chromiumos.longrunning.Operation\"?\xd2\x41<\n\x1cStartDevboardServiceResponse\x12\x1cStartDevboardServiceMetadata\x12\xa8\x01\n\x13StopDevboardService\x12/.chromiumos.test.api.StopDevboardServiceRequest\x1a!.chromiumos.longrunning.Operation\"=\xd2\x41:\n\x1bStopDevboardServiceResponse\x12\x1bStopDevboardServiceMetadataB/Z-go.chromium.org/chromiumos/config/go/test/apib\x06proto3'
  ,
  dependencies=[chromiumos_dot_longrunning_dot_operations__pb2.DESCRIPTOR,])




_STARTDEVBOARDSERVICEREQUEST = _descriptor.Descriptor(
  name='StartDevboardServiceRequest',
  full_name='chromiumos.test.api.StartDevboardServiceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='container_name', full_name='chromiumos.test.api.StartDevboardServiceRequest.container_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='testbed_type', full_name='chromiumos.test.api.StartDevboardServiceRequest.testbed_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gsc_serial', full_name='chromiumos.test.api.StartDevboardServiceRequest.gsc_serial', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='debugger_serial', full_name='chromiumos.test.api.StartDevboardServiceRequest.debugger_serial', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='service_port', full_name='chromiumos.test.api.StartDevboardServiceRequest.service_port', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='container_image', full_name='chromiumos.test.api.StartDevboardServiceRequest.container_image', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='debug', full_name='chromiumos.test.api.StartDevboardServiceRequest.debug', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=291,
)


_STARTDEVBOARDSERVICERESPONSE_SUCCESS = _descriptor.Descriptor(
  name='Success',
  full_name='chromiumos.test.api.StartDevboardServiceResponse.Success',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=482,
  serialized_end=491,
)

_STARTDEVBOARDSERVICERESPONSE_FAILURE = _descriptor.Descriptor(
  name='Failure',
  full_name='chromiumos.test.api.StartDevboardServiceResponse.Failure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_message', full_name='chromiumos.test.api.StartDevboardServiceResponse.Failure.error_message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=493,
  serialized_end=525,
)

_STARTDEVBOARDSERVICERESPONSE = _descriptor.Descriptor(
  name='StartDevboardServiceResponse',
  full_name='chromiumos.test.api.StartDevboardServiceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='chromiumos.test.api.StartDevboardServiceResponse.success', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='failure', full_name='chromiumos.test.api.StartDevboardServiceResponse.failure', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_STARTDEVBOARDSERVICERESPONSE_SUCCESS, _STARTDEVBOARDSERVICERESPONSE_FAILURE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='result', full_name='chromiumos.test.api.StartDevboardServiceResponse.result',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=294,
  serialized_end=535,
)


_STARTDEVBOARDSERVICEMETADATA = _descriptor.Descriptor(
  name='StartDevboardServiceMetadata',
  full_name='chromiumos.test.api.StartDevboardServiceMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=537,
  serialized_end=567,
)


_STOPDEVBOARDSERVICEREQUEST = _descriptor.Descriptor(
  name='StopDevboardServiceRequest',
  full_name='chromiumos.test.api.StopDevboardServiceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='container_name', full_name='chromiumos.test.api.StopDevboardServiceRequest.container_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=569,
  serialized_end=621,
)


_STOPDEVBOARDSERVICERESPONSE_SUCCESS = _descriptor.Descriptor(
  name='Success',
  full_name='chromiumos.test.api.StopDevboardServiceResponse.Success',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=482,
  serialized_end=491,
)

_STOPDEVBOARDSERVICERESPONSE_FAILURE = _descriptor.Descriptor(
  name='Failure',
  full_name='chromiumos.test.api.StopDevboardServiceResponse.Failure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_message', full_name='chromiumos.test.api.StopDevboardServiceResponse.Failure.error_message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=493,
  serialized_end=525,
)

_STOPDEVBOARDSERVICERESPONSE = _descriptor.Descriptor(
  name='StopDevboardServiceResponse',
  full_name='chromiumos.test.api.StopDevboardServiceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='chromiumos.test.api.StopDevboardServiceResponse.success', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='failure', full_name='chromiumos.test.api.StopDevboardServiceResponse.failure', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_STOPDEVBOARDSERVICERESPONSE_SUCCESS, _STOPDEVBOARDSERVICERESPONSE_FAILURE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='result', full_name='chromiumos.test.api.StopDevboardServiceResponse.result',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=624,
  serialized_end=862,
)


_STOPDEVBOARDSERVICEMETADATA = _descriptor.Descriptor(
  name='StopDevboardServiceMetadata',
  full_name='chromiumos.test.api.StopDevboardServiceMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=864,
  serialized_end=893,
)

_STARTDEVBOARDSERVICERESPONSE_SUCCESS.containing_type = _STARTDEVBOARDSERVICERESPONSE
_STARTDEVBOARDSERVICERESPONSE_FAILURE.containing_type = _STARTDEVBOARDSERVICERESPONSE
_STARTDEVBOARDSERVICERESPONSE.fields_by_name['success'].message_type = _STARTDEVBOARDSERVICERESPONSE_SUCCESS
_STARTDEVBOARDSERVICERESPONSE.fields_by_name['failure'].message_type = _STARTDEVBOARDSERVICERESPONSE_FAILURE
_STARTDEVBOARDSERVICERESPONSE.oneofs_by_name['result'].fields.append(
  _STARTDEVBOARDSERVICERESPONSE.fields_by_name['success'])
_STARTDEVBOARDSERVICERESPONSE.fields_by_name['success'].containing_oneof = _STARTDEVBOARDSERVICERESPONSE.oneofs_by_name['result']
_STARTDEVBOARDSERVICERESPONSE.oneofs_by_name['result'].fields.append(
  _STARTDEVBOARDSERVICERESPONSE.fields_by_name['failure'])
_STARTDEVBOARDSERVICERESPONSE.fields_by_name['failure'].containing_oneof = _STARTDEVBOARDSERVICERESPONSE.oneofs_by_name['result']
_STOPDEVBOARDSERVICERESPONSE_SUCCESS.containing_type = _STOPDEVBOARDSERVICERESPONSE
_STOPDEVBOARDSERVICERESPONSE_FAILURE.containing_type = _STOPDEVBOARDSERVICERESPONSE
_STOPDEVBOARDSERVICERESPONSE.fields_by_name['success'].message_type = _STOPDEVBOARDSERVICERESPONSE_SUCCESS
_STOPDEVBOARDSERVICERESPONSE.fields_by_name['failure'].message_type = _STOPDEVBOARDSERVICERESPONSE_FAILURE
_STOPDEVBOARDSERVICERESPONSE.oneofs_by_name['result'].fields.append(
  _STOPDEVBOARDSERVICERESPONSE.fields_by_name['success'])
_STOPDEVBOARDSERVICERESPONSE.fields_by_name['success'].containing_oneof = _STOPDEVBOARDSERVICERESPONSE.oneofs_by_name['result']
_STOPDEVBOARDSERVICERESPONSE.oneofs_by_name['result'].fields.append(
  _STOPDEVBOARDSERVICERESPONSE.fields_by_name['failure'])
_STOPDEVBOARDSERVICERESPONSE.fields_by_name['failure'].containing_oneof = _STOPDEVBOARDSERVICERESPONSE.oneofs_by_name['result']
DESCRIPTOR.message_types_by_name['StartDevboardServiceRequest'] = _STARTDEVBOARDSERVICEREQUEST
DESCRIPTOR.message_types_by_name['StartDevboardServiceResponse'] = _STARTDEVBOARDSERVICERESPONSE
DESCRIPTOR.message_types_by_name['StartDevboardServiceMetadata'] = _STARTDEVBOARDSERVICEMETADATA
DESCRIPTOR.message_types_by_name['StopDevboardServiceRequest'] = _STOPDEVBOARDSERVICEREQUEST
DESCRIPTOR.message_types_by_name['StopDevboardServiceResponse'] = _STOPDEVBOARDSERVICERESPONSE
DESCRIPTOR.message_types_by_name['StopDevboardServiceMetadata'] = _STOPDEVBOARDSERVICEMETADATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartDevboardServiceRequest = _reflection.GeneratedProtocolMessageType('StartDevboardServiceRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTDEVBOARDSERVICEREQUEST,
  '__module__' : 'chromiumos.test.api.devboard_service_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.StartDevboardServiceRequest)
  })
_sym_db.RegisterMessage(StartDevboardServiceRequest)

StartDevboardServiceResponse = _reflection.GeneratedProtocolMessageType('StartDevboardServiceResponse', (_message.Message,), {

  'Success' : _reflection.GeneratedProtocolMessageType('Success', (_message.Message,), {
    'DESCRIPTOR' : _STARTDEVBOARDSERVICERESPONSE_SUCCESS,
    '__module__' : 'chromiumos.test.api.devboard_service_pb2'
    # @@protoc_insertion_point(class_scope:chromiumos.test.api.StartDevboardServiceResponse.Success)
    })
  ,

  'Failure' : _reflection.GeneratedProtocolMessageType('Failure', (_message.Message,), {
    'DESCRIPTOR' : _STARTDEVBOARDSERVICERESPONSE_FAILURE,
    '__module__' : 'chromiumos.test.api.devboard_service_pb2'
    # @@protoc_insertion_point(class_scope:chromiumos.test.api.StartDevboardServiceResponse.Failure)
    })
  ,
  'DESCRIPTOR' : _STARTDEVBOARDSERVICERESPONSE,
  '__module__' : 'chromiumos.test.api.devboard_service_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.StartDevboardServiceResponse)
  })
_sym_db.RegisterMessage(StartDevboardServiceResponse)
_sym_db.RegisterMessage(StartDevboardServiceResponse.Success)
_sym_db.RegisterMessage(StartDevboardServiceResponse.Failure)

StartDevboardServiceMetadata = _reflection.GeneratedProtocolMessageType('StartDevboardServiceMetadata', (_message.Message,), {
  'DESCRIPTOR' : _STARTDEVBOARDSERVICEMETADATA,
  '__module__' : 'chromiumos.test.api.devboard_service_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.StartDevboardServiceMetadata)
  })
_sym_db.RegisterMessage(StartDevboardServiceMetadata)

StopDevboardServiceRequest = _reflection.GeneratedProtocolMessageType('StopDevboardServiceRequest', (_message.Message,), {
  'DESCRIPTOR' : _STOPDEVBOARDSERVICEREQUEST,
  '__module__' : 'chromiumos.test.api.devboard_service_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.StopDevboardServiceRequest)
  })
_sym_db.RegisterMessage(StopDevboardServiceRequest)

StopDevboardServiceResponse = _reflection.GeneratedProtocolMessageType('StopDevboardServiceResponse', (_message.Message,), {

  'Success' : _reflection.GeneratedProtocolMessageType('Success', (_message.Message,), {
    'DESCRIPTOR' : _STOPDEVBOARDSERVICERESPONSE_SUCCESS,
    '__module__' : 'chromiumos.test.api.devboard_service_pb2'
    # @@protoc_insertion_point(class_scope:chromiumos.test.api.StopDevboardServiceResponse.Success)
    })
  ,

  'Failure' : _reflection.GeneratedProtocolMessageType('Failure', (_message.Message,), {
    'DESCRIPTOR' : _STOPDEVBOARDSERVICERESPONSE_FAILURE,
    '__module__' : 'chromiumos.test.api.devboard_service_pb2'
    # @@protoc_insertion_point(class_scope:chromiumos.test.api.StopDevboardServiceResponse.Failure)
    })
  ,
  'DESCRIPTOR' : _STOPDEVBOARDSERVICERESPONSE,
  '__module__' : 'chromiumos.test.api.devboard_service_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.StopDevboardServiceResponse)
  })
_sym_db.RegisterMessage(StopDevboardServiceResponse)
_sym_db.RegisterMessage(StopDevboardServiceResponse.Success)
_sym_db.RegisterMessage(StopDevboardServiceResponse.Failure)

StopDevboardServiceMetadata = _reflection.GeneratedProtocolMessageType('StopDevboardServiceMetadata', (_message.Message,), {
  'DESCRIPTOR' : _STOPDEVBOARDSERVICEMETADATA,
  '__module__' : 'chromiumos.test.api.devboard_service_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.StopDevboardServiceMetadata)
  })
_sym_db.RegisterMessage(StopDevboardServiceMetadata)


DESCRIPTOR._options = None

_DEVBOARDSERVICE = _descriptor.ServiceDescriptor(
  name='DevboardService',
  full_name='chromiumos.test.api.DevboardService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=896,
  serialized_end=1259,
  methods=[
  _descriptor.MethodDescriptor(
    name='StartDevboardService',
    full_name='chromiumos.test.api.DevboardService.StartDevboardService',
    index=0,
    containing_service=None,
    input_type=_STARTDEVBOARDSERVICEREQUEST,
    output_type=chromiumos_dot_longrunning_dot_operations__pb2._OPERATION,
    serialized_options=b'\322A<\n\034StartDevboardServiceResponse\022\034StartDevboardServiceMetadata',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StopDevboardService',
    full_name='chromiumos.test.api.DevboardService.StopDevboardService',
    index=1,
    containing_service=None,
    input_type=_STOPDEVBOARDSERVICEREQUEST,
    output_type=chromiumos_dot_longrunning_dot_operations__pb2._OPERATION,
    serialized_options=b'\322A:\n\033StopDevboardServiceResponse\022\033StopDevboardServiceMetadata',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEVBOARDSERVICE)

DESCRIPTOR.services_by_name['DevboardService'] = _DEVBOARDSERVICE

# @@protoc_insertion_point(module_scope)
