[package]
name = "spdm_test_deps"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[lib]
name = "spdm_test_deps"

[dependencies]
spdm_types = { path = "../spdm-types" }
mocktopus = { version = "0.8.0", optional = true } # ignored unless use.spdm_unstable_tests by ebuild
uninit = { version = "0.6", default-features = false }

[features]
# The mocktopus dependencies are only used when this feature is active because
# CrOS ebuild doesn't support unstable rust features used by mocktopus by
# default.
mock = [ "mocktopus" ] # ignored unless use.spdm_unstable_tests by ebuild
