# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from chromiumos.test.api.lsnexus import lsnexus_service_pb2 as chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2


class LSNexusServiceStub(object):
    """Provides the ability to interact with a labstation/container and
    its peripherals such as servo and dolos.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartServod = channel.unary_unary(
                '/chromiumos.test.api.lsnexus.LSNexusService/StartServod',
                request_serializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.StartServodRequest.SerializeToString,
                response_deserializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.StartServodResponse.FromString,
                )
        self.StopServod = channel.unary_unary(
                '/chromiumos.test.api.lsnexus.LSNexusService/StopServod',
                request_serializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.StopServodRequest.SerializeToString,
                response_deserializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.StopServodResponse.FromString,
                )
        self.CallServod = channel.unary_unary(
                '/chromiumos.test.api.lsnexus.LSNexusService/CallServod',
                request_serializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.CallServodRequest.SerializeToString,
                response_deserializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.CallServodResponse.FromString,
                )
        self.GetFile = channel.unary_stream(
                '/chromiumos.test.api.lsnexus.LSNexusService/GetFile',
                request_serializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.GetFileRequest.SerializeToString,
                response_deserializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.GetFileResponse.FromString,
                )
        self.PutFile = channel.stream_unary(
                '/chromiumos.test.api.lsnexus.LSNexusService/PutFile',
                request_serializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.PutFileRequest.SerializeToString,
                response_deserializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.PutFileResponse.FromString,
                )
        self.RemoveFile = channel.unary_unary(
                '/chromiumos.test.api.lsnexus.LSNexusService/RemoveFile',
                request_serializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.RemoveFileRequest.SerializeToString,
                response_deserializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.RemoveFileResponse.FromString,
                )
        self.MakeDir = channel.unary_unary(
                '/chromiumos.test.api.lsnexus.LSNexusService/MakeDir',
                request_serializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.MakeDirRequest.SerializeToString,
                response_deserializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.MakeDirResponse.FromString,
                )
        self.RemoveDir = channel.unary_unary(
                '/chromiumos.test.api.lsnexus.LSNexusService/RemoveDir',
                request_serializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.RemoveDirRequest.SerializeToString,
                response_deserializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.RemoveDirResponse.FromString,
                )
        self.MakeTempDir = channel.unary_unary(
                '/chromiumos.test.api.lsnexus.LSNexusService/MakeTempDir',
                request_serializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.MakeTempDirRequest.SerializeToString,
                response_deserializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.MakeTempDirResponse.FromString,
                )
        self.DMesg = channel.unary_stream(
                '/chromiumos.test.api.lsnexus.LSNexusService/DMesg',
                request_serializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.DMesgRequest.SerializeToString,
                response_deserializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.DMesgResponse.FromString,
                )
        self.Echo = channel.unary_unary(
                '/chromiumos.test.api.lsnexus.LSNexusService/Echo',
                request_serializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.EchoRequest.SerializeToString,
                response_deserializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.EchoResponse.FromString,
                )
        self.DownloadServoLogs = channel.unary_unary(
                '/chromiumos.test.api.lsnexus.LSNexusService/DownloadServoLogs',
                request_serializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.DownloadServoLogsRequest.SerializeToString,
                response_deserializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.DownloadServoLogsResponse.FromString,
                )
        self.RunFutility = channel.unary_unary(
                '/chromiumos.test.api.lsnexus.LSNexusService/RunFutility',
                request_serializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.RunFutilityRequest.SerializeToString,
                response_deserializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.RunFutilityResponse.FromString,
                )
        self.RunFlashEC = channel.unary_unary(
                '/chromiumos.test.api.lsnexus.LSNexusService/RunFlashEC',
                request_serializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.RunFlashECRequest.SerializeToString,
                response_deserializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.RunFlashECResponse.FromString,
                )
        self.RunGSCTool = channel.unary_unary(
                '/chromiumos.test.api.lsnexus.LSNexusService/RunGSCTool',
                request_serializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.RunGSCToolRequest.SerializeToString,
                response_deserializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.RunGSCToolResponse.FromString,
                )
        self.RunUARTStressTester = channel.unary_unary(
                '/chromiumos.test.api.lsnexus.LSNexusService/RunUARTStressTester',
                request_serializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.RunUARTStressTesterRequest.SerializeToString,
                response_deserializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.RunUARTStressTesterResponse.FromString,
                )


class LSNexusServiceServicer(object):
    """Provides the ability to interact with a labstation/container and
    its peripherals such as servo and dolos.
    """

    def StartServod(self, request, context):
        """StartServod runs a servod daemon.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopServod(self, request, context):
        """StopServod stops the servod daemon.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallServod(self, request, context):
        """CallServod runs a servod command.
        Allowed methods: doc, get, set, and hwinit.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFile(self, request, context):
        """GetFile gets a file from labstation/container.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutFile(self, request_iterator, context):
        """PutFile puts a file on labstation/container.
        If the directory of destination path does not exist, this service
        will also create the directory.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveFile(self, request, context):
        """RemoveFile removes a file on labstation/container.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakeDir(self, request, context):
        """MakeDir make a directory on the labstation/container.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveDir(self, request, context):
        """RemoveDir removes a directory from labstation/container.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakeTempDir(self, request, context):
        """MakeTempDir makes an unique temporary directory on the
        labstation/container.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DMesg(self, request, context):
        """DMesg returns the output from the dmesg command.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Echo(self, request, context):
        """Echo calls the Servo echo method.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadServoLogs(self, request, context):
        """DownloadServoLogs will save servod related logs from the labstation or
        container where servod is running to LSNexus' directory
        Logs include:
        /var/log/servo_<port>/ latest.DEBUG from servod host.
        /var/log/servo_<port>.STARTUP.log from servod host.
        The extraction of the MCU console logs from latest.DEBUG
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunFutility(self, request, context):
        """/////// Firmware tool API /////////

        RunFutility forwards futility request to BOLS.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunFlashEC(self, request, context):
        """RunFlashEC forwards EC firmware flashing request to BOLS.
        In most of implementation, it runs flash_ec tool on labstation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunGSCTool(self, request, context):
        """RunGSCTool forwards gsctool request to BOLS.
        Example:
        gsctool -n 1002D052-9066B226 -f
        Params: ["-n", "1002D052-9066B226", "-f" ]
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunUARTStressTester(self, request, context):
        """RunUARTStressTester forwards uart_stress_tester.py request to BOLS.
        uart_stress_tester.py repeats sending a uart console command
        to each UART device for a given time, and check if output
        has any missing characters.
        Example:
        uart_stress_tester.py /dev/ttyUSB2 --time 3600
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LSNexusServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartServod': grpc.unary_unary_rpc_method_handler(
                    servicer.StartServod,
                    request_deserializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.StartServodRequest.FromString,
                    response_serializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.StartServodResponse.SerializeToString,
            ),
            'StopServod': grpc.unary_unary_rpc_method_handler(
                    servicer.StopServod,
                    request_deserializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.StopServodRequest.FromString,
                    response_serializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.StopServodResponse.SerializeToString,
            ),
            'CallServod': grpc.unary_unary_rpc_method_handler(
                    servicer.CallServod,
                    request_deserializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.CallServodRequest.FromString,
                    response_serializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.CallServodResponse.SerializeToString,
            ),
            'GetFile': grpc.unary_stream_rpc_method_handler(
                    servicer.GetFile,
                    request_deserializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.GetFileRequest.FromString,
                    response_serializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.GetFileResponse.SerializeToString,
            ),
            'PutFile': grpc.stream_unary_rpc_method_handler(
                    servicer.PutFile,
                    request_deserializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.PutFileRequest.FromString,
                    response_serializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.PutFileResponse.SerializeToString,
            ),
            'RemoveFile': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveFile,
                    request_deserializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.RemoveFileRequest.FromString,
                    response_serializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.RemoveFileResponse.SerializeToString,
            ),
            'MakeDir': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeDir,
                    request_deserializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.MakeDirRequest.FromString,
                    response_serializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.MakeDirResponse.SerializeToString,
            ),
            'RemoveDir': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveDir,
                    request_deserializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.RemoveDirRequest.FromString,
                    response_serializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.RemoveDirResponse.SerializeToString,
            ),
            'MakeTempDir': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeTempDir,
                    request_deserializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.MakeTempDirRequest.FromString,
                    response_serializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.MakeTempDirResponse.SerializeToString,
            ),
            'DMesg': grpc.unary_stream_rpc_method_handler(
                    servicer.DMesg,
                    request_deserializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.DMesgRequest.FromString,
                    response_serializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.DMesgResponse.SerializeToString,
            ),
            'Echo': grpc.unary_unary_rpc_method_handler(
                    servicer.Echo,
                    request_deserializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.EchoRequest.FromString,
                    response_serializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.EchoResponse.SerializeToString,
            ),
            'DownloadServoLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadServoLogs,
                    request_deserializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.DownloadServoLogsRequest.FromString,
                    response_serializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.DownloadServoLogsResponse.SerializeToString,
            ),
            'RunFutility': grpc.unary_unary_rpc_method_handler(
                    servicer.RunFutility,
                    request_deserializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.RunFutilityRequest.FromString,
                    response_serializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.RunFutilityResponse.SerializeToString,
            ),
            'RunFlashEC': grpc.unary_unary_rpc_method_handler(
                    servicer.RunFlashEC,
                    request_deserializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.RunFlashECRequest.FromString,
                    response_serializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.RunFlashECResponse.SerializeToString,
            ),
            'RunGSCTool': grpc.unary_unary_rpc_method_handler(
                    servicer.RunGSCTool,
                    request_deserializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.RunGSCToolRequest.FromString,
                    response_serializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.RunGSCToolResponse.SerializeToString,
            ),
            'RunUARTStressTester': grpc.unary_unary_rpc_method_handler(
                    servicer.RunUARTStressTester,
                    request_deserializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.RunUARTStressTesterRequest.FromString,
                    response_serializer=chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.RunUARTStressTesterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chromiumos.test.api.lsnexus.LSNexusService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LSNexusService(object):
    """Provides the ability to interact with a labstation/container and
    its peripherals such as servo and dolos.
    """

    @staticmethod
    def StartServod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chromiumos.test.api.lsnexus.LSNexusService/StartServod',
            chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.StartServodRequest.SerializeToString,
            chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.StartServodResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopServod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chromiumos.test.api.lsnexus.LSNexusService/StopServod',
            chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.StopServodRequest.SerializeToString,
            chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.StopServodResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CallServod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chromiumos.test.api.lsnexus.LSNexusService/CallServod',
            chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.CallServodRequest.SerializeToString,
            chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.CallServodResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/chromiumos.test.api.lsnexus.LSNexusService/GetFile',
            chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.GetFileRequest.SerializeToString,
            chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.GetFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PutFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/chromiumos.test.api.lsnexus.LSNexusService/PutFile',
            chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.PutFileRequest.SerializeToString,
            chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.PutFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chromiumos.test.api.lsnexus.LSNexusService/RemoveFile',
            chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.RemoveFileRequest.SerializeToString,
            chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.RemoveFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MakeDir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chromiumos.test.api.lsnexus.LSNexusService/MakeDir',
            chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.MakeDirRequest.SerializeToString,
            chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.MakeDirResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveDir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chromiumos.test.api.lsnexus.LSNexusService/RemoveDir',
            chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.RemoveDirRequest.SerializeToString,
            chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.RemoveDirResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MakeTempDir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chromiumos.test.api.lsnexus.LSNexusService/MakeTempDir',
            chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.MakeTempDirRequest.SerializeToString,
            chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.MakeTempDirResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DMesg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/chromiumos.test.api.lsnexus.LSNexusService/DMesg',
            chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.DMesgRequest.SerializeToString,
            chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.DMesgResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Echo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chromiumos.test.api.lsnexus.LSNexusService/Echo',
            chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.EchoRequest.SerializeToString,
            chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.EchoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DownloadServoLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chromiumos.test.api.lsnexus.LSNexusService/DownloadServoLogs',
            chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.DownloadServoLogsRequest.SerializeToString,
            chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.DownloadServoLogsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RunFutility(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chromiumos.test.api.lsnexus.LSNexusService/RunFutility',
            chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.RunFutilityRequest.SerializeToString,
            chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.RunFutilityResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RunFlashEC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chromiumos.test.api.lsnexus.LSNexusService/RunFlashEC',
            chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.RunFlashECRequest.SerializeToString,
            chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.RunFlashECResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RunGSCTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chromiumos.test.api.lsnexus.LSNexusService/RunGSCTool',
            chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.RunGSCToolRequest.SerializeToString,
            chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.RunGSCToolResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RunUARTStressTester(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chromiumos.test.api.lsnexus.LSNexusService/RunUARTStressTester',
            chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.RunUARTStressTesterRequest.SerializeToString,
            chromiumos_dot_test_dot_api_dot_lsnexus_dot_lsnexus__service__pb2.RunUARTStressTesterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
