# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "longrunning_proto",
    srcs = ["operations.proto"],
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_protobuf//:any_proto",
        "@com_google_protobuf//:descriptor_proto",
        "@com_google_protobuf//:duration_proto",
        "@com_google_protobuf//:empty_proto",
    ],
)

go_proto_library(
    name = "longrunning_go_proto",
    compilers = ["@io_bazel_rules_go//proto:go_grpc"],
    importpath = "go.chromium.org/chromiumos/config/go/api/test/tls/dependencies/longrunning",
    proto = ":longrunning_proto",
    visibility = ["//visibility:public"],
)

go_library(
    name = "longrunning",
    embed = [":longrunning_go_proto"],
    importpath = "go.chromium.org/chromiumos/config/go/api/test/tls/dependencies/longrunning",
    visibility = ["//visibility:public"],
)
