# Copyright 2022 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

workspace(name = "rules_cros")

load("//cros:repositories.bzl", "rules_cros_dependencies")

rules_cros_dependencies()
