[workspace]
resolver = "2"

members = [
    "one_time_init",
    "one_time_init_loader",
    "stage0",
    "stage1_app",
    "stm32g0_i2c_peripheral",
]

# Optimize all dependencies
[profile.dev.package."*"]
opt-level = "z"
codegen-units = 1

[profile.release.package."*"]
opt-level = "z"
codegen-units = 1

[profile.dev]
lto = true
opt-level = "z"
panic = "abort"

[profile.release]
debug = true
lto = true
opt-level = "z"
panic = "abort"
