#!/usr/bin/env python3

# Copyright 2022 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Prints output from the proto2 AVR UART."""

import os
import sys

import pyftdi.serialext


def main():
    port = pyftdi.serialext.serial_for_url(
        'ftdi://ftdi:4232h/4', baudrate=9600)
    out = os.fdopen(sys.stdout.fileno(), 'wb', 0)
    try:
        while True:
            out.write(port.read(1))
    except KeyboardInterrupt:
        pass


if __name__ == '__main__':
    main()
