#!/bin/bash

# Copyright 2022 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -e

PROJECT_ROOT=$(realpath "$(dirname "${BASH_SOURCE[0]}")"/..)

cd "${PROJECT_ROOT}/rust/mcu"
cargo build \
    -p stage1_app \
    --no-default-features \
    --features proto2,standalone,dev,image-transfer,no-hash-check \
    "$@"
