#!/bin/bash

# Copyright 2021 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Compiles hps-factory as a static binary

set -e
PROJECT_ROOT=$(realpath "$(dirname "${BASH_SOURCE[0]}")"/..)

source "${PROJECT_ROOT}/environment"

cd "${PROJECT_ROOT}/rust"

# Force rerun of build.rs, otherwise changes in the various crates that it
# embeds might not be picked up.
touch hps-factory/build.rs

RUSTFLAGS='-C link-arg=-s' \
    cargo build \
    --release \
    --target x86_64-unknown-linux-musl \
    -p hps-factory \
    --no-default-features \
    --features image-transfer,all-embedded-firmware

echo "Succesfully built statically linked hps-factory:"
ls -lh "${PROJECT_ROOT}/rust/target/x86_64-unknown-linux-musl/release/hps-factory"
