#!/bin/bash

# Copyright 2022 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Compiles sign-rom as a static binary with no libc dependencies

set -e
PROJECT_ROOT=$(realpath "$(dirname "${BASH_SOURCE[0]}")"/..)

cd "${PROJECT_ROOT}/rust"

cargo build \
    --release \
    --target x86_64-unknown-linux-musl \
    -p sign-rom

echo "Successfully built statically linked sign-rom:"
ls -lh "${PROJECT_ROOT}/rust/target/x86_64-unknown-linux-musl/release/sign-rom"
