#!/bin/bash

# Copyright 2022 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This script is not intended to be run directly. Rather it is intended to
# invoke symbolic links that point to it. It then runs the binary with the same
# name as the symbolic link inside the ChromeOS chroot.

set -o pipefail

WD=$(realpath "${PWD}")
CHROMIUMOS="${WD%/src/platform*}"
CHROOT="${CHROMIUMOS}/chroot"

# Determine the name of the symbolic link that was invoked.
PROG="$(basename "$0")"

# When something (generally rust-analyzer) runs `rustc --print sysroot`, prefix
# the output with the chroot path, so that it's a valid path outside the chroot.
if [[ "${PROG}" = "rustc" && "$1" = "--print" && "$2" = "sysroot" ]]; then
    echo -n "${CHROOT}"
fi

mkdir -p "${CHROOT}/home/${USER}/.cargo" "${HOME}/.cargo"

function run_command {
    bwrap \
        --bind "${CHROOT}" / \
        --bind "${HOME}" "${HOME}" \
        --bind "${CHROOT}/home/${USER}/.cargo" "${HOME}/.cargo" \
        --dev-bind /dev /dev \
        --proc /proc \
        --setenv PATH /opt/hps-sdk/bin:/usr/bin:/bin:/usr/sbin \
        "${PROG}" \
        "$@"
}

if [[ "$1" == "metadata" ]]; then
    # When running `cargo metadata`, map any paths to /build to the
    # corresponding out-of-chroot path. This allow rust-analyzer to find sources
    # for our dependent crates.
    run_command "$@" | sed "s#\"/build/#\"${CHROOT}/build/#g"
else
    # Don't pipe output through sed, otherwise interactive commands like hps-mon
    # won't work.
    run_command "$@"
fi
