#!/bin/bash

# Copyright 2021 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Builds and runs the Rust SOC ROM. ./scripts/proto2-openocd should already be
# running in a separate shell and the MCU ROM should already be flashed.

set -e

PROJECT_ROOT=$(git rev-parse --show-toplevel)

"${PROJECT_ROOT}/scripts/run-dev" --nomcu "$@"
