#!/bin/bash

# Copyright 2021 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -e

PROJECT_ROOT=$(realpath "$(dirname "${BASH_SOURCE[0]}")"/..)

cd "${PROJECT_ROOT}/rust"
cargo run -p hps-mon \
    --features direct \
    -- \
    --gateware "${PROJECT_ROOT}/build/hps_platform/gateware/hps_platform.bit" \
    --soc-rom "${PROJECT_ROOT}/build/hps_platform/fpga_rom.bin" \
    --no-mcp-i2c \
    "$@"
