#!/bin/bash

# Copyright 2021 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -e

PROJECT_ROOT=$(realpath "$(dirname "${BASH_SOURCE[0]}")"/..)

openocd \
    -f "${PROJECT_ROOT}/toolchain/mcu_dev/proto2.openocd.cfg" \
    --search tcl \
    -c "init; halt; flash erase_address 0x08000000 0x20000; exit"
