#!/bin/bash

# Copyright 2022 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -e

PROJECT_ROOT=$(realpath "$(dirname "${BASH_SOURCE[0]}")"/..)

openocd \
    -f "${PROJECT_ROOT}/toolchain/mcu_dev/proto2.openocd.cfg" \
    -c "gdb_port 3333" \
    -c "telnet_port 4444" \
    -c "tcl_port 6666" \
    --search tcl \
    "$@"
