[package]
name = "spdm-responder-ffi"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[lib]
name = "spdm_responder"
crate-type = ["staticlib"]

[dependencies]
spdm = { path = "../spdm-core", default-features = false }
spdm_types = { path = "../spdm-types" }
uninit = { version = "0.6", default-features = false }
spdm_responder = { path = "../spdm-responder" }

[features]
default = ["std"]
std = []
