# Copyright 2022 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# Generate version information for the firmware binary

import argparse
import pathlib
import subprocess
import sys

DIR = pathlib.Path(__file__).resolve().parent


def git_hash():
    cmd = "git describe --abbrev=12 --always --dirty"
    git_version = subprocess.check_output(cmd.split(), cwd=DIR)
    git_version = git_version.decode().strip()
    return git_version


def generate_defines(keyvals):
    text = "/* Defines */\n"
    for key, val in keyvals.items():
        line = f'#define {key} "{val}"\n'
        text += line
    return text


def write_file(path):

    git_hash_txt = git_hash()

    keyvals = {"GIT_HASH": git_hash_txt}

    text = "/* File generated by generate_build_info.py */\n"
    text += generate_defines(keyvals)

    path.write_text(text)


def main():
    parser = argparse.ArgumentParser(allow_abbrev=False)
    parser.add_argument("path", help="Path of output file")
    args = parser.parse_args()
    path = pathlib.Path(args.path)

    write_file(path)


if __name__ == "__main__":
    sys.exit(main())
