// Copyright 2021 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.1
// source: chromiumos/test/artifact/manifest.proto

package artifact

import (
	_go "go.chromium.org/chromiumos/config/go"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Capture the various artifact types.
// NEXT TAG: 4
type Artifact_ArtifactType int32

const (
	Artifact_ARTIFACT_TYPE_UNSPECIFIED Artifact_ArtifactType = 0
	Artifact_TEST_RESULT               Artifact_ArtifactType = 1
	Artifact_DUT_METADATA              Artifact_ArtifactType = 2
	Artifact_TEST_PLAN                 Artifact_ArtifactType = 3
)

// Enum value maps for Artifact_ArtifactType.
var (
	Artifact_ArtifactType_name = map[int32]string{
		0: "ARTIFACT_TYPE_UNSPECIFIED",
		1: "TEST_RESULT",
		2: "DUT_METADATA",
		3: "TEST_PLAN",
	}
	Artifact_ArtifactType_value = map[string]int32{
		"ARTIFACT_TYPE_UNSPECIFIED": 0,
		"TEST_RESULT":               1,
		"DUT_METADATA":              2,
		"TEST_PLAN":                 3,
	}
)

func (x Artifact_ArtifactType) Enum() *Artifact_ArtifactType {
	p := new(Artifact_ArtifactType)
	*p = x
	return p
}

func (x Artifact_ArtifactType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Artifact_ArtifactType) Descriptor() protoreflect.EnumDescriptor {
	return file_chromiumos_test_artifact_manifest_proto_enumTypes[0].Descriptor()
}

func (Artifact_ArtifactType) Type() protoreflect.EnumType {
	return &file_chromiumos_test_artifact_manifest_proto_enumTypes[0]
}

func (x Artifact_ArtifactType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Artifact_ArtifactType.Descriptor instead.
func (Artifact_ArtifactType) EnumDescriptor() ([]byte, []int) {
	return file_chromiumos_test_artifact_manifest_proto_rawDescGZIP(), []int{1, 0}
}

// Manifest for test result artifacts.
// NEXT TAG: 3
type Manifest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Captures the manifest version.
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// List of associated test result artifacts.
	Artifacts []*Artifact `protobuf:"bytes,2,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_artifact_manifest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_artifact_manifest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_artifact_manifest_proto_rawDescGZIP(), []int{0}
}

func (x *Manifest) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Manifest) GetArtifacts() []*Artifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

// Artifact information.
// NEXT TAG: 3
type Artifact struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Type of the artifact.
	Type Artifact_ArtifactType `protobuf:"varint,1,opt,name=type,proto3,enum=chromiumos.test.artifact.Artifact_ArtifactType" json:"type,omitempty"`
	// Path containing the artifact (usually points to the artifact GCS URL).
	StoragePath *_go.StoragePath `protobuf:"bytes,2,opt,name=storage_path,json=storagePath,proto3" json:"storage_path,omitempty"`
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_artifact_manifest_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_artifact_manifest_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_artifact_manifest_proto_rawDescGZIP(), []int{1}
}

func (x *Artifact) GetType() Artifact_ArtifactType {
	if x != nil {
		return x.Type
	}
	return Artifact_ARTIFACT_TYPE_UNSPECIFIED
}

func (x *Artifact) GetStoragePath() *_go.StoragePath {
	if x != nil {
		return x.StoragePath
	}
	return nil
}

var File_chromiumos_test_artifact_manifest_proto protoreflect.FileDescriptor

var file_chromiumos_test_artifact_manifest_proto_rawDesc = []byte{
	0x0a, 0x27, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2f, 0x74, 0x65, 0x73,
	0x74, 0x2f, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x2f, 0x6d, 0x61, 0x6e, 0x69, 0x66,
	0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x63, 0x68, 0x72, 0x6f, 0x6d,
	0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x66,
	0x61, 0x63, 0x74, 0x1a, 0x1d, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2f,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x66, 0x0a, 0x08, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x40, 0x0a, 0x09, 0x61, 0x72, 0x74, 0x69,
	0x66, 0x61, 0x63, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x63, 0x68,
	0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x72,
	0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x52,
	0x09, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x22, 0xec, 0x01, 0x0a, 0x08, 0x41,
	0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x12, 0x43, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2f, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d,
	0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74,
	0x2e, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61,
	0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x3a, 0x0a, 0x0c,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e,
	0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x50, 0x61, 0x74, 0x68, 0x52, 0x0b, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x50, 0x61, 0x74, 0x68, 0x22, 0x5f, 0x0a, 0x0c, 0x41, 0x72, 0x74, 0x69,
	0x66, 0x61, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x19, 0x41, 0x52, 0x54, 0x49,
	0x46, 0x41, 0x43, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x45, 0x53, 0x54, 0x5f,
	0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x44, 0x55, 0x54, 0x5f,
	0x4d, 0x45, 0x54, 0x41, 0x44, 0x41, 0x54, 0x41, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x45,
	0x53, 0x54, 0x5f, 0x50, 0x4c, 0x41, 0x4e, 0x10, 0x03, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x6f, 0x2e,
	0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x63, 0x68, 0x72,
	0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x67,
	0x6f, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chromiumos_test_artifact_manifest_proto_rawDescOnce sync.Once
	file_chromiumos_test_artifact_manifest_proto_rawDescData = file_chromiumos_test_artifact_manifest_proto_rawDesc
)

func file_chromiumos_test_artifact_manifest_proto_rawDescGZIP() []byte {
	file_chromiumos_test_artifact_manifest_proto_rawDescOnce.Do(func() {
		file_chromiumos_test_artifact_manifest_proto_rawDescData = protoimpl.X.CompressGZIP(file_chromiumos_test_artifact_manifest_proto_rawDescData)
	})
	return file_chromiumos_test_artifact_manifest_proto_rawDescData
}

var file_chromiumos_test_artifact_manifest_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chromiumos_test_artifact_manifest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chromiumos_test_artifact_manifest_proto_goTypes = []interface{}{
	(Artifact_ArtifactType)(0), // 0: chromiumos.test.artifact.Artifact.ArtifactType
	(*Manifest)(nil),           // 1: chromiumos.test.artifact.Manifest
	(*Artifact)(nil),           // 2: chromiumos.test.artifact.Artifact
	(*_go.StoragePath)(nil),    // 3: chromiumos.StoragePath
}
var file_chromiumos_test_artifact_manifest_proto_depIdxs = []int32{
	2, // 0: chromiumos.test.artifact.Manifest.artifacts:type_name -> chromiumos.test.artifact.Artifact
	0, // 1: chromiumos.test.artifact.Artifact.type:type_name -> chromiumos.test.artifact.Artifact.ArtifactType
	3, // 2: chromiumos.test.artifact.Artifact.storage_path:type_name -> chromiumos.StoragePath
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_chromiumos_test_artifact_manifest_proto_init() }
func file_chromiumos_test_artifact_manifest_proto_init() {
	if File_chromiumos_test_artifact_manifest_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chromiumos_test_artifact_manifest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Manifest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_artifact_manifest_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Artifact); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chromiumos_test_artifact_manifest_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chromiumos_test_artifact_manifest_proto_goTypes,
		DependencyIndexes: file_chromiumos_test_artifact_manifest_proto_depIdxs,
		EnumInfos:         file_chromiumos_test_artifact_manifest_proto_enumTypes,
		MessageInfos:      file_chromiumos_test_artifact_manifest_proto_msgTypes,
	}.Build()
	File_chromiumos_test_artifact_manifest_proto = out.File
	file_chromiumos_test_artifact_manifest_proto_rawDesc = nil
	file_chromiumos_test_artifact_manifest_proto_goTypes = nil
	file_chromiumos_test_artifact_manifest_proto_depIdxs = nil
}
