# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/test/lab/api/rpm.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromiumos.test.lab.api import ip_endpoint_pb2 as chromiumos_dot_test_dot_lab_dot_api_dot_ip__endpoint__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='chromiumos/test/lab/api/rpm.proto',
  package='chromiumos.test.lab.api',
  syntax='proto3',
  serialized_options=b'Z1go.chromium.org/chromiumos/config/go/test/lab/api',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!chromiumos/test/lab/api/rpm.proto\x12\x17\x63hromiumos.test.lab.api\x1a)chromiumos/test/lab/api/ip_endpoint.proto\"\x9f\x02\n\x03RPM\x12\x0f\n\x07present\x18\x01 \x01(\x08\x12=\n\x10\x66rontend_address\x18\x02 \x01(\x0b\x32#.chromiumos.test.lab.api.IpEndpoint\x12@\n\x13power_unit_hostname\x18\x03 \x01(\x0b\x32#.chromiumos.test.lab.api.IpEndpoint\x12\x19\n\x11power_unit_outlet\x18\x04 \x01(\t\x12;\n\x0ehydra_hostname\x18\x05 \x01(\x0b\x32#.chromiumos.test.lab.api.IpEndpoint\x12.\n\x04type\x18\x06 \x01(\x0e\x32 .chromiumos.test.lab.api.RPMType*[\n\x07RPMType\x12\x14\n\x10RPM_TYPE_UNKNOWN\x10\x00\x12\x13\n\x0fRPM_TYPE_SENTRY\x10\x01\x12\x13\n\x0fRPM_TYPE_IP9850\x10\x02\x12\x10\n\x0cRPM_TYPE_CPI\x10\x03\x42\x33Z1go.chromium.org/chromiumos/config/go/test/lab/apib\x06proto3'
  ,
  dependencies=[chromiumos_dot_test_dot_lab_dot_api_dot_ip__endpoint__pb2.DESCRIPTOR,])

_RPMTYPE = _descriptor.EnumDescriptor(
  name='RPMType',
  full_name='chromiumos.test.lab.api.RPMType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RPM_TYPE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RPM_TYPE_SENTRY', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RPM_TYPE_IP9850', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RPM_TYPE_CPI', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=395,
  serialized_end=486,
)
_sym_db.RegisterEnumDescriptor(_RPMTYPE)

RPMType = enum_type_wrapper.EnumTypeWrapper(_RPMTYPE)
RPM_TYPE_UNKNOWN = 0
RPM_TYPE_SENTRY = 1
RPM_TYPE_IP9850 = 2
RPM_TYPE_CPI = 3



_RPM = _descriptor.Descriptor(
  name='RPM',
  full_name='chromiumos.test.lab.api.RPM',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='present', full_name='chromiumos.test.lab.api.RPM.present', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frontend_address', full_name='chromiumos.test.lab.api.RPM.frontend_address', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='power_unit_hostname', full_name='chromiumos.test.lab.api.RPM.power_unit_hostname', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='power_unit_outlet', full_name='chromiumos.test.lab.api.RPM.power_unit_outlet', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hydra_hostname', full_name='chromiumos.test.lab.api.RPM.hydra_hostname', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='chromiumos.test.lab.api.RPM.type', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=393,
)

_RPM.fields_by_name['frontend_address'].message_type = chromiumos_dot_test_dot_lab_dot_api_dot_ip__endpoint__pb2._IPENDPOINT
_RPM.fields_by_name['power_unit_hostname'].message_type = chromiumos_dot_test_dot_lab_dot_api_dot_ip__endpoint__pb2._IPENDPOINT
_RPM.fields_by_name['hydra_hostname'].message_type = chromiumos_dot_test_dot_lab_dot_api_dot_ip__endpoint__pb2._IPENDPOINT
_RPM.fields_by_name['type'].enum_type = _RPMTYPE
DESCRIPTOR.message_types_by_name['RPM'] = _RPM
DESCRIPTOR.enum_types_by_name['RPMType'] = _RPMTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RPM = _reflection.GeneratedProtocolMessageType('RPM', (_message.Message,), {
  'DESCRIPTOR' : _RPM,
  '__module__' : 'chromiumos.test.lab.api.rpm_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.lab.api.RPM)
  })
_sym_db.RegisterMessage(RPM)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
