[package]
name = "mcu_common"
version = "0.1.0"
authors = ["Google"]
edition = "2021"
description = "Definitions shared between stage0 and stage1"
license = "BSD-3-Clause"

[dependencies]
bitflags = "1.3.2"
hmac-sha256 = "0.1.6"
hm01b0 = { path = "../hm01b0" }
num_enum = { version = "0.5.1", default-features = false }
i2c_peripheral = { path = "../i2c_peripheral" }

[features]
dev = []
std = []
image-transfer = []
