#!/bin/bash
# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -e
old_pwd="${PWD}"
cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
exec tools/bazel run --run_under="cd '${old_pwd}' && " //cmd/fflash -- "$@"
