// Copyright 2025 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
syntax = "proto3";
package diagnoseme;
import "google/protobuf/empty.proto";
service ServodRpcService {
  rpc start_servod(StartServodRequest) returns (StartServodResponse) {}
  rpc stop_servod(google.protobuf.Empty) returns (google.protobuf.Empty) {}
  rpc get_dut_hardware_id(GetHardwareIDRequest) returns (GetHardwareIDResponse) {}
  rpc run_dut_control(RunDutControlRequest) returns (RunDutControlResponse) {}
}

message StartServodRequest {
  string board = 1;
  optional string model = 2;
  optional string serial = 3;
  bool recovery = 4;
  bool noboard = 5;
}

message StartServodResponse {
  string console_output = 1;
  bool started = 2;
}

message GetHardwareIDRequest {
  string board = 1;
}

message GetHardwareIDResponse {
  string hwid = 1;
  string console_output = 2;
  int32 error_code = 3;
}

message RunDutControlRequest {
  string command = 1;
}

message RunDutControlResponse {
  string result = 1;
  int32 error_code = 2;
}
