# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

FROM us-docker.pkg.dev/cros-registry/base-images/ubuntu:ubuntuProd
COPY cros-hpt /usr/bin/cros-hpt