// Copyright 2022 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package chromiumos.test.api;

option go_package = "go.chromium.org/chromiumos/config/go/test/api";

message AutotestExecutionMetadata {
  message Arg {
    // The name of the autotest argument
    string flag = 1;
    // The value of the autotest argument
    string value = 2;
  }
  // Custom arguments passed into the autotest test harness
  // HARNESS SPECIFIC ARGS TO BE DEPRECATED IN FAVOR OF GENERIC ARGS.
  repeated Arg args = 1 [deprecated = true];
  // A custom sub directory to which test results will be written. In
  // particular, this path will be appended to the results directory
  // path specified on cros-test server startup to determine the final
  // path where results will live
  string results_sub_dir = 2;
}

// Arg defines a structure for general name/value pair for arguments.
message Arg {
  // The name of the argument.
  string flag = 1;
  // The value of the argument.
  string value = 2;
}

// HARNESS SPECIFIC ARGS TO BE DEPRECATED IN FAVOR OF GENERIC ARGS.
message TastExecutionMetadata {
  option deprecated = true;
  // Custom arguments passed into the Tast.
  repeated Arg args = 1;
}

// This is what will be populated from CTP into testrunner args provided
// on the CTP input request.
message ExecutionMetadata {
  // Custom arguments passed to the drivers. Drivers responsibility to handle.
  repeated Arg args = 1;
}
