#!/usr/bin/env bash
# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# A script to help developers checkout overlays and build packages so that they
# can emerge and deploy packages to the DUT.
# 1. (optional) Flash the DUT to the latest build
# 2a. (Googlers only) repo sync the whole CrOS source tree to the same manifest
#     as the DUT
# 2b. repo sync the whole CrOS source tree to ToT and then perform 2c
# 2c. Checkout to the same chromiumos-overlay commit as the DUT
# 3. Build all dependencies for the specific packages
#
# After these, emerge and deploy shall work smoothly.

DUT=
BOARD=
CROS_ROOT=`dirname "$0"`/../../../.. || return
PACKAGES=()
USE="floss_upstream -cros-debug"
FLASH=1
SYNC="--sync-with-manifest"
JOBS=$((`nproc`/2))

function usage {
  cat <<EOF

Usage: prepare_for_emerge --dut <DUT>
           [--board <BOARD>] [--packages <PACKAGES>] [--use <USE>]
           [--cros-root <CROS_ROOT>] [--no-flash]
           [--sync-with-manifest|--sync-and-checkout|--checkout-only]
Usage: prepare_for_emerge --help

Flash the latest canary test image onto the DUT, repo sync, and build all
dependencies for PACKAGES based on the DUT CrOS version.

Required flags:
  --dut         A ssh-able target for the DUT. E.g.: 192.168.0.35,
                ssh://localhost:3535, chromeos35-row35-rack3-host5.cros

Optional flags:
  --board       The board name such as brask, brya-arc-t, strongbad-kernelnext
                (Default: Query from the DUT)
  --packages    Comma-separated packages list to build. Basically you should
                list all workon-ed packages here. Build all packges if an empty
                list is passed. (Default: Query from the workon list)
  --use         The USE flags for \`cros build-packages\`.
                (Default: "floss_upstream -cros-debug")
  --cros-root   The CrOS root path. (Default: Auto-detected from script path)
  --jobs        Number of jobs to run in parallel. This is passed to the
                \`repo sync\` and the \`cros build-packages\` commands.
                (Default: Half of the output of \`nproc\` command)
  --sync-with-manifest, --sync-and-checkout, --checkout-only
                Decide how to sync the source tree based on the build currently
                installed on the DUT.
                --sync-with-manifest (Googlers only): Downloads the build's
                manifest and use it to sync. This guarantees to have exactly the
                same source trees used to build the image installed on the DUT.
                --sync-and-checkout: The previous default behavior. Sync the
                source tree to the ToT and makes sure the same commit of the
                chromiumos-overlay on the build. Since it's not the only overlay
                plus some packages are not controlled by overlays, this approach
                doesn't guarantee the exactly same tree and sometimes fails.
                --checkout-only: The previous --no-sync behavior. Similar to
                --sync-and-checkout but doesn't repo sync the tree.
                (Default: --sync-with-manifest)
  --no-clean    Do not \`cros clean\` the SDK. (Deprecated, no-op)
  --no-flash    Do not \`cros flash\` the DUT. (Default: Flash)
  --help        Print this.
EOF
}

function err {
  echo "$(date +'%Y-%m-%dT%H:%M:%S%z') ERROR prepare_for_emerge: $*" >&2
}

function log {
  echo "$(date +'%Y-%m-%dT%H:%M:%S%z') prepare_for_emerge: $*"
}

#######################################
# Get the lsb info from the DUT.
# Globals (read-only):
#   DUT
# Arguments:
#   The key to query, e.g. CHROMEOS_RELEASE_VERSION
# Outputs:
#   STDOUT: The value of the lsb field.
#######################################
function get_dut_lsb {
  local ret
  ret=`ssh ${DUT} -- "grep -m 1 '^${1}=' /etc/lsb-release"`
  printf %s "${ret#${1}=}"
}

#######################################
# Checkout chromiumos-overlay to the same point as the DUT's image.
# Globals (read-only):
#   DUT
#   CROS_ROOT
# Arguments:
#   None
# Returns:
#   0 on succeeded, 1 on any error
#######################################
function checkout_overlay {
  local dut_ver
  dut_ver=`get_dut_lsb "CHROMEOS_RELEASE_VERSION"`
  if ! [[ "${dut_ver}" =~ ^[0-9]+\.0\.0$ ]]; then
    err "Invalid CHROMEOS_RELEASE_VERSION: ${dut_ver}"
    return 1
  fi
  log "Got DUT version=${dut_ver}, checking out overlay"
  dut_ver="${dut_ver%.0.0}"

  local sdk_ver git_path="${CROS_ROOT}"/src/third_party/chromiumos-overlay
  git -C "${git_path}" checkout m/main
  sdk_ver=`grep -m 1 '^CHROMEOS_BUILD=' \
    "${git_path}"/chromeos/config/chromeos_version.sh`
  sdk_ver="${sdk_ver#CHROMEOS_BUILD=}"
  if ! [[ "${sdk_ver}" =~ ^[0-9]+$ ]]; then
    err "Invalid version in overlay: ${sdk_ver}"
    return 1
  fi

  if (( sdk_ver < dut_ver )); then
    err "SDK out of sync"
    return 1
  fi

  local commit_hash
  commit_hash=`git -C "${git_path}" log -1 --format=format:%H \
    --grep='^Increment to version R[0-9]\+-'"${dut_ver}"'\.0\.0$' \
    "${git_path}"/chromeos/config/chromeos_version.sh`
  git -C "${git_path}" checkout "${commit_hash}"
}

#######################################
# Process arguments and update globals.
# Globals:
#   DUT
#   BOARD
#   CROS_ROOT
#   PACKAGES
#   USE
#   JOBS
#   FLASH
#   SYNC
# Arguments:
#   See usage
# Returns:
#   0 on succeeded, 1 on any error
#######################################
function process_args {
  local IFS
  while [[ $# -gt 0 ]]; do
    case "$1" in
    --dut)
      DUT="$2"
      shift
      ;;
    --board)
      BOARD="$2"
      shift
      ;;
    --use)
      USE="$2"
      shift
      ;;
    --help)
      usage
      exit
      ;;
    --packages)
      IFS=, PACKAGES=($2)
      shift
      ;;
    --cros-root)
      CROS_ROOT="$2"
      shift
      ;;
    --jobs)
      JOBS="$2"
      shift
      ;;
    --no-clean)
      err "Flag --no-clean is deprecated and is no-op now."
      ;;
    --no-flash)
      FLASH=0
      ;;
    --sync-with-manifest|--sync-and-checkout|--checkout-only)
      SYNC="$1"
      ;;
    *)
      err "Unknow argument: $1"
      usage
      return 1
      ;;
    esac
    shift
  done

  if [[ -z "${DUT}" ]]; then
    err "Unspecified DUT"
    usage
    return 1
  fi

  CROS_ROOT=`realpath "${CROS_ROOT}"`
  cd "${CROS_ROOT}"

  if [[ -z "${BOARD}" ]]; then
    BOARD=`get_dut_lsb "CHROMEOS_RELEASE_BOARD"`
  fi

  if [[ "${#PACKAGES[@]}" == 0 ]]; then
    IFS=$' \t\n' PACKAGES=(
      `"${CROS_ROOT}"/chromite/bin/cros workon --board "${BOARD}" list`
    )
    if [[ "${#PACKAGES[@]}" == 0 ]]; then
      read -p "No workon-ed packages! Build all packages? [N/y] "
      case "${REPLY}" in
        y*|Y*)
          ;;
        *)
          return 1
          ;;
      esac
    fi
  fi

  IFS=' '
  log "Running with flags:
    DUT=${DUT}
    BOARD=${BOARD}
    CROS_ROOT=${CROS_ROOT}
    PACKAGES=${PACKAGES[@]}
    USE=${USE}
    JOBS=${JOBS}
    FLASH=${FLASH}
    SYNC=${SYNC}"
}

function main {
  set -e

  process_args "$@"

  if [[ ${FLASH} == 1 ]]; then
    log "Flashing..."
    "${CROS_ROOT}"/chromite/bin/cros flash --no-ping \
      --disable-rootfs-verification \
      "${DUT}" "xbuddy://remote/${BOARD}/latest-canary/test"
  fi
  case "${SYNC}" in
    --sync-with-manifest)
      log "Running repo sync with manifest..."
      local dut_m dut_ver tmp_manifest_path
      dut_m=`get_dut_lsb "CHROMEOS_RELEASE_CHROME_MILESTONE"`
      dut_ver=`get_dut_lsb "CHROMEOS_RELEASE_VERSION"`
      tmp_manifest_path=`mktemp --tmpdir prepare_for_emerge-manifest.XXXXXX.xml`
      # trap the cleanup because set -e could terminate the program at anytime.
      trap "rm ${tmp_manifest_path@Q}" EXIT
      gsutil cp \
        "gs://chromeos-manifest-versions/buildspecs/${dut_m}/${dut_ver}.xml" \
        "${tmp_manifest_path}"
      repo sync --jobs="${JOBS}" -m "${tmp_manifest_path}"
      ;;
    --sync-and-checkout)
      log "Running repo sync..."
      repo sync --jobs="${JOBS}"
      checkout_overlay
      ;;
    --checkout-only)
      checkout_overlay
      ;;
    *)
      err "Unknow sync flag: ${SYNC}"
      return 1
      ;;
  esac
  log "Building dependencies..."
  USE="${USE}" "${CROS_ROOT}"/chromite/bin/cros build-packages --cleanbuild \
    --skip-setup-board --board="${BOARD}" --jobs="${JOBS}" "${PACKAGES[@]}"
}

main "$@"
