# Copyright 2019 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

group("all") {
  deps = [
    "//platform_camera/hal/mediatek/mtkcam/3rdparty:libmtkcam_3rdparty",
    "//platform_camera/hal/mediatek/mtkcam/app:libcam3_app",
    "//platform_camera/hal/mediatek/mtkcam/custom:libcameracustom",
    "//platform_camera/hal/mediatek/mtkcam/drv/fdvt/4.0:libmtkcam_fdvt",
    "//platform_camera/hal/mediatek/mtkcam/drv/iopipe/src/pass1:libcam_normalpipe",
    "//platform_camera/hal/mediatek/mtkcam/drv/iopipe/src/pass2:libcam_normalstream",
    "//platform_camera/hal/mediatek/mtkcam/drv/sensor:libmtk_halsensor",
    "//platform_camera/hal/mediatek/mtkcam/feature/common/3dnr:libfeature_3dnr",
    "//platform_camera/hal/mediatek/mtkcam/feature/common/faceeffect:libfeature.face",
    "//platform_camera/hal/mediatek/mtkcam/feature/common/lmv:libfeature_lmv",
    "//platform_camera/hal/mediatek/mtkcam/feature/common/utils:libcam.feature_utils",
    "//platform_camera/hal/mediatek/mtkcam/feature/featureCore/featurePipe/capture:libmtkcam.featurepipe.capture",
    "//platform_camera/hal/mediatek/mtkcam/feature/featureCore/featurePipe/streaming:libmtkcam.featurepipe.streaming",
    "//platform_camera/hal/mediatek/mtkcam/feature/featureCore/featurePipe/util:libmtkcam.featurepipe.util",
    "//platform_camera/hal/mediatek/mtkcam/ipc/client:libcam_algo_client",
    "//platform_camera/hal/mediatek/mtkcam/ipc/server:libcam_algo",
    "//platform_camera/hal/mediatek/mtkcam/main/common/module/aaa:libmtkcam_modulefactory_aaa",
    "//platform_camera/hal/mediatek/mtkcam/main/common/module/custom:libmtkcam_modulefactory_custom",
    "//platform_camera/hal/mediatek/mtkcam/main/common/module/drv:libmtkcam_modulefactory_drv",
    "//platform_camera/hal/mediatek/mtkcam/main/common/module/utils:libmtkcam_modulefactory_utils",
    "//platform_camera/hal/mediatek/mtkcam/main/hal/device3:libcam.device3",
    "//platform_camera/hal/mediatek/mtkcam/main/hal/module:libcamera.mt8183",
    "//platform_camera/hal/mediatek/mtkcam/pipeline/hwnode:libmtkcam_hwnode",
    "//platform_camera/hal/mediatek/mtkcam/pipeline/model:libmtkcam_pipelinemodel",
    "//platform_camera/hal/mediatek/mtkcam/pipeline/model/utils:libmtkcam_pipelinemodel_utils",
    "//platform_camera/hal/mediatek/mtkcam/pipeline/pipeline:libmtkcam_pipeline",
    "//platform_camera/hal/mediatek/mtkcam/pipeline/policy:libmtkcam_pipelinepolicy",
    "//platform_camera/hal/mediatek/mtkcam/pipeline/utils:libmtkcam_streamutils",
    "//platform_camera/hal/mediatek/mtkcam/utils/LogicalCam:libmtkcam.logicalmodule",
    "//platform_camera/hal/mediatek/mtkcam/utils/debug:libmtkcam_debugutils",
    "//platform_camera/hal/mediatek/mtkcam/utils/eeprom:eeprom_updater",
    "//platform_camera/hal/mediatek/mtkcam/utils/exif:libmtkcam_exif",
    "//platform_camera/hal/mediatek/mtkcam/utils/gralloc:libmtkcam_grallocutils",
    "//platform_camera/hal/mediatek/mtkcam/utils/hw:libmtkcam_hwutils",
    "//platform_camera/hal/mediatek/mtkcam/utils/imgbuf:libmtkcam_imgbuf",
    "//platform_camera/hal/mediatek/mtkcam/utils/log_service:libmtk_platform_log",
    "//platform_camera/hal/mediatek/mtkcam/utils/metadata:libmtkcam_metadata",
    "//platform_camera/hal/mediatek/mtkcam/utils/metastore:libmtkcam_metastore",
    "//platform_camera/hal/mediatek/mtkcam/utils/property_service:getprop",
    "//platform_camera/hal/mediatek/mtkcam/utils/property_service:libmtk_property",
    "//platform_camera/hal/mediatek/mtkcam/utils/property_service:setprop",
    "//platform_camera/hal/mediatek/mtkcam/utils/std:libmtkcam_stdutils",
    "//platform_camera/hal/mediatek/mtkcam/v4l2:libmtkcam_v4l2drvmgr",
    "//platform_camera/hal/mediatek/mtklibv4l2:libmtk_mc_libv4l2",
  ]
}
