// Copyright 2021 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.1
// source: chromiumos/test/api/test_harness.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Defines a test execution framework that can execute test cases and report
// results.
// LINT.IfChange
type TestHarness struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Globally unique (for ChromeOS) identifier of a given test harness
	//
	// Types that are assignable to TestHarnessType:
	//	*TestHarness_Manual_
	//	*TestHarness_Tauto_
	//	*TestHarness_Tast_
	//	*TestHarness_Gtest_
	//	*TestHarness_Mobly_
	//	*TestHarness_Crosier_
	//	*TestHarness_Tradefed_
	//	*TestHarness_Dtc
	TestHarnessType isTestHarness_TestHarnessType `protobuf_oneof:"test_harness_type"`
}

func (x *TestHarness) Reset() {
	*x = TestHarness{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_test_harness_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestHarness) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestHarness) ProtoMessage() {}

func (x *TestHarness) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_test_harness_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestHarness.ProtoReflect.Descriptor instead.
func (*TestHarness) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_test_harness_proto_rawDescGZIP(), []int{0}
}

func (m *TestHarness) GetTestHarnessType() isTestHarness_TestHarnessType {
	if m != nil {
		return m.TestHarnessType
	}
	return nil
}

func (x *TestHarness) GetManual() *TestHarness_Manual {
	if x, ok := x.GetTestHarnessType().(*TestHarness_Manual_); ok {
		return x.Manual
	}
	return nil
}

func (x *TestHarness) GetTauto() *TestHarness_Tauto {
	if x, ok := x.GetTestHarnessType().(*TestHarness_Tauto_); ok {
		return x.Tauto
	}
	return nil
}

func (x *TestHarness) GetTast() *TestHarness_Tast {
	if x, ok := x.GetTestHarnessType().(*TestHarness_Tast_); ok {
		return x.Tast
	}
	return nil
}

func (x *TestHarness) GetGtest() *TestHarness_Gtest {
	if x, ok := x.GetTestHarnessType().(*TestHarness_Gtest_); ok {
		return x.Gtest
	}
	return nil
}

func (x *TestHarness) GetMobly() *TestHarness_Mobly {
	if x, ok := x.GetTestHarnessType().(*TestHarness_Mobly_); ok {
		return x.Mobly
	}
	return nil
}

func (x *TestHarness) GetCrosier() *TestHarness_Crosier {
	if x, ok := x.GetTestHarnessType().(*TestHarness_Crosier_); ok {
		return x.Crosier
	}
	return nil
}

func (x *TestHarness) GetTradefed() *TestHarness_Tradefed {
	if x, ok := x.GetTestHarnessType().(*TestHarness_Tradefed_); ok {
		return x.Tradefed
	}
	return nil
}

func (x *TestHarness) GetDtc() *TestHarness_DTC {
	if x, ok := x.GetTestHarnessType().(*TestHarness_Dtc); ok {
		return x.Dtc
	}
	return nil
}

type isTestHarness_TestHarnessType interface {
	isTestHarness_TestHarnessType()
}

type TestHarness_Manual_ struct {
	Manual *TestHarness_Manual `protobuf:"bytes,1,opt,name=manual,proto3,oneof"`
}

type TestHarness_Tauto_ struct {
	Tauto *TestHarness_Tauto `protobuf:"bytes,2,opt,name=tauto,proto3,oneof"`
}

type TestHarness_Tast_ struct {
	Tast *TestHarness_Tast `protobuf:"bytes,3,opt,name=tast,proto3,oneof"`
}

type TestHarness_Gtest_ struct {
	Gtest *TestHarness_Gtest `protobuf:"bytes,4,opt,name=gtest,proto3,oneof"`
}

type TestHarness_Mobly_ struct {
	Mobly *TestHarness_Mobly `protobuf:"bytes,5,opt,name=mobly,proto3,oneof"`
}

type TestHarness_Crosier_ struct {
	Crosier *TestHarness_Crosier `protobuf:"bytes,6,opt,name=crosier,proto3,oneof"`
}

type TestHarness_Tradefed_ struct {
	Tradefed *TestHarness_Tradefed `protobuf:"bytes,7,opt,name=tradefed,proto3,oneof"`
}

type TestHarness_Dtc struct {
	Dtc *TestHarness_DTC `protobuf:"bytes,8,opt,name=dtc,proto3,oneof"`
}

func (*TestHarness_Manual_) isTestHarness_TestHarnessType() {}

func (*TestHarness_Tauto_) isTestHarness_TestHarnessType() {}

func (*TestHarness_Tast_) isTestHarness_TestHarnessType() {}

func (*TestHarness_Gtest_) isTestHarness_TestHarnessType() {}

func (*TestHarness_Mobly_) isTestHarness_TestHarnessType() {}

func (*TestHarness_Crosier_) isTestHarness_TestHarnessType() {}

func (*TestHarness_Tradefed_) isTestHarness_TestHarnessType() {}

func (*TestHarness_Dtc) isTestHarness_TestHarnessType() {}

type TestHarness_Manual struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TestHarness_Manual) Reset() {
	*x = TestHarness_Manual{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_test_harness_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestHarness_Manual) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestHarness_Manual) ProtoMessage() {}

func (x *TestHarness_Manual) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_test_harness_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestHarness_Manual.ProtoReflect.Descriptor instead.
func (*TestHarness_Manual) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_test_harness_proto_rawDescGZIP(), []int{0, 0}
}

type TestHarness_Tast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TestHarness_Tast) Reset() {
	*x = TestHarness_Tast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_test_harness_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestHarness_Tast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestHarness_Tast) ProtoMessage() {}

func (x *TestHarness_Tast) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_test_harness_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestHarness_Tast.ProtoReflect.Descriptor instead.
func (*TestHarness_Tast) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_test_harness_proto_rawDescGZIP(), []int{0, 1}
}

type TestHarness_Tauto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TestHarness_Tauto) Reset() {
	*x = TestHarness_Tauto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_test_harness_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestHarness_Tauto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestHarness_Tauto) ProtoMessage() {}

func (x *TestHarness_Tauto) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_test_harness_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestHarness_Tauto.ProtoReflect.Descriptor instead.
func (*TestHarness_Tauto) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_test_harness_proto_rawDescGZIP(), []int{0, 2}
}

type TestHarness_Gtest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Location of the test binary on the DUT
	TargetBinLocation string `protobuf:"bytes,1,opt,name=target_bin_location,json=targetBinLocation,proto3" json:"target_bin_location,omitempty"`
}

func (x *TestHarness_Gtest) Reset() {
	*x = TestHarness_Gtest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_test_harness_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestHarness_Gtest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestHarness_Gtest) ProtoMessage() {}

func (x *TestHarness_Gtest) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_test_harness_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestHarness_Gtest.ProtoReflect.Descriptor instead.
func (*TestHarness_Gtest) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_test_harness_proto_rawDescGZIP(), []int{0, 3}
}

func (x *TestHarness_Gtest) GetTargetBinLocation() string {
	if x != nil {
		return x.TargetBinLocation
	}
	return ""
}

type TestHarness_Mobly struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TestHarness_Mobly) Reset() {
	*x = TestHarness_Mobly{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_test_harness_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestHarness_Mobly) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestHarness_Mobly) ProtoMessage() {}

func (x *TestHarness_Mobly) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_test_harness_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestHarness_Mobly.ProtoReflect.Descriptor instead.
func (*TestHarness_Mobly) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_test_harness_proto_rawDescGZIP(), []int{0, 4}
}

type TestHarness_Crosier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TestHarness_Crosier) Reset() {
	*x = TestHarness_Crosier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_test_harness_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestHarness_Crosier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestHarness_Crosier) ProtoMessage() {}

func (x *TestHarness_Crosier) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_test_harness_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestHarness_Crosier.ProtoReflect.Descriptor instead.
func (*TestHarness_Crosier) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_test_harness_proto_rawDescGZIP(), []int{0, 5}
}

type TestHarness_Tradefed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TestHarness_Tradefed) Reset() {
	*x = TestHarness_Tradefed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_test_harness_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestHarness_Tradefed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestHarness_Tradefed) ProtoMessage() {}

func (x *TestHarness_Tradefed) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_test_harness_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestHarness_Tradefed.ProtoReflect.Descriptor instead.
func (*TestHarness_Tradefed) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_test_harness_proto_rawDescGZIP(), []int{0, 6}
}

type TestHarness_DTC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TestHarness_DTC) Reset() {
	*x = TestHarness_DTC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_test_harness_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestHarness_DTC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestHarness_DTC) ProtoMessage() {}

func (x *TestHarness_DTC) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_test_harness_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestHarness_DTC.ProtoReflect.Descriptor instead.
func (*TestHarness_DTC) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_test_harness_proto_rawDescGZIP(), []int{0, 7}
}

var File_chromiumos_test_api_test_harness_proto protoreflect.FileDescriptor

var file_chromiumos_test_api_test_harness_proto_rawDesc = []byte{
	0x0a, 0x26, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2f, 0x74, 0x65, 0x73,
	0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x68, 0x61, 0x72, 0x6e, 0x65,
	0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69,
	0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x22, 0xa6, 0x05,
	0x0a, 0x0b, 0x54, 0x65, 0x73, 0x74, 0x48, 0x61, 0x72, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x41, 0x0a,
	0x06, 0x6d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e,
	0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x48, 0x61, 0x72, 0x6e, 0x65, 0x73, 0x73, 0x2e,
	0x4d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x48, 0x00, 0x52, 0x06, 0x6d, 0x61, 0x6e, 0x75, 0x61, 0x6c,
	0x12, 0x3e, 0x0a, 0x05, 0x74, 0x61, 0x75, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x26, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73,
	0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x48, 0x61, 0x72, 0x6e, 0x65, 0x73,
	0x73, 0x2e, 0x54, 0x61, 0x75, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x05, 0x74, 0x61, 0x75, 0x74, 0x6f,
	0x12, 0x3b, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25,
	0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x48, 0x61, 0x72, 0x6e, 0x65, 0x73, 0x73,
	0x2e, 0x54, 0x61, 0x73, 0x74, 0x48, 0x00, 0x52, 0x04, 0x74, 0x61, 0x73, 0x74, 0x12, 0x3e, 0x0a,
	0x05, 0x67, 0x74, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x63,
	0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x48, 0x61, 0x72, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x47,
	0x74, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x05, 0x67, 0x74, 0x65, 0x73, 0x74, 0x12, 0x3e, 0x0a,
	0x05, 0x6d, 0x6f, 0x62, 0x6c, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x63,
	0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x48, 0x61, 0x72, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x4d,
	0x6f, 0x62, 0x6c, 0x79, 0x48, 0x00, 0x52, 0x05, 0x6d, 0x6f, 0x62, 0x6c, 0x79, 0x12, 0x44, 0x0a,
	0x07, 0x63, 0x72, 0x6f, 0x73, 0x69, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28,
	0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x48, 0x61, 0x72, 0x6e, 0x65, 0x73, 0x73,
	0x2e, 0x43, 0x72, 0x6f, 0x73, 0x69, 0x65, 0x72, 0x48, 0x00, 0x52, 0x07, 0x63, 0x72, 0x6f, 0x73,
	0x69, 0x65, 0x72, 0x12, 0x47, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x64, 0x65, 0x66, 0x65, 0x64, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d,
	0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x65, 0x73, 0x74,
	0x48, 0x61, 0x72, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x54, 0x72, 0x61, 0x64, 0x65, 0x66, 0x65, 0x64,
	0x48, 0x00, 0x52, 0x08, 0x74, 0x72, 0x61, 0x64, 0x65, 0x66, 0x65, 0x64, 0x12, 0x38, 0x0a, 0x03,
	0x64, 0x74, 0x63, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63, 0x68, 0x72, 0x6f,
	0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x54, 0x65, 0x73, 0x74, 0x48, 0x61, 0x72, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x44, 0x54, 0x43, 0x48,
	0x00, 0x52, 0x03, 0x64, 0x74, 0x63, 0x1a, 0x08, 0x0a, 0x06, 0x4d, 0x61, 0x6e, 0x75, 0x61, 0x6c,
	0x1a, 0x06, 0x0a, 0x04, 0x54, 0x61, 0x73, 0x74, 0x1a, 0x07, 0x0a, 0x05, 0x54, 0x61, 0x75, 0x74,
	0x6f, 0x1a, 0x37, 0x0a, 0x05, 0x47, 0x74, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x13, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x5f, 0x62, 0x69, 0x6e, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x42,
	0x69, 0x6e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x07, 0x0a, 0x05, 0x4d, 0x6f,
	0x62, 0x6c, 0x79, 0x1a, 0x09, 0x0a, 0x07, 0x43, 0x72, 0x6f, 0x73, 0x69, 0x65, 0x72, 0x1a, 0x0a,
	0x0a, 0x08, 0x54, 0x72, 0x61, 0x64, 0x65, 0x66, 0x65, 0x64, 0x1a, 0x05, 0x0a, 0x03, 0x44, 0x54,
	0x43, 0x42, 0x13, 0x0a, 0x11, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x68, 0x61, 0x72, 0x6e, 0x65, 0x73,
	0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x6f, 0x2e, 0x63, 0x68, 0x72,
	0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69,
	0x75, 0x6d, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x67, 0x6f, 0x2f, 0x74,
	0x65, 0x73, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chromiumos_test_api_test_harness_proto_rawDescOnce sync.Once
	file_chromiumos_test_api_test_harness_proto_rawDescData = file_chromiumos_test_api_test_harness_proto_rawDesc
)

func file_chromiumos_test_api_test_harness_proto_rawDescGZIP() []byte {
	file_chromiumos_test_api_test_harness_proto_rawDescOnce.Do(func() {
		file_chromiumos_test_api_test_harness_proto_rawDescData = protoimpl.X.CompressGZIP(file_chromiumos_test_api_test_harness_proto_rawDescData)
	})
	return file_chromiumos_test_api_test_harness_proto_rawDescData
}

var file_chromiumos_test_api_test_harness_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_chromiumos_test_api_test_harness_proto_goTypes = []interface{}{
	(*TestHarness)(nil),          // 0: chromiumos.test.api.TestHarness
	(*TestHarness_Manual)(nil),   // 1: chromiumos.test.api.TestHarness.Manual
	(*TestHarness_Tast)(nil),     // 2: chromiumos.test.api.TestHarness.Tast
	(*TestHarness_Tauto)(nil),    // 3: chromiumos.test.api.TestHarness.Tauto
	(*TestHarness_Gtest)(nil),    // 4: chromiumos.test.api.TestHarness.Gtest
	(*TestHarness_Mobly)(nil),    // 5: chromiumos.test.api.TestHarness.Mobly
	(*TestHarness_Crosier)(nil),  // 6: chromiumos.test.api.TestHarness.Crosier
	(*TestHarness_Tradefed)(nil), // 7: chromiumos.test.api.TestHarness.Tradefed
	(*TestHarness_DTC)(nil),      // 8: chromiumos.test.api.TestHarness.DTC
}
var file_chromiumos_test_api_test_harness_proto_depIdxs = []int32{
	1, // 0: chromiumos.test.api.TestHarness.manual:type_name -> chromiumos.test.api.TestHarness.Manual
	3, // 1: chromiumos.test.api.TestHarness.tauto:type_name -> chromiumos.test.api.TestHarness.Tauto
	2, // 2: chromiumos.test.api.TestHarness.tast:type_name -> chromiumos.test.api.TestHarness.Tast
	4, // 3: chromiumos.test.api.TestHarness.gtest:type_name -> chromiumos.test.api.TestHarness.Gtest
	5, // 4: chromiumos.test.api.TestHarness.mobly:type_name -> chromiumos.test.api.TestHarness.Mobly
	6, // 5: chromiumos.test.api.TestHarness.crosier:type_name -> chromiumos.test.api.TestHarness.Crosier
	7, // 6: chromiumos.test.api.TestHarness.tradefed:type_name -> chromiumos.test.api.TestHarness.Tradefed
	8, // 7: chromiumos.test.api.TestHarness.dtc:type_name -> chromiumos.test.api.TestHarness.DTC
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_chromiumos_test_api_test_harness_proto_init() }
func file_chromiumos_test_api_test_harness_proto_init() {
	if File_chromiumos_test_api_test_harness_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chromiumos_test_api_test_harness_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestHarness); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_test_harness_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestHarness_Manual); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_test_harness_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestHarness_Tast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_test_harness_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestHarness_Tauto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_test_harness_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestHarness_Gtest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_test_harness_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestHarness_Mobly); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_test_harness_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestHarness_Crosier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_test_harness_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestHarness_Tradefed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_test_harness_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestHarness_DTC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_chromiumos_test_api_test_harness_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*TestHarness_Manual_)(nil),
		(*TestHarness_Tauto_)(nil),
		(*TestHarness_Tast_)(nil),
		(*TestHarness_Gtest_)(nil),
		(*TestHarness_Mobly_)(nil),
		(*TestHarness_Crosier_)(nil),
		(*TestHarness_Tradefed_)(nil),
		(*TestHarness_Dtc)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chromiumos_test_api_test_harness_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chromiumos_test_api_test_harness_proto_goTypes,
		DependencyIndexes: file_chromiumos_test_api_test_harness_proto_depIdxs,
		MessageInfos:      file_chromiumos_test_api_test_harness_proto_msgTypes,
	}.Build()
	File_chromiumos_test_api_test_harness_proto = out.File
	file_chromiumos_test_api_test_harness_proto_rawDesc = nil
	file_chromiumos_test_api_test_harness_proto_goTypes = nil
	file_chromiumos_test_api_test_harness_proto_depIdxs = nil
}
