// Copyright 2022 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.1
// source: chromiumos/test/api/test_libs_service.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLibFailure_Reason int32

const (
	GetLibFailure_REASON_UNKNOWN               GetLibFailure_Reason = 0
	GetLibFailure_REASON_UNREGISTERED_LIB      GetLibFailure_Reason = 1
	GetLibFailure_REASON_CONTAINER_START_ERROR GetLibFailure_Reason = 2
)

// Enum value maps for GetLibFailure_Reason.
var (
	GetLibFailure_Reason_name = map[int32]string{
		0: "REASON_UNKNOWN",
		1: "REASON_UNREGISTERED_LIB",
		2: "REASON_CONTAINER_START_ERROR",
	}
	GetLibFailure_Reason_value = map[string]int32{
		"REASON_UNKNOWN":               0,
		"REASON_UNREGISTERED_LIB":      1,
		"REASON_CONTAINER_START_ERROR": 2,
	}
)

func (x GetLibFailure_Reason) Enum() *GetLibFailure_Reason {
	p := new(GetLibFailure_Reason)
	*p = x
	return p
}

func (x GetLibFailure_Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetLibFailure_Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_chromiumos_test_api_test_libs_service_proto_enumTypes[0].Descriptor()
}

func (GetLibFailure_Reason) Type() protoreflect.EnumType {
	return &file_chromiumos_test_api_test_libs_service_proto_enumTypes[0]
}

func (x GetLibFailure_Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetLibFailure_Reason.Descriptor instead.
func (GetLibFailure_Reason) EnumDescriptor() ([]byte, []int) {
	return file_chromiumos_test_api_test_libs_service_proto_rawDescGZIP(), []int{1, 0}
}

// Get Lib messages.
type GetLibSuccess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Port string `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *GetLibSuccess) Reset() {
	*x = GetLibSuccess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_test_libs_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLibSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLibSuccess) ProtoMessage() {}

func (x *GetLibSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_test_libs_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLibSuccess.ProtoReflect.Descriptor instead.
func (*GetLibSuccess) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_test_libs_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetLibSuccess) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetLibSuccess) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

type GetLibFailure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason GetLibFailure_Reason `protobuf:"varint,1,opt,name=reason,proto3,enum=chromiumos.test.api.GetLibFailure_Reason" json:"reason,omitempty"`
}

func (x *GetLibFailure) Reset() {
	*x = GetLibFailure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_test_libs_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLibFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLibFailure) ProtoMessage() {}

func (x *GetLibFailure) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_test_libs_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLibFailure.ProtoReflect.Descriptor instead.
func (*GetLibFailure) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_test_libs_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetLibFailure) GetReason() GetLibFailure_Reason {
	if x != nil {
		return x.Reason
	}
	return GetLibFailure_REASON_UNKNOWN
}

type GetLibRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Options []string `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
}

func (x *GetLibRequest) Reset() {
	*x = GetLibRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_test_libs_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLibRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLibRequest) ProtoMessage() {}

func (x *GetLibRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_test_libs_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLibRequest.ProtoReflect.Descriptor instead.
func (*GetLibRequest) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_test_libs_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetLibRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetLibRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetLibRequest) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

type GetLibResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Outcome:
	//	*GetLibResponse_Success
	//	*GetLibResponse_Failure
	Outcome isGetLibResponse_Outcome `protobuf_oneof:"outcome"`
}

func (x *GetLibResponse) Reset() {
	*x = GetLibResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_test_libs_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLibResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLibResponse) ProtoMessage() {}

func (x *GetLibResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_test_libs_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLibResponse.ProtoReflect.Descriptor instead.
func (*GetLibResponse) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_test_libs_service_proto_rawDescGZIP(), []int{3}
}

func (m *GetLibResponse) GetOutcome() isGetLibResponse_Outcome {
	if m != nil {
		return m.Outcome
	}
	return nil
}

func (x *GetLibResponse) GetSuccess() *GetLibSuccess {
	if x, ok := x.GetOutcome().(*GetLibResponse_Success); ok {
		return x.Success
	}
	return nil
}

func (x *GetLibResponse) GetFailure() *GetLibFailure {
	if x, ok := x.GetOutcome().(*GetLibResponse_Failure); ok {
		return x.Failure
	}
	return nil
}

type isGetLibResponse_Outcome interface {
	isGetLibResponse_Outcome()
}

type GetLibResponse_Success struct {
	Success *GetLibSuccess `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type GetLibResponse_Failure struct {
	Failure *GetLibFailure `protobuf:"bytes,2,opt,name=failure,proto3,oneof"`
}

func (*GetLibResponse_Success) isGetLibResponse_Outcome() {}

func (*GetLibResponse_Failure) isGetLibResponse_Outcome() {}

// Kill Lib messages.
type KillLibRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Options string `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *KillLibRequest) Reset() {
	*x = KillLibRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_test_libs_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KillLibRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillLibRequest) ProtoMessage() {}

func (x *KillLibRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_test_libs_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillLibRequest.ProtoReflect.Descriptor instead.
func (*KillLibRequest) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_test_libs_service_proto_rawDescGZIP(), []int{4}
}

func (x *KillLibRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KillLibRequest) GetOptions() string {
	if x != nil {
		return x.Options
	}
	return ""
}

type KillLibResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KillLibResponse) Reset() {
	*x = KillLibResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_test_libs_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KillLibResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillLibResponse) ProtoMessage() {}

func (x *KillLibResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_test_libs_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillLibResponse.ProtoReflect.Descriptor instead.
func (*KillLibResponse) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_test_libs_service_proto_rawDescGZIP(), []int{5}
}

var File_chromiumos_test_api_test_libs_service_proto protoreflect.FileDescriptor

var file_chromiumos_test_api_test_libs_service_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2f, 0x74, 0x65, 0x73,
	0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x6c, 0x69, 0x62, 0x73, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x63,
	0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61,
	0x70, 0x69, 0x22, 0x33, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x62, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0xaf, 0x01, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4c,
	0x69, 0x62, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x12, 0x41, 0x0a, 0x06, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x63, 0x68, 0x72, 0x6f,
	0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x47, 0x65, 0x74, 0x4c, 0x69, 0x62, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x2e, 0x52, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x5b, 0x0a, 0x06,
	0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x45, 0x41, 0x53, 0x4f, 0x4e,
	0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x1b, 0x0a, 0x17, 0x52, 0x45,
	0x41, 0x53, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x45, 0x52, 0x45,
	0x44, 0x5f, 0x4c, 0x49, 0x42, 0x10, 0x01, 0x12, 0x20, 0x0a, 0x1c, 0x52, 0x45, 0x41, 0x53, 0x4f,
	0x4e, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x41, 0x49, 0x4e, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x52,
	0x54, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x22, 0x57, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x4c, 0x69, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x22, 0x9b, 0x01, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x62, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75,
	0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74,
	0x4c, 0x69, 0x62, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x48, 0x00, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x3e, 0x0a, 0x07, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75,
	0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74,
	0x4c, 0x69, 0x62, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x48, 0x00, 0x52, 0x07, 0x66, 0x61,
	0x69, 0x6c, 0x75, 0x72, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x6f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65,
	0x22, 0x3a, 0x0a, 0x0e, 0x4b, 0x69, 0x6c, 0x6c, 0x4c, 0x69, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x11, 0x0a, 0x0f,
	0x4b, 0x69, 0x6c, 0x6c, 0x4c, 0x69, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32,
	0x90, 0x02, 0x0a, 0x0f, 0x54, 0x65, 0x73, 0x74, 0x4c, 0x69, 0x62, 0x73, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x53, 0x0a, 0x08, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x69, 0x62, 0x12,
	0x22, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73,
	0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x62, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73,
	0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x62,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x07, 0x46, 0x69, 0x6e, 0x64,
	0x4c, 0x69, 0x62, 0x12, 0x22, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73,
	0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x62,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69,
	0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65,
	0x74, 0x4c, 0x69, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x54, 0x0a, 0x07,
	0x4b, 0x69, 0x6c, 0x6c, 0x4c, 0x69, 0x62, 0x12, 0x23, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69,
	0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4b, 0x69,
	0x6c, 0x6c, 0x4c, 0x69, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x63,
	0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x4b, 0x69, 0x6c, 0x6c, 0x4c, 0x69, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x6f, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75,
	0x6d, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73,
	0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x67, 0x6f, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2f,
	0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chromiumos_test_api_test_libs_service_proto_rawDescOnce sync.Once
	file_chromiumos_test_api_test_libs_service_proto_rawDescData = file_chromiumos_test_api_test_libs_service_proto_rawDesc
)

func file_chromiumos_test_api_test_libs_service_proto_rawDescGZIP() []byte {
	file_chromiumos_test_api_test_libs_service_proto_rawDescOnce.Do(func() {
		file_chromiumos_test_api_test_libs_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_chromiumos_test_api_test_libs_service_proto_rawDescData)
	})
	return file_chromiumos_test_api_test_libs_service_proto_rawDescData
}

var file_chromiumos_test_api_test_libs_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chromiumos_test_api_test_libs_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_chromiumos_test_api_test_libs_service_proto_goTypes = []interface{}{
	(GetLibFailure_Reason)(0), // 0: chromiumos.test.api.GetLibFailure.Reason
	(*GetLibSuccess)(nil),     // 1: chromiumos.test.api.GetLibSuccess
	(*GetLibFailure)(nil),     // 2: chromiumos.test.api.GetLibFailure
	(*GetLibRequest)(nil),     // 3: chromiumos.test.api.GetLibRequest
	(*GetLibResponse)(nil),    // 4: chromiumos.test.api.GetLibResponse
	(*KillLibRequest)(nil),    // 5: chromiumos.test.api.KillLibRequest
	(*KillLibResponse)(nil),   // 6: chromiumos.test.api.KillLibResponse
}
var file_chromiumos_test_api_test_libs_service_proto_depIdxs = []int32{
	0, // 0: chromiumos.test.api.GetLibFailure.reason:type_name -> chromiumos.test.api.GetLibFailure.Reason
	1, // 1: chromiumos.test.api.GetLibResponse.success:type_name -> chromiumos.test.api.GetLibSuccess
	2, // 2: chromiumos.test.api.GetLibResponse.failure:type_name -> chromiumos.test.api.GetLibFailure
	3, // 3: chromiumos.test.api.TestLibsService.StartLib:input_type -> chromiumos.test.api.GetLibRequest
	3, // 4: chromiumos.test.api.TestLibsService.FindLib:input_type -> chromiumos.test.api.GetLibRequest
	5, // 5: chromiumos.test.api.TestLibsService.KillLib:input_type -> chromiumos.test.api.KillLibRequest
	4, // 6: chromiumos.test.api.TestLibsService.StartLib:output_type -> chromiumos.test.api.GetLibResponse
	4, // 7: chromiumos.test.api.TestLibsService.FindLib:output_type -> chromiumos.test.api.GetLibResponse
	6, // 8: chromiumos.test.api.TestLibsService.KillLib:output_type -> chromiumos.test.api.KillLibResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_chromiumos_test_api_test_libs_service_proto_init() }
func file_chromiumos_test_api_test_libs_service_proto_init() {
	if File_chromiumos_test_api_test_libs_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chromiumos_test_api_test_libs_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLibSuccess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_test_libs_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLibFailure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_test_libs_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLibRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_test_libs_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLibResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_test_libs_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KillLibRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_test_libs_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KillLibResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_chromiumos_test_api_test_libs_service_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*GetLibResponse_Success)(nil),
		(*GetLibResponse_Failure)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chromiumos_test_api_test_libs_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chromiumos_test_api_test_libs_service_proto_goTypes,
		DependencyIndexes: file_chromiumos_test_api_test_libs_service_proto_depIdxs,
		EnumInfos:         file_chromiumos_test_api_test_libs_service_proto_enumTypes,
		MessageInfos:      file_chromiumos_test_api_test_libs_service_proto_msgTypes,
	}.Build()
	File_chromiumos_test_api_test_libs_service_proto = out.File
	file_chromiumos_test_api_test_libs_service_proto_rawDesc = nil
	file_chromiumos_test_api_test_libs_service_proto_goTypes = nil
	file_chromiumos_test_api_test_libs_service_proto_depIdxs = nil
}
