# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "metadata_proto",
    srcs = ["metadata.proto"],
    visibility = ["//visibility:public"],
    deps = [
        "//chromiumos/config/api:api_proto",
        "//chromiumos/config/api/test/dut/v1:dut_proto",
        "@com_google_protobuf//:struct_proto",
    ],
)

go_proto_library(
    name = "metadata_go_proto",
    importpath = "go.chromium.org/chromiumos/config/go/api/test/metadata/v1",
    proto = ":metadata_proto",
    visibility = ["//visibility:public"],
    deps = [
        "//chromiumos/config/api",
        "//chromiumos/config/api/test/dut/v1:dut",
    ],
)

go_library(
    name = "metadata",
    embed = [":metadata_go_proto"],
    importpath = "go.chromium.org/chromiumos/config/go/api/test/metadata/v1",
    visibility = ["//visibility:public"],
)
