# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

package(
    default_visibility = ["//:__subpackages__"],
)

cc_library(
    name = "log_fixture",
    testonly = True,
    srcs = ["log_fixture.cc"],
    hdrs = ["log_fixture.h"],
    deps = [
        "@com_google_googletest//:gtest",
    ],
)

cc_library(
    name = "stable_delegate_env",
    testonly = True,
    srcs = ["stable_delegate_env.cc"],
    hdrs = ["stable_delegate_env.h"],
    deps = [
        "@com_google_googletest//:gtest",
        "@org_tensorflow//tensorflow/lite:framework",
        "@org_tensorflow//tensorflow/lite/tools/delegates:delegate_provider_lib",
        "@org_tensorflow//tensorflow/lite/tools/delegates/experimental/stable_delegate:delegate_provider",
    ],
)

cc_library(
    name = "aligned_tflite_buffer_allocator",
    testonly = True,
    srcs = ["aligned_tflite_buffer_allocator.cc"],
    hdrs = ["aligned_tflite_buffer_allocator.h"],
    deps = [
        "@org_tensorflow//tensorflow/lite:util",
    ],
)

cc_library(
    name = "fp16_compare",
    testonly = True,
    srcs = ["fp16_compare.cc"],
    hdrs = ["fp16_compare.h"],
    deps = [
        "@com_google_googletest//:gtest",
    ],
)

cc_binary(
    name = "fp16_compare_test",
    testonly = True,
    srcs = ["fp16_compare_test.cc"],
    deps = [
        ":fp16_compare",
        "@com_google_googletest//:gtest",
    ],
)
