[tool.poetry]
name = "cros_ca_win_lib"
version = "0.1.0"
description = ""
authors = ["Jason Chen"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
psutil = "^5.9.6"
wmi = "^1.4.9"
pywin32 = "*"
selenium = "^4.18.1"
requests = "^2.31.0"
pycaw = "^20240210"

[tool.poetry.scripts]
test_win_local = 'main:test_win_local'

[tool.black]
line-length = 80

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
