// Copyright 2021 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package chromiumos.test.artifact;

import "chromiumos/storage_path.proto";

option go_package = "go.chromium.org/chromiumos/config/go/test/artifact";

// Manifest for test result artifacts.
// NEXT TAG: 3
message Manifest {
  // Captures the manifest version.
  uint32 version = 1;

  // List of associated test result artifacts.
  repeated Artifact artifacts = 2;
}

// Artifact information.
// NEXT TAG: 3
message Artifact {
  // Capture the various artifact types.
  // NEXT TAG: 4
  enum ArtifactType {
    ARTIFACT_TYPE_UNSPECIFIED = 0;
    TEST_RESULT = 1;
    DUT_METADATA = 2;
    TEST_PLAN = 3;
  }

  // Type of the artifact.
  ArtifactType type = 1;

  // Path containing the artifact (usually points to the artifact GCS URL).
  chromiumos.StoragePath storage_path = 2;
}
