# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@bazel_gazelle//:def.bzl", "gazelle")

gazelle(name = "gazelle")
