[package]
name = "opt"
version = "0.1.0"
edition = "2021"
description = "OPENOS Desktop Package Manager CLI - .opt 包管理命令行工具"

[dependencies]
clap = { version = "4", features = ["derive"] }
clap_complete = "4"
serde_json = "1"
zip = { version = "2", default-features = false, features = ["deflate"] }
libopt = { path = "../libopt" }
ureq = { version = "2", features = ["gzip"] }
dirs = "5"
flate2 = "1"
