# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_RUNTIME=y
CONFIG_PM_DEVICE_SHELL=y

# TODO(b/395151088): picolibc build causes a macro redefinition on some source
# files between include/zephyr/posix/posix_features.h and
# picolibc/coreboot-arm-eabi/include/sys/syslimits.h when using the chroot
# coreboot toolchain, use minimal libc until that's resolved.
CONFIG_MINIMAL_LIBC=y

CONFIG_GPIO=y
CONFIG_LOG=y
CONFIG_LOG_PROCESS_THREAD_SLEEP_MS=100
CONFIG_DEBUG_THREAD_INFO=y
CONFIG_COMPILER_TRACK_MACRO_EXPANSION=n
CONFIG_APPLICATION_DEFINED_SYSCALL=y

# USB
CONFIG_USB_DEVICE_STACK=n
CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_USBD_CDC_ACM_CLASS=y
CONFIG_UART_LINE_CTRL=y
CONFIG_UDC_DRIVER_LOG_LEVEL_WRN=y
CONFIG_USBD_CDC_ACM_LOG_LEVEL_OFF=y
CONFIG_USBD_LOG_LEVEL_WRN=y

# I2C
CONFIG_I2C_TARGET=y
CONFIG_I2C_EEPROM_TARGET=y

# Subsystems
CONFIG_SHELL=y
CONFIG_I2C=y
CONFIG_LED=y
CONFIG_INPUT=y
CONFIG_REGULATOR=y
CONFIG_DAC=y
CONFIG_REBOOT=y

# Shell commands
CONFIG_GPIO_SHELL=y
CONFIG_I2C_SHELL=y
CONFIG_LED_SHELL=y
CONFIG_REGULATOR_SHELL=y
CONFIG_DAC_SHELL=y
CONFIG_INPUT_SHELL=y
CONFIG_INPUT_EVENT_DUMP=y

CONFIG_SHELL_PROMPT_UART="dagwood:~$ "
