# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

manifest:
  remotes:
    - name: chromium
      url-base: https://chromium.googlesource.com/chromiumos

  projects:
    - name: zephyr
      remote: chromium
      repo-path: third_party/zephyr
      revision: main
      west-commands: scripts/west-commands.yml

    - name: cmsis_6
      remote: chromium
      repo-path: third_party/zephyr/cmsis_6
      revision: chromeos-main
      path: modules/hal/cmsis_6

    - name: hal_stm32
      remote: chromium
      repo-path: third_party/zephyr/hal_stm32
      revision: chromeos-main
      path: modules/hal/stm32
