# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "graphics_proto",
    srcs = [
        "trace.proto",
        "trace_id.proto",
    ],
    visibility = ["//visibility:public"],
)

go_proto_library(
    name = "graphics_go_proto",
    importpath = "go.chromium.org/chromiumos/config/go/api/test/results/graphics/v1",
    proto = ":graphics_proto",
    visibility = ["//visibility:public"],
)

go_library(
    name = "graphics",
    embed = [":graphics_go_proto"],
    importpath = "go.chromium.org/chromiumos/config/go/api/test/results/graphics/v1",
    visibility = ["//visibility:public"],
)
