// Copyright 2020 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.1
// source: chromiumos/config/api/test/plan/v1/plan.proto

package plan

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Exclusion_Type int32

const (
	// Do not use.
	Exclusion_TYPE_UNSPECIFIED Exclusion_Type = 0
	// There are no active plans to remove these exclusions becuase it is
	// prohibitive to fix the issue or business needs do not justify the effort
	// to fix the issue.
	//
	// Each PERMANENT exclusion MUST include references that point to a business
	// justification for its addition.
	Exclusion_PERMANENT Exclusion_Type = 1
	// Use for excluding new tests from running on devices where the test has
	// not yet been stabilized. The intention is to support incremental rollout
	// of new tests.
	//
	// These exclsusion are temporary. These exclusions SHOULD be routinely
	// audited and resolved or promoted to PERMANENT exclusions.
	Exclusion_TEMPORARY_NEW_TEST Exclusion_Type = 2
	// Use for excluding broken / flakey tests while a fix is being worked on.
	//
	// These exclsusion are temporary. These exclusions SHOULD be routinely
	// audited and resolved or promoted to PERMANENT exclusions.
	Exclusion_TEMPORARY_PENDING_FIX Exclusion_Type = 3
	// No lab devices are deployed matching the coverage rule DUT criteria.
	Exclusion_TEMPORARY_NO_LAB_DEVICES_DEPLOYED Exclusion_Type = 4
	// Insufficient lab devices available to run the coverage rule.
	Exclusion_TEMPORARY_INSUFFICIENT_LAB_DEVICES_AVAILABLE Exclusion_Type = 5
)

// Enum value maps for Exclusion_Type.
var (
	Exclusion_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "PERMANENT",
		2: "TEMPORARY_NEW_TEST",
		3: "TEMPORARY_PENDING_FIX",
		4: "TEMPORARY_NO_LAB_DEVICES_DEPLOYED",
		5: "TEMPORARY_INSUFFICIENT_LAB_DEVICES_AVAILABLE",
	}
	Exclusion_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED":                             0,
		"PERMANENT":                                    1,
		"TEMPORARY_NEW_TEST":                           2,
		"TEMPORARY_PENDING_FIX":                        3,
		"TEMPORARY_NO_LAB_DEVICES_DEPLOYED":            4,
		"TEMPORARY_INSUFFICIENT_LAB_DEVICES_AVAILABLE": 5,
	}
)

func (x Exclusion_Type) Enum() *Exclusion_Type {
	p := new(Exclusion_Type)
	*p = x
	return p
}

func (x Exclusion_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Exclusion_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_chromiumos_config_api_test_plan_v1_plan_proto_enumTypes[0].Descriptor()
}

func (Exclusion_Type) Type() protoreflect.EnumType {
	return &file_chromiumos_config_api_test_plan_v1_plan_proto_enumTypes[0]
}

func (x Exclusion_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Exclusion_Type.Descriptor instead.
func (Exclusion_Type) EnumDescriptor() ([]byte, []int) {
	return file_chromiumos_config_api_test_plan_v1_plan_proto_rawDescGZIP(), []int{5, 0}
}

type Exclusion_Action int32

const (
	// Specify no action.
	//
	// The Test Lab Environment may choose any of the available actions based
	// on internal heuristics.
	//
	// The default Action is a good default if none of the considersations for
	// the specific actions below apply.
	Exclusion_ACTION_UNSPECIFIED Exclusion_Action = 0
	// Do not schedule the selected Tests on specified Devices Under Test.
	//
	// It is especially useful to set this Action for permanent exceptions as it
	// is definitely not useful to run the Tests at all in those cases.
	Exclusion_DO_NOT_SCHEDULE Exclusion_Action = 1
	// Schedule the Test on Devices Under Test as required by the test plan
	// unit, but mark the results for selected tests on the specified Devices
	// Under Test as non-critical. Results marked non-critical are intended to
	// be ignored by result consumers (e.g, presubmit system should consider the
	// result irrelevant for validatting a Chrome OS build).
	//
	// This action does not guarantee that results for the selected (Test,
	// Device Under Test) pairs are always available because that depends no how
	// the test plan Unit is interpreted overall. When this action is set, the
	// Test Lab Environment SHOULD NOT make any special effort to include /
	// exclude the selected (Test, Device Under Test) pairs.
	//
	// It is useful to set this Action for temporary exclusions where the
	// results generated from test execution can be uesd to root cause and fix
	// the underlying issues.
	Exclusion_MARK_NON_CRITICAL Exclusion_Action = 2
)

// Enum value maps for Exclusion_Action.
var (
	Exclusion_Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "DO_NOT_SCHEDULE",
		2: "MARK_NON_CRITICAL",
	}
	Exclusion_Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"DO_NOT_SCHEDULE":    1,
		"MARK_NON_CRITICAL":  2,
	}
)

func (x Exclusion_Action) Enum() *Exclusion_Action {
	p := new(Exclusion_Action)
	*p = x
	return p
}

func (x Exclusion_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Exclusion_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_chromiumos_config_api_test_plan_v1_plan_proto_enumTypes[1].Descriptor()
}

func (Exclusion_Action) Type() protoreflect.EnumType {
	return &file_chromiumos_config_api_test_plan_v1_plan_proto_enumTypes[1]
}

func (x Exclusion_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Exclusion_Action.Descriptor instead.
func (Exclusion_Action) EnumDescriptor() ([]byte, []int) {
	return file_chromiumos_config_api_test_plan_v1_plan_proto_rawDescGZIP(), []int{5, 1}
}

// A set of known test plans.
//
// In practice, a complete specification of all known plans may consist of
// multiple Specification instances. In that case the plan names MUST be unique
// across different Specification instances.
type Specification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plans []*Plan `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty"`
}

func (x *Specification) Reset() {
	*x = Specification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_config_api_test_plan_v1_plan_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Specification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Specification) ProtoMessage() {}

func (x *Specification) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_config_api_test_plan_v1_plan_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Specification.ProtoReflect.Descriptor instead.
func (*Specification) Descriptor() ([]byte, []int) {
	return file_chromiumos_config_api_test_plan_v1_plan_proto_rawDescGZIP(), []int{0}
}

func (x *Specification) GetPlans() []*Plan {
	if x != nil {
		return x.Plans
	}
	return nil
}

// A Plan fully specifies a Test Platform end-user's coverage needs.
//
// Plans SHOULD associate platform software and Device Under Test condition
// coverage rules with tests that exercise those components. Plans MUST be used
// in the Test Platform request API. Other Test Lab Environments may use plans
// to ease interoperation with the Test Platform.
type Plan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A globally unique test plan name.
	//
	// MUST be valid resource name per https://aip.dev/122.
	//
	// Pattern: plans/{plan}
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Each test plan unit specifies a particular set of tests to be run to meet
	// specific conditions.
	Units []*Unit `protobuf:"bytes,2,rep,name=units,proto3" json:"units,omitempty"`
}

func (x *Plan) Reset() {
	*x = Plan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_config_api_test_plan_v1_plan_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Plan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plan) ProtoMessage() {}

func (x *Plan) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_config_api_test_plan_v1_plan_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plan.ProtoReflect.Descriptor instead.
func (*Plan) Descriptor() ([]byte, []int) {
	return file_chromiumos_config_api_test_plan_v1_plan_proto_rawDescGZIP(), []int{1}
}

func (x *Plan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Plan) GetUnits() []*Unit {
	if x != nil {
		return x.Units
	}
	return nil
}

// Defines the device rule that must be met in for a given set of tests.
// Examples:
// attribute='hw_components.soc.family.arch', value=['X86']
type DutCriterion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// String encoded path to the attribute from DeviceUnderTest
	Attribute string `protobuf:"bytes,1,opt,name=attribute,proto3" json:"attribute,omitempty"`
	// String encoded values, where enums are encoded as their name (not value)
	// Setting multiple values here treats this as an OR clause wrt matching.
	// This gives freedom to the scheduling system to find devices with the most
	// available idle capacity that match one of these values.
	Values []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *DutCriterion) Reset() {
	*x = DutCriterion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_config_api_test_plan_v1_plan_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DutCriterion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DutCriterion) ProtoMessage() {}

func (x *DutCriterion) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_config_api_test_plan_v1_plan_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DutCriterion.ProtoReflect.Descriptor instead.
func (*DutCriterion) Descriptor() ([]byte, []int) {
	return file_chromiumos_config_api_test_plan_v1_plan_proto_rawDescGZIP(), []int{2}
}

func (x *DutCriterion) GetAttribute() string {
	if x != nil {
		return x.Attribute
	}
	return ""
}

func (x *DutCriterion) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type CoverageRule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Human friendly name for easier analysis of test coverage rules/criteria.
	// E.g. kernel:5.4_soc:geminilake_wifi:intel-5600
	// Specifically, this helps when generalizing OR criteria (e.g. kernel
	// versions)
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// These are criteria that must be met.  ANDs and ORs.
	DutCriteria []*DutCriterion `protobuf:"bytes,2,rep,name=dut_criteria,json=dutCriteria,proto3" json:"dut_criteria,omitempty"`
	// Optional exclusion that applies to only to the given dut coverage criteria.
	// E.g. If a specific device was failing the wifi test suite.
	Exclusion *Exclusion `protobuf:"bytes,4,opt,name=exclusion,proto3" json:"exclusion,omitempty"`
}

func (x *CoverageRule) Reset() {
	*x = CoverageRule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_config_api_test_plan_v1_plan_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CoverageRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoverageRule) ProtoMessage() {}

func (x *CoverageRule) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_config_api_test_plan_v1_plan_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoverageRule.ProtoReflect.Descriptor instead.
func (*CoverageRule) Descriptor() ([]byte, []int) {
	return file_chromiumos_config_api_test_plan_v1_plan_proto_rawDescGZIP(), []int{3}
}

func (x *CoverageRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CoverageRule) GetDutCriteria() []*DutCriterion {
	if x != nil {
		return x.DutCriteria
	}
	return nil
}

func (x *CoverageRule) GetExclusion() *Exclusion {
	if x != nil {
		return x.Exclusion
	}
	return nil
}

// Specifies a particular set of tests to be run for a given set of coverage
// rules.
type Unit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A globally unique test plan unit name.
	//
	// MUST be valid resource name per https://aip.dev/122.
	//
	// Pattern: plans/{plan}/units/{unit}
	//   where {plan} is the parent Plan of this Unit.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Defines the tests that are included.
	Suites []*Unit_Suite `protobuf:"bytes,2,rep,name=suites,proto3" json:"suites,omitempty"`
	Tests  []*Unit_Test  `protobuf:"bytes,3,rep,name=tests,proto3" json:"tests,omitempty"`
	// Defines all of the coverage rules that need to be executed
	// for the given tests.
	// Separate test results will be generated for each distinct coverage rule.
	CoverageRules []*CoverageRule `protobuf:"bytes,4,rep,name=coverage_rules,json=coverageRules,proto3" json:"coverage_rules,omitempty"`
	// Optional exclusion that applies to tests in the given unit.
	// E.g. If the test itself was bad, regardless of the device tested
	// against.
	Exclusion *Exclusion `protobuf:"bytes,5,opt,name=exclusion,proto3" json:"exclusion,omitempty"`
}

func (x *Unit) Reset() {
	*x = Unit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_config_api_test_plan_v1_plan_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Unit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unit) ProtoMessage() {}

func (x *Unit) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_config_api_test_plan_v1_plan_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unit.ProtoReflect.Descriptor instead.
func (*Unit) Descriptor() ([]byte, []int) {
	return file_chromiumos_config_api_test_plan_v1_plan_proto_rawDescGZIP(), []int{4}
}

func (x *Unit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Unit) GetSuites() []*Unit_Suite {
	if x != nil {
		return x.Suites
	}
	return nil
}

func (x *Unit) GetTests() []*Unit_Test {
	if x != nil {
		return x.Tests
	}
	return nil
}

func (x *Unit) GetCoverageRules() []*CoverageRule {
	if x != nil {
		return x.CoverageRules
	}
	return nil
}

func (x *Unit) GetExclusion() *Exclusion {
	if x != nil {
		return x.Exclusion
	}
	return nil
}

// Exclusion is used to record exceptions to the test plan
// specification for devices that are known to cause test failures for some
// temporary or permanent reasons.
type Exclusion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Required.
	Type   Exclusion_Type   `protobuf:"varint,1,opt,name=type,proto3,enum=chromiumos.config.api.test.plan.v1.Exclusion_Type" json:"type,omitempty"`
	Action Exclusion_Action `protobuf:"varint,5,opt,name=action,proto3,enum=chromiumos.config.api.test.plan.v1.Exclusion_Action" json:"action,omitempty"`
	// External references useful for archeology for this exclusion.
	//
	// PERMANENT exclusions MUST add references for the decision to make the
	// exclusion PERMANENT.
	//
	// References should be links with more context behind the decision.
	// Suggested forms:
	// * Monorail bug: https://bugs.chromium.org/p/chromium/issues/detail?id=XXX
	// * Buganizer bug: https://b.corp.google.com/issues/XXX
	References []string `protobuf:"bytes,4,rep,name=references,proto3" json:"references,omitempty"`
}

func (x *Exclusion) Reset() {
	*x = Exclusion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_config_api_test_plan_v1_plan_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Exclusion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exclusion) ProtoMessage() {}

func (x *Exclusion) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_config_api_test_plan_v1_plan_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exclusion.ProtoReflect.Descriptor instead.
func (*Exclusion) Descriptor() ([]byte, []int) {
	return file_chromiumos_config_api_test_plan_v1_plan_proto_rawDescGZIP(), []int{5}
}

func (x *Exclusion) GetType() Exclusion_Type {
	if x != nil {
		return x.Type
	}
	return Exclusion_TYPE_UNSPECIFIED
}

func (x *Exclusion) GetAction() Exclusion_Action {
	if x != nil {
		return x.Action
	}
	return Exclusion_ACTION_UNSPECIFIED
}

func (x *Exclusion) GetReferences() []string {
	if x != nil {
		return x.References
	}
	return nil
}

type Unit_Suite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Name of the test suite to be executed
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Unit_Suite) Reset() {
	*x = Unit_Suite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_config_api_test_plan_v1_plan_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Unit_Suite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unit_Suite) ProtoMessage() {}

func (x *Unit_Suite) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_config_api_test_plan_v1_plan_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unit_Suite.ProtoReflect.Descriptor instead.
func (*Unit_Suite) Descriptor() ([]byte, []int) {
	return file_chromiumos_config_api_test_plan_v1_plan_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Unit_Suite) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Unit_Test struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Name of the test as specified in test.metadata.Test.name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The test attribute name as specified in the test.metadata.Attribute.name
	//
	// attributes are populated from test.metadata.Test.attributes.
	Attributes []string `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty"`
}

func (x *Unit_Test) Reset() {
	*x = Unit_Test{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_config_api_test_plan_v1_plan_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Unit_Test) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unit_Test) ProtoMessage() {}

func (x *Unit_Test) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_config_api_test_plan_v1_plan_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unit_Test.ProtoReflect.Descriptor instead.
func (*Unit_Test) Descriptor() ([]byte, []int) {
	return file_chromiumos_config_api_test_plan_v1_plan_proto_rawDescGZIP(), []int{4, 1}
}

func (x *Unit_Test) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Unit_Test) GetAttributes() []string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_chromiumos_config_api_test_plan_v1_plan_proto protoreflect.FileDescriptor

var file_chromiumos_config_api_test_plan_v1_plan_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x70, 0x6c, 0x61,
	0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6c, 0x61, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x22, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x6c, 0x61, 0x6e,
	0x2e, 0x76, 0x31, 0x22, 0x4f, 0x0a, 0x0d, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3e, 0x0a, 0x05, 0x70, 0x6c, 0x61, 0x6e, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73,
	0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x65, 0x73, 0x74,
	0x2e, 0x70, 0x6c, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x05, 0x70,
	0x6c, 0x61, 0x6e, 0x73, 0x22, 0x5a, 0x0a, 0x04, 0x50, 0x6c, 0x61, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x3e, 0x0a, 0x05, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x28, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x6c, 0x61,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x05, 0x75, 0x6e, 0x69, 0x74, 0x73,
	0x22, 0x44, 0x0a, 0x0c, 0x44, 0x75, 0x74, 0x43, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x6f, 0x6e,
	0x12, 0x1c, 0x0a, 0x09, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0xc4, 0x01, 0x0a, 0x0c, 0x43, 0x6f, 0x76, 0x65, 0x72,
	0x61, 0x67, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x53, 0x0a, 0x0c, 0x64,
	0x75, 0x74, 0x5f, 0x63, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x30, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70,
	0x6c, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x75, 0x74, 0x43, 0x72, 0x69, 0x74, 0x65, 0x72,
	0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x64, 0x75, 0x74, 0x43, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x61,
	0x12, 0x4b, 0x0a, 0x09, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73,
	0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x65, 0x73, 0x74,
	0x2e, 0x70, 0x6c, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x09, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xa6, 0x03,
	0x0a, 0x04, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x46, 0x0a, 0x06, 0x73, 0x75,
	0x69, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x63, 0x68, 0x72,
	0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x6c, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x55, 0x6e, 0x69, 0x74, 0x2e, 0x53, 0x75, 0x69, 0x74, 0x65, 0x52, 0x06, 0x73, 0x75, 0x69, 0x74,
	0x65, 0x73, 0x12, 0x43, 0x0a, 0x05, 0x74, 0x65, 0x73, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x2d, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70,
	0x6c, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x6e, 0x69, 0x74, 0x2e, 0x54, 0x65, 0x73, 0x74,
	0x52, 0x05, 0x74, 0x65, 0x73, 0x74, 0x73, 0x12, 0x57, 0x0a, 0x0e, 0x63, 0x6f, 0x76, 0x65, 0x72,
	0x61, 0x67, 0x65, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x30, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x6c, 0x61,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x52, 0x75, 0x6c,
	0x65, 0x52, 0x0d, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x73,
	0x12, 0x4b, 0x0a, 0x09, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73,
	0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x65, 0x73, 0x74,
	0x2e, 0x70, 0x6c, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x09, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x6f, 0x6e, 0x1a, 0x1b, 0x0a,
	0x05, 0x53, 0x75, 0x69, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x3a, 0x0a, 0x04, 0x54, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x22, 0xc9, 0x03, 0x0a, 0x09, 0x45, 0x78, 0x63, 0x6c, 0x75,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x46, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x32, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e,
	0x70, 0x6c, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x6f,
	0x6e, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x4c, 0x0a, 0x06,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x34, 0x2e, 0x63,
	0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x6c, 0x61, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a,
	0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x22, 0xb7, 0x01, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x45, 0x52,
	0x4d, 0x41, 0x4e, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x54, 0x45, 0x4d, 0x50,
	0x4f, 0x52, 0x41, 0x52, 0x59, 0x5f, 0x4e, 0x45, 0x57, 0x5f, 0x54, 0x45, 0x53, 0x54, 0x10, 0x02,
	0x12, 0x19, 0x0a, 0x15, 0x54, 0x45, 0x4d, 0x50, 0x4f, 0x52, 0x41, 0x52, 0x59, 0x5f, 0x50, 0x45,
	0x4e, 0x44, 0x49, 0x4e, 0x47, 0x5f, 0x46, 0x49, 0x58, 0x10, 0x03, 0x12, 0x25, 0x0a, 0x21, 0x54,
	0x45, 0x4d, 0x50, 0x4f, 0x52, 0x41, 0x52, 0x59, 0x5f, 0x4e, 0x4f, 0x5f, 0x4c, 0x41, 0x42, 0x5f,
	0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x53, 0x5f, 0x44, 0x45, 0x50, 0x4c, 0x4f, 0x59, 0x45, 0x44,
	0x10, 0x04, 0x12, 0x30, 0x0a, 0x2c, 0x54, 0x45, 0x4d, 0x50, 0x4f, 0x52, 0x41, 0x52, 0x59, 0x5f,
	0x49, 0x4e, 0x53, 0x55, 0x46, 0x46, 0x49, 0x43, 0x49, 0x45, 0x4e, 0x54, 0x5f, 0x4c, 0x41, 0x42,
	0x5f, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x53, 0x5f, 0x41, 0x56, 0x41, 0x49, 0x4c, 0x41, 0x42,
	0x4c, 0x45, 0x10, 0x05, 0x22, 0x4c, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16,
	0x0a, 0x12, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x44, 0x4f, 0x5f, 0x4e, 0x4f, 0x54,
	0x5f, 0x53, 0x43, 0x48, 0x45, 0x44, 0x55, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x4d,
	0x41, 0x52, 0x4b, 0x5f, 0x4e, 0x4f, 0x4e, 0x5f, 0x43, 0x52, 0x49, 0x54, 0x49, 0x43, 0x41, 0x4c,
	0x10, 0x02, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x6f, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75,
	0x6d, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73,
	0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x67, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74,
	0x65, 0x73, 0x74, 0x2f, 0x70, 0x6c, 0x61, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x6c, 0x61, 0x6e,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chromiumos_config_api_test_plan_v1_plan_proto_rawDescOnce sync.Once
	file_chromiumos_config_api_test_plan_v1_plan_proto_rawDescData = file_chromiumos_config_api_test_plan_v1_plan_proto_rawDesc
)

func file_chromiumos_config_api_test_plan_v1_plan_proto_rawDescGZIP() []byte {
	file_chromiumos_config_api_test_plan_v1_plan_proto_rawDescOnce.Do(func() {
		file_chromiumos_config_api_test_plan_v1_plan_proto_rawDescData = protoimpl.X.CompressGZIP(file_chromiumos_config_api_test_plan_v1_plan_proto_rawDescData)
	})
	return file_chromiumos_config_api_test_plan_v1_plan_proto_rawDescData
}

var file_chromiumos_config_api_test_plan_v1_plan_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_chromiumos_config_api_test_plan_v1_plan_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_chromiumos_config_api_test_plan_v1_plan_proto_goTypes = []interface{}{
	(Exclusion_Type)(0),   // 0: chromiumos.config.api.test.plan.v1.Exclusion.Type
	(Exclusion_Action)(0), // 1: chromiumos.config.api.test.plan.v1.Exclusion.Action
	(*Specification)(nil), // 2: chromiumos.config.api.test.plan.v1.Specification
	(*Plan)(nil),          // 3: chromiumos.config.api.test.plan.v1.Plan
	(*DutCriterion)(nil),  // 4: chromiumos.config.api.test.plan.v1.DutCriterion
	(*CoverageRule)(nil),  // 5: chromiumos.config.api.test.plan.v1.CoverageRule
	(*Unit)(nil),          // 6: chromiumos.config.api.test.plan.v1.Unit
	(*Exclusion)(nil),     // 7: chromiumos.config.api.test.plan.v1.Exclusion
	(*Unit_Suite)(nil),    // 8: chromiumos.config.api.test.plan.v1.Unit.Suite
	(*Unit_Test)(nil),     // 9: chromiumos.config.api.test.plan.v1.Unit.Test
}
var file_chromiumos_config_api_test_plan_v1_plan_proto_depIdxs = []int32{
	3,  // 0: chromiumos.config.api.test.plan.v1.Specification.plans:type_name -> chromiumos.config.api.test.plan.v1.Plan
	6,  // 1: chromiumos.config.api.test.plan.v1.Plan.units:type_name -> chromiumos.config.api.test.plan.v1.Unit
	4,  // 2: chromiumos.config.api.test.plan.v1.CoverageRule.dut_criteria:type_name -> chromiumos.config.api.test.plan.v1.DutCriterion
	7,  // 3: chromiumos.config.api.test.plan.v1.CoverageRule.exclusion:type_name -> chromiumos.config.api.test.plan.v1.Exclusion
	8,  // 4: chromiumos.config.api.test.plan.v1.Unit.suites:type_name -> chromiumos.config.api.test.plan.v1.Unit.Suite
	9,  // 5: chromiumos.config.api.test.plan.v1.Unit.tests:type_name -> chromiumos.config.api.test.plan.v1.Unit.Test
	5,  // 6: chromiumos.config.api.test.plan.v1.Unit.coverage_rules:type_name -> chromiumos.config.api.test.plan.v1.CoverageRule
	7,  // 7: chromiumos.config.api.test.plan.v1.Unit.exclusion:type_name -> chromiumos.config.api.test.plan.v1.Exclusion
	0,  // 8: chromiumos.config.api.test.plan.v1.Exclusion.type:type_name -> chromiumos.config.api.test.plan.v1.Exclusion.Type
	1,  // 9: chromiumos.config.api.test.plan.v1.Exclusion.action:type_name -> chromiumos.config.api.test.plan.v1.Exclusion.Action
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_chromiumos_config_api_test_plan_v1_plan_proto_init() }
func file_chromiumos_config_api_test_plan_v1_plan_proto_init() {
	if File_chromiumos_config_api_test_plan_v1_plan_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chromiumos_config_api_test_plan_v1_plan_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Specification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_config_api_test_plan_v1_plan_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Plan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_config_api_test_plan_v1_plan_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DutCriterion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_config_api_test_plan_v1_plan_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CoverageRule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_config_api_test_plan_v1_plan_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Unit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_config_api_test_plan_v1_plan_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Exclusion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_config_api_test_plan_v1_plan_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Unit_Suite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_config_api_test_plan_v1_plan_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Unit_Test); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chromiumos_config_api_test_plan_v1_plan_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chromiumos_config_api_test_plan_v1_plan_proto_goTypes,
		DependencyIndexes: file_chromiumos_config_api_test_plan_v1_plan_proto_depIdxs,
		EnumInfos:         file_chromiumos_config_api_test_plan_v1_plan_proto_enumTypes,
		MessageInfos:      file_chromiumos_config_api_test_plan_v1_plan_proto_msgTypes,
	}.Build()
	File_chromiumos_config_api_test_plan_v1_plan_proto = out.File
	file_chromiumos_config_api_test_plan_v1_plan_proto_rawDesc = nil
	file_chromiumos_config_api_test_plan_v1_plan_proto_goTypes = nil
	file_chromiumos_config_api_test_plan_v1_plan_proto_depIdxs = nil
}
