[package]
name = "spdm"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[lib]
name = "spdm"

[dependencies]
spdm_proc_macros = { path = "../spdm-proc-macros" }
spdm_types = { path = "../spdm-types" }
open-enum = "0.3.0"
zerocopy = "0.6.1"
uninit = { version = "0.6", default-features = false }
mocktopus = { version = "0.8.0", optional = true } # ignored unless use.spdm_unstable_tests by ebuild

[dev-dependencies]
spdm_test_deps = { path = "../test-deps" }

[features]
# The mocktopus dependencies are only used when this feature is active because
# CrOS ebuild doesn't support unstable rust features used by mocktopus by
# default.
mock = [ "mocktopus" ] # ignored unless use.spdm_unstable_tests by ebuild
