# Copyright 2026 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

steps:
  # Fetch Realtek files to satisfy Dockerfile COPY instruction
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mkdir -p dist
        gcloud storage cp "gs://rtk-tools/rtunicpg-2.0.25.3.tar.bz2" "dist/rtunicpg.tar.bz2"
        gcloud storage cp "gs://rtk-tools/r8152-2.21.4.tar.bz2" "dist/r8152.tar.bz2"

  # Build the DEB package using Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'deb-builder', '-f', 'development_environment/deb_builder/Dockerfile', '.']

  # Extract the DEB file from the image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker create --name temp-container deb-builder
        docker cp temp-container:/diagnoseme.deb .
        docker rm temp-container

  # Upload the DEB to Artifact Registry
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud artifacts apt upload diagnoseme-deb \
          --project=chromeos-hw-tools \
          --location=us \
          --source=diagnoseme.deb
