// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.1.0
// - protoc             v3.17.1
// source: chromiumos/test/lab/api/dut_provision_service.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DutProvisionServiceClient is the client API for DutProvisionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DutProvisionServiceClient interface {
	// Uploads provisioning attempts data to BigQuery.
	UploadProvisionMetrics(ctx context.Context, in *UploadProvisionMetricsRequest, opts ...grpc.CallOption) (*UploadProvisionMetricsResponse, error)
}

type dutProvisionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDutProvisionServiceClient(cc grpc.ClientConnInterface) DutProvisionServiceClient {
	return &dutProvisionServiceClient{cc}
}

func (c *dutProvisionServiceClient) UploadProvisionMetrics(ctx context.Context, in *UploadProvisionMetricsRequest, opts ...grpc.CallOption) (*UploadProvisionMetricsResponse, error) {
	out := new(UploadProvisionMetricsResponse)
	err := c.cc.Invoke(ctx, "/chromiumos.test.lab.api.DutProvisionService/UploadProvisionMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DutProvisionServiceServer is the server API for DutProvisionService service.
// All implementations should embed UnimplementedDutProvisionServiceServer
// for forward compatibility
type DutProvisionServiceServer interface {
	// Uploads provisioning attempts data to BigQuery.
	UploadProvisionMetrics(context.Context, *UploadProvisionMetricsRequest) (*UploadProvisionMetricsResponse, error)
}

// UnimplementedDutProvisionServiceServer should be embedded to have forward compatible implementations.
type UnimplementedDutProvisionServiceServer struct {
}

func (UnimplementedDutProvisionServiceServer) UploadProvisionMetrics(context.Context, *UploadProvisionMetricsRequest) (*UploadProvisionMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadProvisionMetrics not implemented")
}

// UnsafeDutProvisionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DutProvisionServiceServer will
// result in compilation errors.
type UnsafeDutProvisionServiceServer interface {
	mustEmbedUnimplementedDutProvisionServiceServer()
}

func RegisterDutProvisionServiceServer(s grpc.ServiceRegistrar, srv DutProvisionServiceServer) {
	s.RegisterService(&DutProvisionService_ServiceDesc, srv)
}

func _DutProvisionService_UploadProvisionMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadProvisionMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DutProvisionServiceServer).UploadProvisionMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chromiumos.test.lab.api.DutProvisionService/UploadProvisionMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DutProvisionServiceServer).UploadProvisionMetrics(ctx, req.(*UploadProvisionMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DutProvisionService_ServiceDesc is the grpc.ServiceDesc for DutProvisionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DutProvisionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chromiumos.test.lab.api.DutProvisionService",
	HandlerType: (*DutProvisionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadProvisionMetrics",
			Handler:    _DutProvisionService_UploadProvisionMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chromiumos/test/lab/api/dut_provision_service.proto",
}
