// Copyright 2022 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.1
// source: chromiumos/test/lab/api/usb_drive.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UsbDrive describes details of the USB drive.
type UsbDrive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// serial provides the serial number of the USB drive.
	Serial string `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	// manufacturer provides the manufacturer name of the USB drive.
	Manufacturer string `protobuf:"bytes,2,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	// first_seen_time provides the time when the USB drive was first seen
	// in lab or test systems. This is used as an optional heuristic to track
	// the lifetime of USB drives and failure rates.
	FirstSeenTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=first_seen_time,json=firstSeenTime,proto3" json:"first_seen_time,omitempty"`
}

func (x *UsbDrive) Reset() {
	*x = UsbDrive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_lab_api_usb_drive_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsbDrive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsbDrive) ProtoMessage() {}

func (x *UsbDrive) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_lab_api_usb_drive_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsbDrive.ProtoReflect.Descriptor instead.
func (*UsbDrive) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_lab_api_usb_drive_proto_rawDescGZIP(), []int{0}
}

func (x *UsbDrive) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *UsbDrive) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *UsbDrive) GetFirstSeenTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSeenTime
	}
	return nil
}

var File_chromiumos_test_lab_api_usb_drive_proto protoreflect.FileDescriptor

var file_chromiumos_test_lab_api_usb_drive_proto_rawDesc = []byte{
	0x0a, 0x27, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2f, 0x74, 0x65, 0x73,
	0x74, 0x2f, 0x6c, 0x61, 0x62, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x75, 0x73, 0x62, 0x5f, 0x64, 0x72,
	0x69, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x63, 0x68, 0x72, 0x6f, 0x6d,
	0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x6c, 0x61, 0x62, 0x2e, 0x61,
	0x70, 0x69, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x8a, 0x01, 0x0a, 0x08, 0x55, 0x73, 0x62, 0x44, 0x72, 0x69, 0x76, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x61, 0x6e, 0x75,
	0x66, 0x61, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x6d, 0x61, 0x6e, 0x75, 0x66, 0x61, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x12, 0x42, 0x0a, 0x0f,
	0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x65, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x0d, 0x66, 0x69, 0x72, 0x73, 0x74, 0x53, 0x65, 0x65, 0x6e, 0x54, 0x69, 0x6d, 0x65,
	0x42, 0x33, 0x5a, 0x31, 0x67, 0x6f, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x2e,
	0x6f, 0x72, 0x67, 0x2f, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2f, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x67, 0x6f, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x6c, 0x61,
	0x62, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chromiumos_test_lab_api_usb_drive_proto_rawDescOnce sync.Once
	file_chromiumos_test_lab_api_usb_drive_proto_rawDescData = file_chromiumos_test_lab_api_usb_drive_proto_rawDesc
)

func file_chromiumos_test_lab_api_usb_drive_proto_rawDescGZIP() []byte {
	file_chromiumos_test_lab_api_usb_drive_proto_rawDescOnce.Do(func() {
		file_chromiumos_test_lab_api_usb_drive_proto_rawDescData = protoimpl.X.CompressGZIP(file_chromiumos_test_lab_api_usb_drive_proto_rawDescData)
	})
	return file_chromiumos_test_lab_api_usb_drive_proto_rawDescData
}

var file_chromiumos_test_lab_api_usb_drive_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_chromiumos_test_lab_api_usb_drive_proto_goTypes = []interface{}{
	(*UsbDrive)(nil),              // 0: chromiumos.test.lab.api.UsbDrive
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_chromiumos_test_lab_api_usb_drive_proto_depIdxs = []int32{
	1, // 0: chromiumos.test.lab.api.UsbDrive.first_seen_time:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_chromiumos_test_lab_api_usb_drive_proto_init() }
func file_chromiumos_test_lab_api_usb_drive_proto_init() {
	if File_chromiumos_test_lab_api_usb_drive_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chromiumos_test_lab_api_usb_drive_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsbDrive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chromiumos_test_lab_api_usb_drive_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chromiumos_test_lab_api_usb_drive_proto_goTypes,
		DependencyIndexes: file_chromiumos_test_lab_api_usb_drive_proto_depIdxs,
		MessageInfos:      file_chromiumos_test_lab_api_usb_drive_proto_msgTypes,
	}.Build()
	File_chromiumos_test_lab_api_usb_drive_proto = out.File
	file_chromiumos_test_lab_api_usb_drive_proto_rawDesc = nil
	file_chromiumos_test_lab_api_usb_drive_proto_goTypes = nil
	file_chromiumos_test_lab_api_usb_drive_proto_depIdxs = nil
}
