# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "software_proto",
    srcs = [
        "audio_config.proto",
        "bluetooth_config.proto",
        "brand_config.proto",
        "camera_config.proto",
        "firmware_info.proto",
        "health_config.proto",
        "nnpalm_config.proto",
        "power_config.proto",
        "rma_config.proto",
        "software_config.proto",
        "ui_config.proto",
        "usb_config.proto",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//chromiumos/build/api:api_proto",
        "//chromiumos/config/api:api_proto",
        "//chromiumos/config/public_replication:public_replication_proto",
    ],
)

go_proto_library(
    name = "software_go_proto",
    importpath = "go.chromium.org/chromiumos/config/go/api/software",
    proto = ":software_proto",
    visibility = ["//visibility:public"],
    deps = [
        "//chromiumos/build/api",
        "//chromiumos/config/api",
        "//chromiumos/config/public_replication",
    ],
)

go_library(
    name = "software",
    embed = [":software_go_proto"],
    importpath = "go.chromium.org/chromiumos/config/go/api/software",
    visibility = ["//visibility:public"],
)
