# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from chromiumos.test.lab.api.passport import usb_tester_service_pb2 as chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2


class UsbTesterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTesters = channel.unary_unary(
                '/chromiumos.test.lab.api.passport.UsbTesterService/GetTesters',
                request_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.GetTestersRequest.SerializeToString,
                response_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.GetTestersReply.FromString,
                )
        self.GetTesterCapability = channel.unary_unary(
                '/chromiumos.test.lab.api.passport.UsbTesterService/GetTesterCapability',
                request_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.GetUsbTesterCapabilityRequest.SerializeToString,
                response_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.GetUsbTesterCapabilityReply.FromString,
                )
        self.SetTesterCapability = channel.unary_unary(
                '/chromiumos.test.lab.api.passport.UsbTesterService/SetTesterCapability',
                request_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.SetUsbTesterCapabilityRequest.SerializeToString,
                response_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.SetUsbTesterCapabilityReply.FromString,
                )
        self.GetDpInfo = channel.unary_unary(
                '/chromiumos.test.lab.api.passport.UsbTesterService/GetDpInfo',
                request_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.GetDpInfoRequest.SerializeToString,
                response_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.GetDpInfoReply.FromString,
                )
        self.GetPdos = channel.unary_unary(
                '/chromiumos.test.lab.api.passport.UsbTesterService/GetPdos',
                request_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.GetPdosRequest.SerializeToString,
                response_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.GetPdosReply.FromString,
                )
        self.ReplugCable = channel.unary_unary(
                '/chromiumos.test.lab.api.passport.UsbTesterService/ReplugCable',
                request_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.DoCableReplugRequest.SerializeToString,
                response_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.DoCableReplugReply.FromString,
                )
        self.HardResetTester = channel.unary_unary(
                '/chromiumos.test.lab.api.passport.UsbTesterService/HardResetTester',
                request_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.HardResetTesterRequest.SerializeToString,
                response_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.HardResetTesterReply.FromString,
                )
        self.ResetPd = channel.unary_unary(
                '/chromiumos.test.lab.api.passport.UsbTesterService/ResetPd',
                request_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.ResetPdRequest.SerializeToString,
                response_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.ResetPdReply.FromString,
                )
        self.OpenTester = channel.unary_unary(
                '/chromiumos.test.lab.api.passport.UsbTesterService/OpenTester',
                request_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.OpenTesterRequest.SerializeToString,
                response_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.OpenTesterReply.FromString,
                )
        self.CloseTester = channel.unary_unary(
                '/chromiumos.test.lab.api.passport.UsbTesterService/CloseTester',
                request_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.CloseTesterRequest.SerializeToString,
                response_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.CloseTesterReply.FromString,
                )
        self.GetActivePort = channel.unary_unary(
                '/chromiumos.test.lab.api.passport.UsbTesterService/GetActivePort',
                request_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.GetActivePortRequest.SerializeToString,
                response_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.GetActivePortReply.FromString,
                )
        self.SetActivePort = channel.unary_unary(
                '/chromiumos.test.lab.api.passport.UsbTesterService/SetActivePort',
                request_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.SetActivePortRequest.SerializeToString,
                response_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.SetActivePortReply.FromString,
                )
        self.LoadEdid = channel.unary_unary(
                '/chromiumos.test.lab.api.passport.UsbTesterService/LoadEdid',
                request_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.LoadEdidRequest.SerializeToString,
                response_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.LoadEdidReply.FromString,
                )
        self.SendVdmHpd = channel.unary_unary(
                '/chromiumos.test.lab.api.passport.UsbTesterService/SendVdmHpd',
                request_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.SendVdmHpdRequest.SerializeToString,
                response_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.SendVdmHpdReply.FromString,
                )
        self.SimulateKeyPress = channel.unary_unary(
                '/chromiumos.test.lab.api.passport.UsbTesterService/SimulateKeyPress',
                request_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.SimulateKeyPressRequest.SerializeToString,
                response_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.SimulateKeyPressReply.FromString,
                )
        self.SendPdAlert = channel.unary_unary(
                '/chromiumos.test.lab.api.passport.UsbTesterService/SendPdAlert',
                request_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.SendPdAlertRequest.SerializeToString,
                response_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.SendPdAlertReply.FromString,
                )
        self.GetPdStats = channel.unary_unary(
                '/chromiumos.test.lab.api.passport.UsbTesterService/GetPdStats',
                request_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.GetPdStatsRequest.SerializeToString,
                response_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.GetPdStatsReply.FromString,
                )
        self.ResetPdStats = channel.unary_unary(
                '/chromiumos.test.lab.api.passport.UsbTesterService/ResetPdStats',
                request_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.ResetPdStatsRequest.SerializeToString,
                response_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.ResetPdStatsReply.FromString,
                )


class UsbTesterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTesters(self, request, context):
        """Probe all testers connected to the host device.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTesterCapability(self, request, context):
        """Get the value of a certain capability, eg: data role, power role etc ...
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTesterCapability(self, request, context):
        """Set the value of a certain capability, eg: data role, power role etc ...
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDpInfo(self, request, context):
        """Get the display port alternate mode information.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPdos(self, request, context):
        """Get the power delivery objects
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplugCable(self, request, context):
        """Simulate the physical disconnect and reconnect of the cable between the
        tester and the DUT.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HardResetTester(self, request, context):
        """This method is used to do a hard reset/power cycle.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetPd(self, request, context):
        """This method is used to issue power delivery resets.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenTester(self, request, context):
        """This method is used to open the serial of the USB tester being used.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseTester(self, request, context):
        """This method is used to close the serial of the USB tester being used.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActivePort(self, request, context):
        """This method is used to get the active test port on the testing device.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetActivePort(self, request, context):
        """This method is used to set the active test port on the testing device.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadEdid(self, request, context):
        """This method is used to load an EDID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendVdmHpd(self, request, context):
        """This method is used send a VDM HPDs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SimulateKeyPress(self, request, context):
        """Simulate a key press. ATM this will simulate the "G" key press.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendPdAlert(self, request, context):
        """Send a PD alert message to partner.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPdStats(self, request, context):
        """Get statistics about the PD requests.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetPdStats(self, request, context):
        """Reset the PD statistics.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UsbTesterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTesters': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTesters,
                    request_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.GetTestersRequest.FromString,
                    response_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.GetTestersReply.SerializeToString,
            ),
            'GetTesterCapability': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTesterCapability,
                    request_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.GetUsbTesterCapabilityRequest.FromString,
                    response_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.GetUsbTesterCapabilityReply.SerializeToString,
            ),
            'SetTesterCapability': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTesterCapability,
                    request_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.SetUsbTesterCapabilityRequest.FromString,
                    response_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.SetUsbTesterCapabilityReply.SerializeToString,
            ),
            'GetDpInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDpInfo,
                    request_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.GetDpInfoRequest.FromString,
                    response_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.GetDpInfoReply.SerializeToString,
            ),
            'GetPdos': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPdos,
                    request_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.GetPdosRequest.FromString,
                    response_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.GetPdosReply.SerializeToString,
            ),
            'ReplugCable': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplugCable,
                    request_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.DoCableReplugRequest.FromString,
                    response_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.DoCableReplugReply.SerializeToString,
            ),
            'HardResetTester': grpc.unary_unary_rpc_method_handler(
                    servicer.HardResetTester,
                    request_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.HardResetTesterRequest.FromString,
                    response_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.HardResetTesterReply.SerializeToString,
            ),
            'ResetPd': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetPd,
                    request_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.ResetPdRequest.FromString,
                    response_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.ResetPdReply.SerializeToString,
            ),
            'OpenTester': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenTester,
                    request_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.OpenTesterRequest.FromString,
                    response_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.OpenTesterReply.SerializeToString,
            ),
            'CloseTester': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseTester,
                    request_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.CloseTesterRequest.FromString,
                    response_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.CloseTesterReply.SerializeToString,
            ),
            'GetActivePort': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActivePort,
                    request_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.GetActivePortRequest.FromString,
                    response_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.GetActivePortReply.SerializeToString,
            ),
            'SetActivePort': grpc.unary_unary_rpc_method_handler(
                    servicer.SetActivePort,
                    request_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.SetActivePortRequest.FromString,
                    response_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.SetActivePortReply.SerializeToString,
            ),
            'LoadEdid': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadEdid,
                    request_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.LoadEdidRequest.FromString,
                    response_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.LoadEdidReply.SerializeToString,
            ),
            'SendVdmHpd': grpc.unary_unary_rpc_method_handler(
                    servicer.SendVdmHpd,
                    request_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.SendVdmHpdRequest.FromString,
                    response_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.SendVdmHpdReply.SerializeToString,
            ),
            'SimulateKeyPress': grpc.unary_unary_rpc_method_handler(
                    servicer.SimulateKeyPress,
                    request_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.SimulateKeyPressRequest.FromString,
                    response_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.SimulateKeyPressReply.SerializeToString,
            ),
            'SendPdAlert': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPdAlert,
                    request_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.SendPdAlertRequest.FromString,
                    response_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.SendPdAlertReply.SerializeToString,
            ),
            'GetPdStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPdStats,
                    request_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.GetPdStatsRequest.FromString,
                    response_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.GetPdStatsReply.SerializeToString,
            ),
            'ResetPdStats': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetPdStats,
                    request_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.ResetPdStatsRequest.FromString,
                    response_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.ResetPdStatsReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chromiumos.test.lab.api.passport.UsbTesterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UsbTesterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTesters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chromiumos.test.lab.api.passport.UsbTesterService/GetTesters',
            chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.GetTestersRequest.SerializeToString,
            chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.GetTestersReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTesterCapability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chromiumos.test.lab.api.passport.UsbTesterService/GetTesterCapability',
            chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.GetUsbTesterCapabilityRequest.SerializeToString,
            chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.GetUsbTesterCapabilityReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetTesterCapability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chromiumos.test.lab.api.passport.UsbTesterService/SetTesterCapability',
            chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.SetUsbTesterCapabilityRequest.SerializeToString,
            chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.SetUsbTesterCapabilityReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDpInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chromiumos.test.lab.api.passport.UsbTesterService/GetDpInfo',
            chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.GetDpInfoRequest.SerializeToString,
            chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.GetDpInfoReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPdos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chromiumos.test.lab.api.passport.UsbTesterService/GetPdos',
            chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.GetPdosRequest.SerializeToString,
            chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.GetPdosReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReplugCable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chromiumos.test.lab.api.passport.UsbTesterService/ReplugCable',
            chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.DoCableReplugRequest.SerializeToString,
            chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.DoCableReplugReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HardResetTester(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chromiumos.test.lab.api.passport.UsbTesterService/HardResetTester',
            chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.HardResetTesterRequest.SerializeToString,
            chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.HardResetTesterReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResetPd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chromiumos.test.lab.api.passport.UsbTesterService/ResetPd',
            chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.ResetPdRequest.SerializeToString,
            chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.ResetPdReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OpenTester(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chromiumos.test.lab.api.passport.UsbTesterService/OpenTester',
            chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.OpenTesterRequest.SerializeToString,
            chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.OpenTesterReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CloseTester(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chromiumos.test.lab.api.passport.UsbTesterService/CloseTester',
            chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.CloseTesterRequest.SerializeToString,
            chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.CloseTesterReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetActivePort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chromiumos.test.lab.api.passport.UsbTesterService/GetActivePort',
            chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.GetActivePortRequest.SerializeToString,
            chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.GetActivePortReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetActivePort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chromiumos.test.lab.api.passport.UsbTesterService/SetActivePort',
            chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.SetActivePortRequest.SerializeToString,
            chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.SetActivePortReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LoadEdid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chromiumos.test.lab.api.passport.UsbTesterService/LoadEdid',
            chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.LoadEdidRequest.SerializeToString,
            chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.LoadEdidReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendVdmHpd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chromiumos.test.lab.api.passport.UsbTesterService/SendVdmHpd',
            chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.SendVdmHpdRequest.SerializeToString,
            chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.SendVdmHpdReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SimulateKeyPress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chromiumos.test.lab.api.passport.UsbTesterService/SimulateKeyPress',
            chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.SimulateKeyPressRequest.SerializeToString,
            chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.SimulateKeyPressReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendPdAlert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chromiumos.test.lab.api.passport.UsbTesterService/SendPdAlert',
            chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.SendPdAlertRequest.SerializeToString,
            chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.SendPdAlertReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPdStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chromiumos.test.lab.api.passport.UsbTesterService/GetPdStats',
            chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.GetPdStatsRequest.SerializeToString,
            chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.GetPdStatsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResetPdStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chromiumos.test.lab.api.passport.UsbTesterService/ResetPdStats',
            chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.ResetPdStatsRequest.SerializeToString,
            chromiumos_dot_test_dot_lab_dot_api_dot_passport_dot_usb__tester__service__pb2.ResetPdStatsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
