load("@org_tensorflow//tensorflow/lite:build_def.bzl", "tflite_copts")
load("@org_tensorflow//tensorflow/lite/core/shims:cc_library_with_tflite.bzl", "cc_library_with_tflite")

package(
    default_visibility = [
        "//visibility:public",
    ],
    licenses = ["notice"],
)

cc_library_with_tflite(
    name = "operations_base",
    srcs = [
        "operations_base.cc",
        "src/add.cc",
        "src/average_pool_2d.cc",
        "src/concat.cc",
        "src/conv_2d.cc",
        "src/depthwise_conv_2d.cc",
        "src/dequantize.cc",
        "src/hardswish.cc",
        "src/logistic.cc",
        "src/max_pool_2d.cc",
        "src/mean.cc",
        "src/mul.cc",
        "src/pad.cc",
        "src/prelu.cc",
        "src/relu.cc",
        "src/relu6.cc",
        "src/reshape.cc",
        "src/resize_bilinear.cc",
        "src/softmax.cc",
        "src/sub.cc",
        "src/tanh.cc",
        "src/transpose_conv.cc",
    ],
    hdrs = [
        "include/add.h",
        "include/average_pool_2d.h",
        "include/concat.h",
        "include/conv_2d.h",
        "include/depthwise_conv_2d.h",
        "include/dequantize.h",
        "include/hardswish.h",
        "include/logistic.h",
        "include/max_pool_2d.h",
        "include/mean.h",
        "include/mul.h",
        "include/pad.h",
        "include/prelu.h",
        "include/relu.h",
        "include/relu6.h",
        "include/reshape.h",
        "include/resize_bilinear.h",
        "include/softmax.h",
        "include/sub.h",
        "include/tanh.h",
        "include/transpose_conv.h",
        "openvino_node_manager.h",
        "operations_base.h",
        "utility.h",
    ],
    copts = tflite_copts(),
    visibility = ["//delegate/intel_openvino:__subpackages__"],
    deps = [
        "//delegate/intel_openvino:log",
        "@intel_openvino//:openvino",
        "@org_tensorflow//tensorflow/lite:kernel_api",
        "@org_tensorflow//tensorflow/lite:util",
        "@org_tensorflow//tensorflow/lite/c:c_api",
        "@org_tensorflow//tensorflow/lite/c:c_api_experimental",
        "@org_tensorflow//tensorflow/lite/c:c_api_types",
        "@org_tensorflow//tensorflow/lite/c:common",
        "@org_tensorflow//tensorflow/lite/kernels:kernel_util",
        "@org_tensorflow//tensorflow/lite/kernels:padding",
        "@org_tensorflow//tensorflow/lite/kernels/internal:optimized_base",
        "@org_tensorflow//tensorflow/lite/kernels/internal:tensor",
        "@org_tensorflow//tensorflow/lite/kernels/internal:types",
    ],
)
