#!/bin/bash
# Copyright (c) 2012 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

FILE_PATH=`readlink -f $0`
INSTALL_DIR=`dirname $FILE_PATH`
SRC_DIR=`readlink -f $INSTALL_DIR/../`

TESTS_DIR=$INSTALL_DIR/tests
FRAMEWORK_DIR=$INSTALL_DIR/framework

PYTHONPATH=$FRAMEWORK_DIR TESTS_DIR=$TESTS_DIR \
    SRC_DIR=$SRC_DIR python $FRAMEWORK_DIR/main.py $*
