[package]
name = "stm32g0_i2c_peripheral"
version = "0.1.0"
edition = "2021"
authors = ["Google"]
license = "BSD-3-Clause"

[dependencies]
hal = { package = "stm32g0xx-hal", version = "0.1.0" }
i2c_peripheral = { path = "../../i2c_peripheral" }
stm32g0 = "0.13.0"
nb = "1.0.0"

[features]
default = [
    "stm32g071"
]
stm32g031 = ["hal/stm32g031"]
stm32g071 = ["hal/stm32g071"]
