# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/test/api/firmware_provision.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromiumos.build.api import firmware_config_pb2 as chromiumos_dot_build_dot_api_dot_firmware__config__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='chromiumos/test/api/firmware_provision.proto',
  package='chromiumos.test.api',
  syntax='proto3',
  serialized_options=b'Z-go.chromium.org/chromiumos/config/go/test/api',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n,chromiumos/test/api/firmware_provision.proto\x12\x13\x63hromiumos.test.api\x1a*chromiumos/build/api/firmware_config.proto\">\n FirmwareProvisionStartupMetadataJ\x04\x08\x01\x10\x02R\x14\x63\x61\x63he_server_address\"\x91\x02\n FirmwareProvisionInstallMetadata\x12=\n\x0f\x66irmware_config\x18\x01 \x01(\x0b\x32$.chromiumos.build.api.FirmwareConfig\x12Q\n\x02os\x18\x02 \x01(\x0e\x32\x45.chromiumos.test.api.FirmwareProvisionInstallMetadata.OperatingSystem\x12 \n\x18\x66orce_flash_same_version\x18\x03 \x01(\x08\"9\n\x0fOperatingSystem\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08\x43HROMEOS\x10\x01\x12\x0b\n\x07\x41NDROID\x10\x02\"\x92\x01\n\x19\x46irmwareProvisionResponse\x12\x19\n\rerror_message\x18\x01 \x01(\tB\x02\x18\x01\x12\x15\n\rap_ro_version\x18\x02 \x01(\t\x12\x15\n\rap_rw_version\x18\x03 \x01(\t\x12\x15\n\rec_ro_version\x18\x04 \x01(\t\x12\x15\n\rec_rw_version\x18\x05 \x01(\tB/Z-go.chromium.org/chromiumos/config/go/test/apib\x06proto3'
  ,
  dependencies=[chromiumos_dot_build_dot_api_dot_firmware__config__pb2.DESCRIPTOR,])



_FIRMWAREPROVISIONINSTALLMETADATA_OPERATINGSYSTEM = _descriptor.EnumDescriptor(
  name='OperatingSystem',
  full_name='chromiumos.test.api.FirmwareProvisionInstallMetadata.OperatingSystem',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CHROMEOS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ANDROID', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=394,
  serialized_end=451,
)
_sym_db.RegisterEnumDescriptor(_FIRMWAREPROVISIONINSTALLMETADATA_OPERATINGSYSTEM)


_FIRMWAREPROVISIONSTARTUPMETADATA = _descriptor.Descriptor(
  name='FirmwareProvisionStartupMetadata',
  full_name='chromiumos.test.api.FirmwareProvisionStartupMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=175,
)


_FIRMWAREPROVISIONINSTALLMETADATA = _descriptor.Descriptor(
  name='FirmwareProvisionInstallMetadata',
  full_name='chromiumos.test.api.FirmwareProvisionInstallMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='firmware_config', full_name='chromiumos.test.api.FirmwareProvisionInstallMetadata.firmware_config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='os', full_name='chromiumos.test.api.FirmwareProvisionInstallMetadata.os', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='force_flash_same_version', full_name='chromiumos.test.api.FirmwareProvisionInstallMetadata.force_flash_same_version', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FIRMWAREPROVISIONINSTALLMETADATA_OPERATINGSYSTEM,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=451,
)


_FIRMWAREPROVISIONRESPONSE = _descriptor.Descriptor(
  name='FirmwareProvisionResponse',
  full_name='chromiumos.test.api.FirmwareProvisionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_message', full_name='chromiumos.test.api.FirmwareProvisionResponse.error_message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\030\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ap_ro_version', full_name='chromiumos.test.api.FirmwareProvisionResponse.ap_ro_version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ap_rw_version', full_name='chromiumos.test.api.FirmwareProvisionResponse.ap_rw_version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ec_ro_version', full_name='chromiumos.test.api.FirmwareProvisionResponse.ec_ro_version', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ec_rw_version', full_name='chromiumos.test.api.FirmwareProvisionResponse.ec_rw_version', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=454,
  serialized_end=600,
)

_FIRMWAREPROVISIONINSTALLMETADATA.fields_by_name['firmware_config'].message_type = chromiumos_dot_build_dot_api_dot_firmware__config__pb2._FIRMWARECONFIG
_FIRMWAREPROVISIONINSTALLMETADATA.fields_by_name['os'].enum_type = _FIRMWAREPROVISIONINSTALLMETADATA_OPERATINGSYSTEM
_FIRMWAREPROVISIONINSTALLMETADATA_OPERATINGSYSTEM.containing_type = _FIRMWAREPROVISIONINSTALLMETADATA
DESCRIPTOR.message_types_by_name['FirmwareProvisionStartupMetadata'] = _FIRMWAREPROVISIONSTARTUPMETADATA
DESCRIPTOR.message_types_by_name['FirmwareProvisionInstallMetadata'] = _FIRMWAREPROVISIONINSTALLMETADATA
DESCRIPTOR.message_types_by_name['FirmwareProvisionResponse'] = _FIRMWAREPROVISIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FirmwareProvisionStartupMetadata = _reflection.GeneratedProtocolMessageType('FirmwareProvisionStartupMetadata', (_message.Message,), {
  'DESCRIPTOR' : _FIRMWAREPROVISIONSTARTUPMETADATA,
  '__module__' : 'chromiumos.test.api.firmware_provision_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.FirmwareProvisionStartupMetadata)
  })
_sym_db.RegisterMessage(FirmwareProvisionStartupMetadata)

FirmwareProvisionInstallMetadata = _reflection.GeneratedProtocolMessageType('FirmwareProvisionInstallMetadata', (_message.Message,), {
  'DESCRIPTOR' : _FIRMWAREPROVISIONINSTALLMETADATA,
  '__module__' : 'chromiumos.test.api.firmware_provision_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.FirmwareProvisionInstallMetadata)
  })
_sym_db.RegisterMessage(FirmwareProvisionInstallMetadata)

FirmwareProvisionResponse = _reflection.GeneratedProtocolMessageType('FirmwareProvisionResponse', (_message.Message,), {
  'DESCRIPTOR' : _FIRMWAREPROVISIONRESPONSE,
  '__module__' : 'chromiumos.test.api.firmware_provision_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.FirmwareProvisionResponse)
  })
_sym_db.RegisterMessage(FirmwareProvisionResponse)


DESCRIPTOR._options = None
_FIRMWAREPROVISIONRESPONSE.fields_by_name['error_message']._options = None
# @@protoc_insertion_point(module_scope)
