# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from chromiumos.test.api import suite_history_service_pb2 as chromiumos_dot_test_dot_api_dot_suite__history__service__pb2


class SuiteHistoryServiceStub(object):
    """SuiteHistoryService provides historical test execution metrics.
    This is used by the suite-history-filter to dynamically calculate
    execution deadlines and prevent timeout-doomed tasks from being scheduled.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDuration = channel.unary_unary(
                '/chromiumos.test.api.SuiteHistoryService/GetDuration',
                request_serializer=chromiumos_dot_test_dot_api_dot_suite__history__service__pb2.GetDurationRequest.SerializeToString,
                response_deserializer=chromiumos_dot_test_dot_api_dot_suite__history__service__pb2.GetDurationResponse.FromString,
                )


class SuiteHistoryServiceServicer(object):
    """SuiteHistoryService provides historical test execution metrics.
    This is used by the suite-history-filter to dynamically calculate
    execution deadlines and prevent timeout-doomed tasks from being scheduled.
    """

    def GetDuration(self, request, context):
        """Returns the historical execution duration for a specific test configuration.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SuiteHistoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDuration': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDuration,
                    request_deserializer=chromiumos_dot_test_dot_api_dot_suite__history__service__pb2.GetDurationRequest.FromString,
                    response_serializer=chromiumos_dot_test_dot_api_dot_suite__history__service__pb2.GetDurationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chromiumos.test.api.SuiteHistoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SuiteHistoryService(object):
    """SuiteHistoryService provides historical test execution metrics.
    This is used by the suite-history-filter to dynamically calculate
    execution deadlines and prevent timeout-doomed tasks from being scheduled.
    """

    @staticmethod
    def GetDuration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chromiumos.test.api.SuiteHistoryService/GetDuration',
            chromiumos_dot_test_dot_api_dot_suite__history__service__pb2.GetDurationRequest.SerializeToString,
            chromiumos_dot_test_dot_api_dot_suite__history__service__pb2.GetDurationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
