[package]
name = "hps-util"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"

[dependencies]
anyhow = "1.0.38"
clap = { version = "3.1.0", features = ["derive"] }
embedded-hal = "0.2.4"
fpga_app = { path = "../fpga_app" }
gpio-cdev = "0.5.1"
hps_interface = { path = "../hps_interface" }
host_dev_common = { path = "../host_dev_common" }
interrupt_proxy = { path = "../interrupt_proxy" }
linux-embedded-hal = "0.3.1"
mcp2221 = { path = "../mcp2221", optional = true }
mcu_common = { path = "../mcu_common", features = [ "dev" ] }

[features]
default = [ "mcp2221" ]
