#!/usr/bin/env python3
# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "diagnoseme_rpcserver"
version = "0.0.1"
description = "DiagnoseMe RpcServer"
requires-python = ">=3.11"

[project.scripts]
rpcserver = "server.rpcserver:run_service"
