# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openos/test/api/test_harness_metadata.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromite.api.gen_sdk.openos.test.api import test_case_metadata_pb2 as openos_dot_test_dot_api_dot_test__case__metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/openos/test/api/test_harness_metadata.proto\x12\x13\x63hromiumos.test.api\x1a,openos/test/api/test_case_metadata.proto\"\xcf\x01\n\x13TestHarnessMetadata\x12N\n\rtast_metadata\x18\x01 \x01(\x0b\x32\x35.openos.test.api.TestHarnessMetadata.TastMetadataH\x00\x1aW\n\x0cTastMetadata\x12G\n\x15tast_fixture_metadata\x18\x01 \x03(\x0b\x32(.openos.test.api.TastFixtureMetadataB\x0f\n\rmetadata_type\"\xaf\x01\n\x13TastFixtureMetadata\x12\n\n\x02id\x18\x01 \x01(\t\x12,\n\x06owners\x18\x02 \x03(\x0b\x32\x1c.openos.test.api.Contact\x12\x38\n\rbug_component\x18\x03 \x01(\x0b\x32!.openos.test.api.BugComponent\x12\x14\n\x0cpath_to_file\x18\x04 \x01(\t\x12\x0e\n\x06parent\x18\x05 \x01(\t\"S\n\x17TestHarnessMetadataList\x12\x38\n\x06values\x18\x01 \x03(\x0b\x32(.openos.test.api.TestHarnessMetadataB/Z-go.chromium.org/openos/config/go/test/apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openos.test.api.test_harness_metadata_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z-go.chromium.org/openos/config/go/test/api'
  _globals['_TESTHARNESSMETADATA']._serialized_start=119
  _globals['_TESTHARNESSMETADATA']._serialized_end=326
  _globals['_TESTHARNESSMETADATA_TASTMETADATA']._serialized_start=222
  _globals['_TESTHARNESSMETADATA_TASTMETADATA']._serialized_end=309
  _globals['_TASTFIXTUREMETADATA']._serialized_start=329
  _globals['_TASTFIXTUREMETADATA']._serialized_end=504
  _globals['_TESTHARNESSMETADATALIST']._serialized_start=506
  _globals['_TESTHARNESSMETADATALIST']._serialized_end=589
# @@protoc_insertion_point(module_scope)
