# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "public_replication_proto",
    srcs = ["public_replication.proto"],
    visibility = ["//visibility:public"],
    deps = ["@com_google_protobuf//:field_mask_proto"],
)

go_proto_library(
    name = "public_replication_go_proto",
    importpath = "go.chromium.org/chromiumos/config/go/public_replication",
    proto = ":public_replication_proto",
    visibility = ["//visibility:public"],
)

go_library(
    name = "public_replication",
    embed = [":public_replication_go_proto"],
    importpath = "go.chromium.org/chromiumos/config/go/public_replication",
    visibility = ["//visibility:public"],
)
