# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "results_proto",
    srcs = [
        "machine.proto",
        "machine_id.proto",
        "package.proto",
        "result.proto",
        "result_id.proto",
        "software_config.proto",
        "software_config_id.proto",
        "software_overrides_config.proto",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//chromiumos/config/api/test/results/graphics/v1:graphics_proto",
        "@com_google_protobuf//:timestamp_proto",
    ],
)

go_proto_library(
    name = "results_go_proto",
    importpath = "go.chromium.org/chromiumos/config/go/api/test/results/v1",
    proto = ":results_proto",
    visibility = ["//visibility:public"],
    deps = ["//chromiumos/config/api/test/results/graphics/v1:graphics"],
)

go_library(
    name = "results",
    embed = [":results_go_proto"],
    importpath = "go.chromium.org/chromiumos/config/go/api/test/results/v1",
    visibility = ["//visibility:public"],
)
