// Copyright 2020 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package chromiumos.config.api.test.results.v1;

option go_package = "go.chromium.org/chromiumos/config/go/api/test/results/v1;results";

import "chromiumos/config/api/test/results/v1/package.proto";

// Software overridden from the normal system software.
// Next Tag: 2
message SoftwareOverridesConfig {
  // Packages that were explicitly overridden from the normal system software.
  repeated Package packages = 1;
}
