// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.1.0
// - protoc             v3.17.1
// source: chromiumos/test/lab/api/inventory_service.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InventoryServiceClient is the client API for InventoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InventoryServiceClient interface {
	// Returns the device wiring topology, including all peripherals attached to
	// the device and peer devices that are used in the test setup.
	GetDutTopology(ctx context.Context, in *GetDutTopologyRequest, opts ...grpc.CallOption) (InventoryService_GetDutTopologyClient, error)
	// GetStableVersion fetches the stable version for a given device.
	// It checks for a local stable version file first (e.g., on Satlab).
	// If no local file exists, it queries the central stable version service (e.g., crosskylabadmin).
	// Device details from the inventory are used to determine the correct version.
	GetStableVersion(ctx context.Context, in *GetStableVersionRequest, opts ...grpc.CallOption) (*GetStableVersionResponse, error)
}

type inventoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryServiceClient(cc grpc.ClientConnInterface) InventoryServiceClient {
	return &inventoryServiceClient{cc}
}

func (c *inventoryServiceClient) GetDutTopology(ctx context.Context, in *GetDutTopologyRequest, opts ...grpc.CallOption) (InventoryService_GetDutTopologyClient, error) {
	stream, err := c.cc.NewStream(ctx, &InventoryService_ServiceDesc.Streams[0], "/chromiumos.test.lab.api.InventoryService/GetDutTopology", opts...)
	if err != nil {
		return nil, err
	}
	x := &inventoryServiceGetDutTopologyClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type InventoryService_GetDutTopologyClient interface {
	Recv() (*GetDutTopologyResponse, error)
	grpc.ClientStream
}

type inventoryServiceGetDutTopologyClient struct {
	grpc.ClientStream
}

func (x *inventoryServiceGetDutTopologyClient) Recv() (*GetDutTopologyResponse, error) {
	m := new(GetDutTopologyResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *inventoryServiceClient) GetStableVersion(ctx context.Context, in *GetStableVersionRequest, opts ...grpc.CallOption) (*GetStableVersionResponse, error) {
	out := new(GetStableVersionResponse)
	err := c.cc.Invoke(ctx, "/chromiumos.test.lab.api.InventoryService/GetStableVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryServiceServer is the server API for InventoryService service.
// All implementations should embed UnimplementedInventoryServiceServer
// for forward compatibility
type InventoryServiceServer interface {
	// Returns the device wiring topology, including all peripherals attached to
	// the device and peer devices that are used in the test setup.
	GetDutTopology(*GetDutTopologyRequest, InventoryService_GetDutTopologyServer) error
	// GetStableVersion fetches the stable version for a given device.
	// It checks for a local stable version file first (e.g., on Satlab).
	// If no local file exists, it queries the central stable version service (e.g., crosskylabadmin).
	// Device details from the inventory are used to determine the correct version.
	GetStableVersion(context.Context, *GetStableVersionRequest) (*GetStableVersionResponse, error)
}

// UnimplementedInventoryServiceServer should be embedded to have forward compatible implementations.
type UnimplementedInventoryServiceServer struct {
}

func (UnimplementedInventoryServiceServer) GetDutTopology(*GetDutTopologyRequest, InventoryService_GetDutTopologyServer) error {
	return status.Errorf(codes.Unimplemented, "method GetDutTopology not implemented")
}
func (UnimplementedInventoryServiceServer) GetStableVersion(context.Context, *GetStableVersionRequest) (*GetStableVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStableVersion not implemented")
}

// UnsafeInventoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryServiceServer will
// result in compilation errors.
type UnsafeInventoryServiceServer interface {
	mustEmbedUnimplementedInventoryServiceServer()
}

func RegisterInventoryServiceServer(s grpc.ServiceRegistrar, srv InventoryServiceServer) {
	s.RegisterService(&InventoryService_ServiceDesc, srv)
}

func _InventoryService_GetDutTopology_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetDutTopologyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InventoryServiceServer).GetDutTopology(m, &inventoryServiceGetDutTopologyServer{stream})
}

type InventoryService_GetDutTopologyServer interface {
	Send(*GetDutTopologyResponse) error
	grpc.ServerStream
}

type inventoryServiceGetDutTopologyServer struct {
	grpc.ServerStream
}

func (x *inventoryServiceGetDutTopologyServer) Send(m *GetDutTopologyResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _InventoryService_GetStableVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStableVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetStableVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chromiumos.test.lab.api.InventoryService/GetStableVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetStableVersion(ctx, req.(*GetStableVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryService_ServiceDesc is the grpc.ServiceDesc for InventoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chromiumos.test.lab.api.InventoryService",
	HandlerType: (*InventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStableVersion",
			Handler:    _InventoryService_GetStableVersion_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetDutTopology",
			Handler:       _InventoryService_GetDutTopology_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "chromiumos/test/lab/api/inventory_service.proto",
}
