# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "pinweaver_srcs",
    srcs = [
        ":pinweaver.c",
    ],
)

filegroup(
    name = "pinweaver_api",
    srcs = [
        ":pinweaver.h",
    ],
)

filegroup(
    name = "pinweaver_hdrs",
    srcs = [
        ":pinweaver_api",
        ":pinweaver_eal.h",
        ":pinweaver_types.h",
    ],
)
