# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.


######################################################################
# Prepare base container
FROM debian:bookworm-slim AS downloader

RUN apt update && apt upgrade -y && apt install -y --no-install-recommends \
  ca-certificates \
  ccache \
  cmake \
  device-tree-compiler \
  dfu-util \
  file \
  g++-multilib \
  gcc \
  gcc-multilib \
  git \
  gperf \
  libc6-i386 \
  make \
  ninja-build \
  python3-dev \
  python3-pip \
  python3-pyelftools \
  python3-setuptools \
  python3-tk \
  python3-wheel \
  udev \
  wget \
  xz-utils \
  && apt clean

# There are other packages required for Zephyr tooling, e.g. twister, best to install them now
COPY dockerfiles/requirements.compiled .
RUN pip install --break-system-packages --require-hashes -r requirements.compiled

######################################################################
# Prepare Zephyr SDK
FROM downloader AS zephyr-sdk
ARG ZEPHYR_VERSION=0.16.8

RUN wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v${ZEPHYR_VERSION}/zephyr-sdk-${ZEPHYR_VERSION}_linux-x86_64.tar.xz -O /tmp/zephyr.tar.xz &&\
  tar xvf /tmp/zephyr.tar.xz -C /usr/local &&\
  /usr/local/zephyr-sdk-${ZEPHYR_VERSION}/setup.sh -h -c &&\
  rm /tmp/zephyr.tar.xz &&\
  cd /usr/local/zephyr-sdk-${ZEPHYR_VERSION} &&\
  rm -rf xtensa* arc* aarch* micro* mips* nios2* riscv* sparc*

######################################################################
# Prepare Zephyr repository
FROM downloader AS zephyr-repo

RUN mkdir /zephyr
WORKDIR /zephyr
RUN git clone -b mspm0_dev_stable https://github.com/msp-ti/zephyr.git

WORKDIR /zephyr/zephyr
RUN git checkout 51ee856187cd0f5350af54b1d0b9ab4cf2ce154b
RUN west init -l && west update hal_ti cmsis &&\
  chmod +x /zephyr/zephyr/zephyr-env.sh &&\
  chmod o+w /zephyr/.west/config

######################################################################
# Copy artifacts from previous stages
FROM downloader AS builder

COPY --from=zephyr-sdk /usr/local/ /usr/local/
COPY --from=zephyr-repo /zephyr /zephyr

######################################################################
# Prepare scripts to build firmware
COPY tools/formatconverter/converter.py /usr/local/bin/converter.py
COPY tools/imgtool/ /usr/local/imgtool/
COPY dockerfiles/firmware_build.sh /firmware_build.sh

RUN chmod 777 /usr/local/bin/converter.py
RUN chmod -R 777 /usr/local/imgtool
RUN chmod 777 /firmware_build.sh
RUN ln -s /tmp /zephyr/zephyr/.cache

WORKDIR /tmp
VOLUME /repo
ENTRYPOINT ["/bin/bash", "/firmware_build.sh"]
