[package]
name = "hps_interface"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"

[dependencies]
anyhow = "1.0.38"
embedded-hal = "0.2.4"
gpio-cdev = "0.5.1"
mcu_common = { path = "../mcu_common", features = [ "std" ] }

[dev-dependencies]
fake_i2c = { path = "../fake_i2c" }
i2c_protocol = { path = "../i2c_protocol" }
