# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""
Configuration file to store memory layout of Dolos board.
"""

KB = 1024
PAD_VALUE = 0xFF.to_bytes(1, "little")

FLASH_TOTAL_SIZE = 128 * KB
RO_PARTITION_SIZE = 128
FIRMWARE_TRAILER_SIZE = 64
RO_RECORD_SIZE = 32
BOOT_PARTITION_SIZE = 18 * KB - RO_PARTITION_SIZE
RO_PARTITION_START_ADDR = BOOT_PARTITION_SIZE
FIRMWARE_PARTITION_START_ADDR = RO_PARTITION_START_ADDR + RO_PARTITION_SIZE
FIRMWARE_PARTITION_SIZE = (
    FLASH_TOTAL_SIZE - FIRMWARE_PARTITION_START_ADDR - FIRMWARE_TRAILER_SIZE
)
FIRMWARE_TRAILER_START_ADDR = FIRMWARE_PARTITION_START_ADDR + FIRMWARE_PARTITION_SIZE
