# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from chromiumos.test.lab.api import dut_action_service_pb2 as chromiumos_dot_test_dot_lab_dot_api_dot_dut__action__service__pb2


class DutActionServiceStub(object):
    """Service to perform actions on DUTs and their peripherals.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetRpmPowerState = channel.unary_unary(
                '/chromiumos.test.lab.api.DutActionService/SetRpmPowerState',
                request_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_dut__action__service__pb2.SetRpmPowerStateRequest.SerializeToString,
                response_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_dut__action__service__pb2.SetRpmPowerStateResponse.FromString,
                )


class DutActionServiceServicer(object):
    """Service to perform actions on DUTs and their peripherals.
    """

    def SetRpmPowerState(self, request, context):
        """Set the power state of an RPM outlet.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DutActionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetRpmPowerState': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRpmPowerState,
                    request_deserializer=chromiumos_dot_test_dot_lab_dot_api_dot_dut__action__service__pb2.SetRpmPowerStateRequest.FromString,
                    response_serializer=chromiumos_dot_test_dot_lab_dot_api_dot_dut__action__service__pb2.SetRpmPowerStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chromiumos.test.lab.api.DutActionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DutActionService(object):
    """Service to perform actions on DUTs and their peripherals.
    """

    @staticmethod
    def SetRpmPowerState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chromiumos.test.lab.api.DutActionService/SetRpmPowerState',
            chromiumos_dot_test_dot_lab_dot_api_dot_dut__action__service__pb2.SetRpmPowerStateRequest.SerializeToString,
            chromiumos_dot_test_dot_lab_dot_api_dot_dut__action__service__pb2.SetRpmPowerStateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
