// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.1.0
// - protoc             v3.17.1
// source: chromiumos/test/api/chameleon_lib_service.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChameleonLibServiceClient is the client API for ChameleonLibService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChameleonLibServiceClient interface {
	// Verifies the connection/status of the chameleon device
	CheckChameleonHealth(ctx context.Context, in *CheckChameleonHealthRequest, opts ...grpc.CallOption) (ChameleonLibService_CheckChameleonHealthClient, error)
}

type chameleonLibServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChameleonLibServiceClient(cc grpc.ClientConnInterface) ChameleonLibServiceClient {
	return &chameleonLibServiceClient{cc}
}

func (c *chameleonLibServiceClient) CheckChameleonHealth(ctx context.Context, in *CheckChameleonHealthRequest, opts ...grpc.CallOption) (ChameleonLibService_CheckChameleonHealthClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChameleonLibService_ServiceDesc.Streams[0], "/chromiumos.test.api.ChameleonLibService/CheckChameleonHealth", opts...)
	if err != nil {
		return nil, err
	}
	x := &chameleonLibServiceCheckChameleonHealthClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChameleonLibService_CheckChameleonHealthClient interface {
	Recv() (*CheckChameleonHealthResponse, error)
	grpc.ClientStream
}

type chameleonLibServiceCheckChameleonHealthClient struct {
	grpc.ClientStream
}

func (x *chameleonLibServiceCheckChameleonHealthClient) Recv() (*CheckChameleonHealthResponse, error) {
	m := new(CheckChameleonHealthResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChameleonLibServiceServer is the server API for ChameleonLibService service.
// All implementations should embed UnimplementedChameleonLibServiceServer
// for forward compatibility
type ChameleonLibServiceServer interface {
	// Verifies the connection/status of the chameleon device
	CheckChameleonHealth(*CheckChameleonHealthRequest, ChameleonLibService_CheckChameleonHealthServer) error
}

// UnimplementedChameleonLibServiceServer should be embedded to have forward compatible implementations.
type UnimplementedChameleonLibServiceServer struct {
}

func (UnimplementedChameleonLibServiceServer) CheckChameleonHealth(*CheckChameleonHealthRequest, ChameleonLibService_CheckChameleonHealthServer) error {
	return status.Errorf(codes.Unimplemented, "method CheckChameleonHealth not implemented")
}

// UnsafeChameleonLibServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChameleonLibServiceServer will
// result in compilation errors.
type UnsafeChameleonLibServiceServer interface {
	mustEmbedUnimplementedChameleonLibServiceServer()
}

func RegisterChameleonLibServiceServer(s grpc.ServiceRegistrar, srv ChameleonLibServiceServer) {
	s.RegisterService(&ChameleonLibService_ServiceDesc, srv)
}

func _ChameleonLibService_CheckChameleonHealth_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CheckChameleonHealthRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChameleonLibServiceServer).CheckChameleonHealth(m, &chameleonLibServiceCheckChameleonHealthServer{stream})
}

type ChameleonLibService_CheckChameleonHealthServer interface {
	Send(*CheckChameleonHealthResponse) error
	grpc.ServerStream
}

type chameleonLibServiceCheckChameleonHealthServer struct {
	grpc.ServerStream
}

func (x *chameleonLibServiceCheckChameleonHealthServer) Send(m *CheckChameleonHealthResponse) error {
	return x.ServerStream.SendMsg(m)
}

// ChameleonLibService_ServiceDesc is the grpc.ServiceDesc for ChameleonLibService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChameleonLibService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chromiumos.test.api.ChameleonLibService",
	HandlerType: (*ChameleonLibServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CheckChameleonHealth",
			Handler:       _ChameleonLibService_CheckChameleonHealth_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "chromiumos/test/api/chameleon_lib_service.proto",
}
