// Copyright 2024 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.1
// source: chromiumos/test/api/trv2_dynamic_updates.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TaskType defines which task type is being targeted.
type FocalTaskFinder_TaskType int32

const (
	FocalTaskFinder_PROVISION FocalTaskFinder_TaskType = 0
	FocalTaskFinder_PRETEST   FocalTaskFinder_TaskType = 1
	FocalTaskFinder_TEST      FocalTaskFinder_TaskType = 2
	FocalTaskFinder_POSTTEST  FocalTaskFinder_TaskType = 3
	FocalTaskFinder_PUBLISH   FocalTaskFinder_TaskType = 4
	FocalTaskFinder_GENERIC   FocalTaskFinder_TaskType = 5
)

// Enum value maps for FocalTaskFinder_TaskType.
var (
	FocalTaskFinder_TaskType_name = map[int32]string{
		0: "PROVISION",
		1: "PRETEST",
		2: "TEST",
		3: "POSTTEST",
		4: "PUBLISH",
		5: "GENERIC",
	}
	FocalTaskFinder_TaskType_value = map[string]int32{
		"PROVISION": 0,
		"PRETEST":   1,
		"TEST":      2,
		"POSTTEST":  3,
		"PUBLISH":   4,
		"GENERIC":   5,
	}
)

func (x FocalTaskFinder_TaskType) Enum() *FocalTaskFinder_TaskType {
	p := new(FocalTaskFinder_TaskType)
	*p = x
	return p
}

func (x FocalTaskFinder_TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FocalTaskFinder_TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_chromiumos_test_api_trv2_dynamic_updates_proto_enumTypes[0].Descriptor()
}

func (FocalTaskFinder_TaskType) Type() protoreflect.EnumType {
	return &file_chromiumos_test_api_trv2_dynamic_updates_proto_enumTypes[0]
}

func (x FocalTaskFinder_TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FocalTaskFinder_TaskType.Descriptor instead.
func (FocalTaskFinder_TaskType) EnumDescriptor() ([]byte, []int) {
	return file_chromiumos_test_api_trv2_dynamic_updates_proto_rawDescGZIP(), []int{1, 0}
}

// InsertType describes how the task should be placed within
// ordered task list around the focal task.
type UpdateAction_Insert_InsertType int32

const (
	UpdateAction_Insert_APPEND  UpdateAction_Insert_InsertType = 0
	UpdateAction_Insert_PREPEND UpdateAction_Insert_InsertType = 1
	UpdateAction_Insert_REPLACE UpdateAction_Insert_InsertType = 2
)

// Enum value maps for UpdateAction_Insert_InsertType.
var (
	UpdateAction_Insert_InsertType_name = map[int32]string{
		0: "APPEND",
		1: "PREPEND",
		2: "REPLACE",
	}
	UpdateAction_Insert_InsertType_value = map[string]int32{
		"APPEND":  0,
		"PREPEND": 1,
		"REPLACE": 2,
	}
)

func (x UpdateAction_Insert_InsertType) Enum() *UpdateAction_Insert_InsertType {
	p := new(UpdateAction_Insert_InsertType)
	*p = x
	return p
}

func (x UpdateAction_Insert_InsertType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateAction_Insert_InsertType) Descriptor() protoreflect.EnumDescriptor {
	return file_chromiumos_test_api_trv2_dynamic_updates_proto_enumTypes[1].Descriptor()
}

func (UpdateAction_Insert_InsertType) Type() protoreflect.EnumType {
	return &file_chromiumos_test_api_trv2_dynamic_updates_proto_enumTypes[1]
}

func (x UpdateAction_Insert_InsertType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateAction_Insert_InsertType.Descriptor instead.
func (UpdateAction_Insert_InsertType) EnumDescriptor() ([]byte, []int) {
	return file_chromiumos_test_api_trv2_dynamic_updates_proto_rawDescGZIP(), []int{2, 0, 0}
}

// UserDefinedDynamicUpdate is what updates a dynamic trv2 request.
type UserDefinedDynamicUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FocalTaskFinder *FocalTaskFinder `protobuf:"bytes,1,opt,name=focal_task_finder,json=focalTaskFinder,proto3" json:"focal_task_finder,omitempty"`
	UpdateAction    *UpdateAction    `protobuf:"bytes,2,opt,name=update_action,json=updateAction,proto3" json:"update_action,omitempty"`
}

func (x *UserDefinedDynamicUpdate) Reset() {
	*x = UserDefinedDynamicUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDefinedDynamicUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDefinedDynamicUpdate) ProtoMessage() {}

func (x *UserDefinedDynamicUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDefinedDynamicUpdate.ProtoReflect.Descriptor instead.
func (*UserDefinedDynamicUpdate) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_trv2_dynamic_updates_proto_rawDescGZIP(), []int{0}
}

func (x *UserDefinedDynamicUpdate) GetFocalTaskFinder() *FocalTaskFinder {
	if x != nil {
		return x.FocalTaskFinder
	}
	return nil
}

func (x *UserDefinedDynamicUpdate) GetUpdateAction() *UpdateAction {
	if x != nil {
		return x.UpdateAction
	}
	return nil
}

// FocalTaskFinder describes which task is the update based around.
type FocalTaskFinder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Finder:
	//	*FocalTaskFinder_First_
	//	*FocalTaskFinder_Last_
	//	*FocalTaskFinder_Beginning_
	//	*FocalTaskFinder_End_
	//	*FocalTaskFinder_ByDynamicIdentifier_
	Finder isFocalTaskFinder_Finder `protobuf_oneof:"finder"`
}

func (x *FocalTaskFinder) Reset() {
	*x = FocalTaskFinder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FocalTaskFinder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FocalTaskFinder) ProtoMessage() {}

func (x *FocalTaskFinder) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FocalTaskFinder.ProtoReflect.Descriptor instead.
func (*FocalTaskFinder) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_trv2_dynamic_updates_proto_rawDescGZIP(), []int{1}
}

func (m *FocalTaskFinder) GetFinder() isFocalTaskFinder_Finder {
	if m != nil {
		return m.Finder
	}
	return nil
}

func (x *FocalTaskFinder) GetFirst() *FocalTaskFinder_First {
	if x, ok := x.GetFinder().(*FocalTaskFinder_First_); ok {
		return x.First
	}
	return nil
}

func (x *FocalTaskFinder) GetLast() *FocalTaskFinder_Last {
	if x, ok := x.GetFinder().(*FocalTaskFinder_Last_); ok {
		return x.Last
	}
	return nil
}

func (x *FocalTaskFinder) GetBeginning() *FocalTaskFinder_Beginning {
	if x, ok := x.GetFinder().(*FocalTaskFinder_Beginning_); ok {
		return x.Beginning
	}
	return nil
}

func (x *FocalTaskFinder) GetEnd() *FocalTaskFinder_End {
	if x, ok := x.GetFinder().(*FocalTaskFinder_End_); ok {
		return x.End
	}
	return nil
}

func (x *FocalTaskFinder) GetByDynamicIdentifier() *FocalTaskFinder_ByDynamicIdentifier {
	if x, ok := x.GetFinder().(*FocalTaskFinder_ByDynamicIdentifier_); ok {
		return x.ByDynamicIdentifier
	}
	return nil
}

type isFocalTaskFinder_Finder interface {
	isFocalTaskFinder_Finder()
}

type FocalTaskFinder_First_ struct {
	First *FocalTaskFinder_First `protobuf:"bytes,1,opt,name=first,proto3,oneof"`
}

type FocalTaskFinder_Last_ struct {
	Last *FocalTaskFinder_Last `protobuf:"bytes,2,opt,name=last,proto3,oneof"`
}

type FocalTaskFinder_Beginning_ struct {
	Beginning *FocalTaskFinder_Beginning `protobuf:"bytes,3,opt,name=beginning,proto3,oneof"`
}

type FocalTaskFinder_End_ struct {
	End *FocalTaskFinder_End `protobuf:"bytes,4,opt,name=end,proto3,oneof"`
}

type FocalTaskFinder_ByDynamicIdentifier_ struct {
	ByDynamicIdentifier *FocalTaskFinder_ByDynamicIdentifier `protobuf:"bytes,5,opt,name=by_dynamic_identifier,json=byDynamicIdentifier,proto3,oneof"`
}

func (*FocalTaskFinder_First_) isFocalTaskFinder_Finder() {}

func (*FocalTaskFinder_Last_) isFocalTaskFinder_Finder() {}

func (*FocalTaskFinder_Beginning_) isFocalTaskFinder_Finder() {}

func (*FocalTaskFinder_End_) isFocalTaskFinder_Finder() {}

func (*FocalTaskFinder_ByDynamicIdentifier_) isFocalTaskFinder_Finder() {}

// UpdateAction describes what action will be taken around the focal task.
type UpdateAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Action:
	//	*UpdateAction_Insert_
	//	*UpdateAction_Remove_
	//	*UpdateAction_Modify_
	Action isUpdateAction_Action `protobuf_oneof:"action"`
}

func (x *UpdateAction) Reset() {
	*x = UpdateAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAction) ProtoMessage() {}

func (x *UpdateAction) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAction.ProtoReflect.Descriptor instead.
func (*UpdateAction) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_trv2_dynamic_updates_proto_rawDescGZIP(), []int{2}
}

func (m *UpdateAction) GetAction() isUpdateAction_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (x *UpdateAction) GetInsert() *UpdateAction_Insert {
	if x, ok := x.GetAction().(*UpdateAction_Insert_); ok {
		return x.Insert
	}
	return nil
}

func (x *UpdateAction) GetRemove() *UpdateAction_Remove {
	if x, ok := x.GetAction().(*UpdateAction_Remove_); ok {
		return x.Remove
	}
	return nil
}

func (x *UpdateAction) GetModify() *UpdateAction_Modify {
	if x, ok := x.GetAction().(*UpdateAction_Modify_); ok {
		return x.Modify
	}
	return nil
}

type isUpdateAction_Action interface {
	isUpdateAction_Action()
}

type UpdateAction_Insert_ struct {
	Insert *UpdateAction_Insert `protobuf:"bytes,1,opt,name=insert,proto3,oneof"`
}

type UpdateAction_Remove_ struct {
	Remove *UpdateAction_Remove `protobuf:"bytes,2,opt,name=remove,proto3,oneof"`
}

type UpdateAction_Modify_ struct {
	Modify *UpdateAction_Modify `protobuf:"bytes,3,opt,name=modify,proto3,oneof"`
}

func (*UpdateAction_Insert_) isUpdateAction_Action() {}

func (*UpdateAction_Remove_) isUpdateAction_Action() {}

func (*UpdateAction_Modify_) isUpdateAction_Action() {}

// First gives back the first task that is of the type provided.
type FocalTaskFinder_First struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskType FocalTaskFinder_TaskType `protobuf:"varint,1,opt,name=task_type,json=taskType,proto3,enum=chromiumos.test.api.FocalTaskFinder_TaskType" json:"task_type,omitempty"`
}

func (x *FocalTaskFinder_First) Reset() {
	*x = FocalTaskFinder_First{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FocalTaskFinder_First) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FocalTaskFinder_First) ProtoMessage() {}

func (x *FocalTaskFinder_First) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FocalTaskFinder_First.ProtoReflect.Descriptor instead.
func (*FocalTaskFinder_First) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_trv2_dynamic_updates_proto_rawDescGZIP(), []int{1, 0}
}

func (x *FocalTaskFinder_First) GetTaskType() FocalTaskFinder_TaskType {
	if x != nil {
		return x.TaskType
	}
	return FocalTaskFinder_PROVISION
}

// Last gives back the last task that is of the type provided.
type FocalTaskFinder_Last struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskType FocalTaskFinder_TaskType `protobuf:"varint,1,opt,name=task_type,json=taskType,proto3,enum=chromiumos.test.api.FocalTaskFinder_TaskType" json:"task_type,omitempty"`
}

func (x *FocalTaskFinder_Last) Reset() {
	*x = FocalTaskFinder_Last{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FocalTaskFinder_Last) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FocalTaskFinder_Last) ProtoMessage() {}

func (x *FocalTaskFinder_Last) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FocalTaskFinder_Last.ProtoReflect.Descriptor instead.
func (*FocalTaskFinder_Last) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_trv2_dynamic_updates_proto_rawDescGZIP(), []int{1, 1}
}

func (x *FocalTaskFinder_Last) GetTaskType() FocalTaskFinder_TaskType {
	if x != nil {
		return x.TaskType
	}
	return FocalTaskFinder_PROVISION
}

// Beginning always gives the first task in the list, ie the 0th index.
type FocalTaskFinder_Beginning struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FocalTaskFinder_Beginning) Reset() {
	*x = FocalTaskFinder_Beginning{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FocalTaskFinder_Beginning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FocalTaskFinder_Beginning) ProtoMessage() {}

func (x *FocalTaskFinder_Beginning) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FocalTaskFinder_Beginning.ProtoReflect.Descriptor instead.
func (*FocalTaskFinder_Beginning) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_trv2_dynamic_updates_proto_rawDescGZIP(), []int{1, 2}
}

// End always gives the last task in the list, ie the len(list)-1 index.
type FocalTaskFinder_End struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FocalTaskFinder_End) Reset() {
	*x = FocalTaskFinder_End{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FocalTaskFinder_End) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FocalTaskFinder_End) ProtoMessage() {}

func (x *FocalTaskFinder_End) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FocalTaskFinder_End.ProtoReflect.Descriptor instead.
func (*FocalTaskFinder_End) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_trv2_dynamic_updates_proto_rawDescGZIP(), []int{1, 3}
}

// ByDynamicIdentifier is a lookup finder that finds the task
// with the given dynamic identifier set.
type FocalTaskFinder_ByDynamicIdentifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DynamicIdentifier string `protobuf:"bytes,1,opt,name=dynamic_identifier,json=dynamicIdentifier,proto3" json:"dynamic_identifier,omitempty"`
}

func (x *FocalTaskFinder_ByDynamicIdentifier) Reset() {
	*x = FocalTaskFinder_ByDynamicIdentifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FocalTaskFinder_ByDynamicIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FocalTaskFinder_ByDynamicIdentifier) ProtoMessage() {}

func (x *FocalTaskFinder_ByDynamicIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FocalTaskFinder_ByDynamicIdentifier.ProtoReflect.Descriptor instead.
func (*FocalTaskFinder_ByDynamicIdentifier) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_trv2_dynamic_updates_proto_rawDescGZIP(), []int{1, 4}
}

func (x *FocalTaskFinder_ByDynamicIdentifier) GetDynamicIdentifier() string {
	if x != nil {
		return x.DynamicIdentifier
	}
	return ""
}

// Insert places the entire task provided within the ordered
// task list based on the insert type.
type UpdateAction_Insert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InsertType UpdateAction_Insert_InsertType `protobuf:"varint,1,opt,name=insert_type,json=insertType,proto3,enum=chromiumos.test.api.UpdateAction_Insert_InsertType" json:"insert_type,omitempty"`
	// Task payload that will be inserted into the task list.
	Task *CrosTestRunnerDynamicRequest_Task `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
}

func (x *UpdateAction_Insert) Reset() {
	*x = UpdateAction_Insert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAction_Insert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAction_Insert) ProtoMessage() {}

func (x *UpdateAction_Insert) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAction_Insert.ProtoReflect.Descriptor instead.
func (*UpdateAction_Insert) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_trv2_dynamic_updates_proto_rawDescGZIP(), []int{2, 0}
}

func (x *UpdateAction_Insert) GetInsertType() UpdateAction_Insert_InsertType {
	if x != nil {
		return x.InsertType
	}
	return UpdateAction_Insert_APPEND
}

func (x *UpdateAction_Insert) GetTask() *CrosTestRunnerDynamicRequest_Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// Remove will fully remove the focal task, shrinking
// the ordered task list by one.
type UpdateAction_Remove struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateAction_Remove) Reset() {
	*x = UpdateAction_Remove{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAction_Remove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAction_Remove) ProtoMessage() {}

func (x *UpdateAction_Remove) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAction_Remove.ProtoReflect.Descriptor instead.
func (*UpdateAction_Remove) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_trv2_dynamic_updates_proto_rawDescGZIP(), []int{2, 1}
}

// Modify deploys in-place modifications to the focal task
// based on the given payloads and their corresponding instructions.
type UpdateAction_Modify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// May bundle modifications within a single action.
	Modifications []*UpdateAction_Modify_Modification `protobuf:"bytes,1,rep,name=modifications,proto3" json:"modifications,omitempty"`
}

func (x *UpdateAction_Modify) Reset() {
	*x = UpdateAction_Modify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAction_Modify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAction_Modify) ProtoMessage() {}

func (x *UpdateAction_Modify) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAction_Modify.ProtoReflect.Descriptor instead.
func (*UpdateAction_Modify) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_trv2_dynamic_updates_proto_rawDescGZIP(), []int{2, 2}
}

func (x *UpdateAction_Modify) GetModifications() []*UpdateAction_Modify_Modification {
	if x != nil {
		return x.Modifications
	}
	return nil
}

type UpdateAction_Modify_Modification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Payload is the reference object for modifying the task in-place.
	Payload *anypb.Any `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// Instructions follow the DynamicDeps formatting rules in which the
	// key represents where in the task the modification is occurring, and
	// the value represents which part of the payload is being deployed to
	// that portion of the task.
	// Note: An empty value within an instruction represents a one-to-one
	//  mapping between the type of the modified task portion and the payload.
	//
	// Example:
	//  Payload = {
	//      Value = "example string"
	//  }
	//  Instructions = {
	//      "provision.provisionRequest.target": "value"
	//  }
	Instructions map[string]string `protobuf:"bytes,2,rep,name=instructions,proto3" json:"instructions,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *UpdateAction_Modify_Modification) Reset() {
	*x = UpdateAction_Modify_Modification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAction_Modify_Modification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAction_Modify_Modification) ProtoMessage() {}

func (x *UpdateAction_Modify_Modification) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAction_Modify_Modification.ProtoReflect.Descriptor instead.
func (*UpdateAction_Modify_Modification) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_trv2_dynamic_updates_proto_rawDescGZIP(), []int{2, 2, 0}
}

func (x *UpdateAction_Modify_Modification) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UpdateAction_Modify_Modification) GetInstructions() map[string]string {
	if x != nil {
		return x.Instructions
	}
	return nil
}

var File_chromiumos_test_api_trv2_dynamic_updates_proto protoreflect.FileDescriptor

var file_chromiumos_test_api_trv2_dynamic_updates_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2f, 0x74, 0x65, 0x73,
	0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x72, 0x76, 0x32, 0x5f, 0x64, 0x79, 0x6e, 0x61, 0x6d,
	0x69, 0x63, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x13, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73,
	0x74, 0x2e, 0x61, 0x70, 0x69, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x26, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2f, 0x74, 0x65, 0x73,
	0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x72, 0x76, 0x32, 0x5f, 0x64, 0x79, 0x6e, 0x61, 0x6d,
	0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb4, 0x01, 0x0a, 0x18, 0x55, 0x73, 0x65,
	0x72, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x64, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x50, 0x0a, 0x11, 0x66, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x74,
	0x61, 0x73, 0x6b, 0x5f, 0x66, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x24, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65,
	0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x6f, 0x63, 0x61, 0x6c, 0x54, 0x61, 0x73, 0x6b,
	0x46, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x0f, 0x66, 0x6f, 0x63, 0x61, 0x6c, 0x54, 0x61, 0x73,
	0x6b, 0x46, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x46, 0x0a, 0x0d, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21,
	0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x0c, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0xfb, 0x05, 0x0a, 0x0f, 0x46, 0x6f, 0x63, 0x61, 0x6c, 0x54, 0x61, 0x73, 0x6b, 0x46, 0x69, 0x6e,
	0x64, 0x65, 0x72, 0x12, 0x42, 0x0a, 0x05, 0x66, 0x69, 0x72, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e,
	0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x6f, 0x63, 0x61, 0x6c, 0x54, 0x61,
	0x73, 0x6b, 0x46, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x46, 0x69, 0x72, 0x73, 0x74, 0x48, 0x00,
	0x52, 0x05, 0x66, 0x69, 0x72, 0x73, 0x74, 0x12, 0x3f, 0x0a, 0x04, 0x6c, 0x61, 0x73, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d,
	0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x6f, 0x63, 0x61,
	0x6c, 0x54, 0x61, 0x73, 0x6b, 0x46, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x4c, 0x61, 0x73, 0x74,
	0x48, 0x00, 0x52, 0x04, 0x6c, 0x61, 0x73, 0x74, 0x12, 0x4e, 0x0a, 0x09, 0x62, 0x65, 0x67, 0x69,
	0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x63, 0x68,
	0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x46, 0x6f, 0x63, 0x61, 0x6c, 0x54, 0x61, 0x73, 0x6b, 0x46, 0x69, 0x6e, 0x64, 0x65,
	0x72, 0x2e, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x09, 0x62,
	0x65, 0x67, 0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x3c, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d,
	0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x6f, 0x63, 0x61,
	0x6c, 0x54, 0x61, 0x73, 0x6b, 0x46, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x45, 0x6e, 0x64, 0x48,
	0x00, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x12, 0x6e, 0x0a, 0x15, 0x62, 0x79, 0x5f, 0x64, 0x79, 0x6e,
	0x61, 0x6d, 0x69, 0x63, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x38, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d,
	0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x6f, 0x63, 0x61,
	0x6c, 0x54, 0x61, 0x73, 0x6b, 0x46, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x42, 0x79, 0x44, 0x79,
	0x6e, 0x61, 0x6d, 0x69, 0x63, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x48,
	0x00, 0x52, 0x13, 0x62, 0x79, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x1a, 0x53, 0x0a, 0x05, 0x46, 0x69, 0x72, 0x73, 0x74, 0x12,
	0x4a, 0x0a, 0x09, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x2d, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e,
	0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x6f, 0x63, 0x61, 0x6c, 0x54, 0x61,
	0x73, 0x6b, 0x46, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x1a, 0x52, 0x0a, 0x04, 0x4c,
	0x61, 0x73, 0x74, 0x12, 0x4a, 0x0a, 0x09, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2d, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75,
	0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x6f, 0x63,
	0x61, 0x6c, 0x54, 0x61, 0x73, 0x6b, 0x46, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x54, 0x61, 0x73,
	0x6b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x1a,
	0x0b, 0x0a, 0x09, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x1a, 0x05, 0x0a, 0x03,
	0x45, 0x6e, 0x64, 0x1a, 0x44, 0x0a, 0x13, 0x42, 0x79, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x2d, 0x0a, 0x12, 0x64, 0x79,
	0x6e, 0x61, 0x6d, 0x69, 0x63, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x22, 0x58, 0x0a, 0x08, 0x54, 0x61, 0x73,
	0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x52, 0x4f, 0x56, 0x49, 0x53, 0x49,
	0x4f, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x52, 0x45, 0x54, 0x45, 0x53, 0x54, 0x10,
	0x01, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x45, 0x53, 0x54, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x50,
	0x4f, 0x53, 0x54, 0x54, 0x45, 0x53, 0x54, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x55, 0x42,
	0x4c, 0x49, 0x53, 0x48, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x47, 0x45, 0x4e, 0x45, 0x52, 0x49,
	0x43, 0x10, 0x05, 0x42, 0x08, 0x0a, 0x06, 0x66, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x22, 0xa6, 0x06,
	0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x42,
	0x0a, 0x06, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28,
	0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x48, 0x00, 0x52, 0x06, 0x69, 0x6e, 0x73, 0x65,
	0x72, 0x74, 0x12, 0x42, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x28, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e,
	0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x48, 0x00, 0x52, 0x06,
	0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x42, 0x0a, 0x06, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75,
	0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79,
	0x48, 0x00, 0x52, 0x06, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x1a, 0xde, 0x01, 0x0a, 0x06, 0x49,
	0x6e, 0x73, 0x65, 0x72, 0x74, 0x12, 0x54, 0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x33, 0x2e, 0x63, 0x68, 0x72,
	0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x49, 0x6e,
	0x73, 0x65, 0x72, 0x74, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x0a, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x4a, 0x0a, 0x04, 0x74,
	0x61, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x63, 0x68, 0x72, 0x6f,
	0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x43, 0x72, 0x6f, 0x73, 0x54, 0x65, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x44, 0x79,
	0x6e, 0x61, 0x6d, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x54, 0x61, 0x73,
	0x6b, 0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x22, 0x32, 0x0a, 0x0a, 0x49, 0x6e, 0x73, 0x65, 0x72,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x50, 0x50, 0x45, 0x4e, 0x44, 0x10,
	0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x52, 0x45, 0x50, 0x45, 0x4e, 0x44, 0x10, 0x01, 0x12, 0x0b,
	0x0a, 0x07, 0x52, 0x45, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x10, 0x02, 0x1a, 0x08, 0x0a, 0x06, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x1a, 0xd4, 0x02, 0x0a, 0x06, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79,
	0x12, 0x5b, 0x0a, 0x0d, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69,
	0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66,
	0x79, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d,
	0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0xec, 0x01,
	0x0a, 0x0c, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x6b,
	0x0a, 0x0c, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x47, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f,
	0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x2e, 0x4d,
	0x6f, 0x64, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x49, 0x6e, 0x73, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0c, 0x69,
	0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x3f, 0x0a, 0x11, 0x49,
	0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x08, 0x0a, 0x06,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x6f, 0x2e, 0x63, 0x68, 0x72,
	0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69,
	0x75, 0x6d, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x67, 0x6f, 0x2f, 0x74,
	0x65, 0x73, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chromiumos_test_api_trv2_dynamic_updates_proto_rawDescOnce sync.Once
	file_chromiumos_test_api_trv2_dynamic_updates_proto_rawDescData = file_chromiumos_test_api_trv2_dynamic_updates_proto_rawDesc
)

func file_chromiumos_test_api_trv2_dynamic_updates_proto_rawDescGZIP() []byte {
	file_chromiumos_test_api_trv2_dynamic_updates_proto_rawDescOnce.Do(func() {
		file_chromiumos_test_api_trv2_dynamic_updates_proto_rawDescData = protoimpl.X.CompressGZIP(file_chromiumos_test_api_trv2_dynamic_updates_proto_rawDescData)
	})
	return file_chromiumos_test_api_trv2_dynamic_updates_proto_rawDescData
}

var file_chromiumos_test_api_trv2_dynamic_updates_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_chromiumos_test_api_trv2_dynamic_updates_proto_goTypes = []interface{}{
	(FocalTaskFinder_TaskType)(0),               // 0: chromiumos.test.api.FocalTaskFinder.TaskType
	(UpdateAction_Insert_InsertType)(0),         // 1: chromiumos.test.api.UpdateAction.Insert.InsertType
	(*UserDefinedDynamicUpdate)(nil),            // 2: chromiumos.test.api.UserDefinedDynamicUpdate
	(*FocalTaskFinder)(nil),                     // 3: chromiumos.test.api.FocalTaskFinder
	(*UpdateAction)(nil),                        // 4: chromiumos.test.api.UpdateAction
	(*FocalTaskFinder_First)(nil),               // 5: chromiumos.test.api.FocalTaskFinder.First
	(*FocalTaskFinder_Last)(nil),                // 6: chromiumos.test.api.FocalTaskFinder.Last
	(*FocalTaskFinder_Beginning)(nil),           // 7: chromiumos.test.api.FocalTaskFinder.Beginning
	(*FocalTaskFinder_End)(nil),                 // 8: chromiumos.test.api.FocalTaskFinder.End
	(*FocalTaskFinder_ByDynamicIdentifier)(nil), // 9: chromiumos.test.api.FocalTaskFinder.ByDynamicIdentifier
	(*UpdateAction_Insert)(nil),                 // 10: chromiumos.test.api.UpdateAction.Insert
	(*UpdateAction_Remove)(nil),                 // 11: chromiumos.test.api.UpdateAction.Remove
	(*UpdateAction_Modify)(nil),                 // 12: chromiumos.test.api.UpdateAction.Modify
	(*UpdateAction_Modify_Modification)(nil),    // 13: chromiumos.test.api.UpdateAction.Modify.Modification
	nil,                                         // 14: chromiumos.test.api.UpdateAction.Modify.Modification.InstructionsEntry
	(*CrosTestRunnerDynamicRequest_Task)(nil),   // 15: chromiumos.test.api.CrosTestRunnerDynamicRequest.Task
	(*anypb.Any)(nil),                           // 16: google.protobuf.Any
}
var file_chromiumos_test_api_trv2_dynamic_updates_proto_depIdxs = []int32{
	3,  // 0: chromiumos.test.api.UserDefinedDynamicUpdate.focal_task_finder:type_name -> chromiumos.test.api.FocalTaskFinder
	4,  // 1: chromiumos.test.api.UserDefinedDynamicUpdate.update_action:type_name -> chromiumos.test.api.UpdateAction
	5,  // 2: chromiumos.test.api.FocalTaskFinder.first:type_name -> chromiumos.test.api.FocalTaskFinder.First
	6,  // 3: chromiumos.test.api.FocalTaskFinder.last:type_name -> chromiumos.test.api.FocalTaskFinder.Last
	7,  // 4: chromiumos.test.api.FocalTaskFinder.beginning:type_name -> chromiumos.test.api.FocalTaskFinder.Beginning
	8,  // 5: chromiumos.test.api.FocalTaskFinder.end:type_name -> chromiumos.test.api.FocalTaskFinder.End
	9,  // 6: chromiumos.test.api.FocalTaskFinder.by_dynamic_identifier:type_name -> chromiumos.test.api.FocalTaskFinder.ByDynamicIdentifier
	10, // 7: chromiumos.test.api.UpdateAction.insert:type_name -> chromiumos.test.api.UpdateAction.Insert
	11, // 8: chromiumos.test.api.UpdateAction.remove:type_name -> chromiumos.test.api.UpdateAction.Remove
	12, // 9: chromiumos.test.api.UpdateAction.modify:type_name -> chromiumos.test.api.UpdateAction.Modify
	0,  // 10: chromiumos.test.api.FocalTaskFinder.First.task_type:type_name -> chromiumos.test.api.FocalTaskFinder.TaskType
	0,  // 11: chromiumos.test.api.FocalTaskFinder.Last.task_type:type_name -> chromiumos.test.api.FocalTaskFinder.TaskType
	1,  // 12: chromiumos.test.api.UpdateAction.Insert.insert_type:type_name -> chromiumos.test.api.UpdateAction.Insert.InsertType
	15, // 13: chromiumos.test.api.UpdateAction.Insert.task:type_name -> chromiumos.test.api.CrosTestRunnerDynamicRequest.Task
	13, // 14: chromiumos.test.api.UpdateAction.Modify.modifications:type_name -> chromiumos.test.api.UpdateAction.Modify.Modification
	16, // 15: chromiumos.test.api.UpdateAction.Modify.Modification.payload:type_name -> google.protobuf.Any
	14, // 16: chromiumos.test.api.UpdateAction.Modify.Modification.instructions:type_name -> chromiumos.test.api.UpdateAction.Modify.Modification.InstructionsEntry
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_chromiumos_test_api_trv2_dynamic_updates_proto_init() }
func file_chromiumos_test_api_trv2_dynamic_updates_proto_init() {
	if File_chromiumos_test_api_trv2_dynamic_updates_proto != nil {
		return
	}
	file_chromiumos_test_api_trv2_dynamic_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDefinedDynamicUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FocalTaskFinder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FocalTaskFinder_First); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FocalTaskFinder_Last); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FocalTaskFinder_Beginning); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FocalTaskFinder_End); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FocalTaskFinder_ByDynamicIdentifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAction_Insert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAction_Remove); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAction_Modify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAction_Modify_Modification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*FocalTaskFinder_First_)(nil),
		(*FocalTaskFinder_Last_)(nil),
		(*FocalTaskFinder_Beginning_)(nil),
		(*FocalTaskFinder_End_)(nil),
		(*FocalTaskFinder_ByDynamicIdentifier_)(nil),
	}
	file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*UpdateAction_Insert_)(nil),
		(*UpdateAction_Remove_)(nil),
		(*UpdateAction_Modify_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chromiumos_test_api_trv2_dynamic_updates_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chromiumos_test_api_trv2_dynamic_updates_proto_goTypes,
		DependencyIndexes: file_chromiumos_test_api_trv2_dynamic_updates_proto_depIdxs,
		EnumInfos:         file_chromiumos_test_api_trv2_dynamic_updates_proto_enumTypes,
		MessageInfos:      file_chromiumos_test_api_trv2_dynamic_updates_proto_msgTypes,
	}.Build()
	File_chromiumos_test_api_trv2_dynamic_updates_proto = out.File
	file_chromiumos_test_api_trv2_dynamic_updates_proto_rawDesc = nil
	file_chromiumos_test_api_trv2_dynamic_updates_proto_goTypes = nil
	file_chromiumos_test_api_trv2_dynamic_updates_proto_depIdxs = nil
}
