// Copyright 2021 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package chromiumos.test.api;

option go_package = "go.chromium.org/chromiumos/config/go/test/api";

// CrosPublishRequest specifies a local directory that will be uploaded to a GS
// path.
// NEXT TAG: 3
message CrosPublishRequest {
  // GS path to upload to, e.g. gs://foo/bar/baz/
  string gs_directory = 1;

  // Absolute path to local directory to upload to GS, e.g. /usr/local/foo/bar
  string local_directory = 2;
}

// CrosPublishResponse includes the GS url for the uploaded data. If failed,
// populates the error message.
// NEXT TAG: 4
message CrosPublishResponse {
  // URL of Google Storage location containing offloaded files
  string gs_url = 1;

  // If the publish process finished successfully or not.
  bool error = 2;

  // Error message when the publish process failed.
  string error_message = 3;
}
