// Copyright 2024 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package chromiumos.test.api;

import "google/protobuf/any.proto";

option go_package = "go.chromium.org/chromiumos/config/go/test/api";

service GenericService {
  rpc Start(GenericStartRequest) returns (GenericStartResponse) {}
  rpc Run(GenericRunRequest) returns (GenericRunResponse) {}
  rpc Stop(GenericStopRequest) returns (GenericStopResponse) {}
}

message GenericStartRequest {
  GenericMessage message = 1;
}

message GenericStartResponse {
  GenericMessage message = 1;
}

message GenericRunRequest {
  GenericMessage message = 1;
}

message GenericRunResponse {
  GenericMessage message = 1;
}

message GenericStopRequest {
  GenericMessage message = 1;
}

message GenericStopResponse {
  GenericMessage message = 1;
}

message GenericMessage {
  map<string, google.protobuf.Any> values = 1;
}
