# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

worker_processes  5;
error_log  /var/log/nginx/nginx_error.log debug;
pid        /var/run/nginx.pid;
worker_rlimit_nofile 8192;

events {
  worker_connections  4096;  ## Default: 1024
}

http {
    # include the default mime.types to map file extensions to MIME types
    include /etc/nginx/mime.types;
    default_type  application/octet-stream;
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';
    access_log  /var/log/nginx/nginx_access.log  main;
    sendfile     on;
    tcp_nopush   on;

    server {
        listen 6010;
        listen [::]:6010;
        # set the root directory for the server (we need to copy our
        # application files here)
        root /etc/nginx/html;

        # set the default index file for the server (Angular generates the
        # index.html file for us and it will be in the above directory)
        index index.html;

        # specify the configuration for the '/' location
        location / {
            # try to serve the requested URI. if that fails then try to
            # serve the URI with a trailing slash. if that fails, then
            # serve the index.html file; this is needed in order to serve
            # Angular routes--e.g.,'localhost:8080/customer' will serve
            # the index.html file
            try_files $uri $uri/ /index.html;
            add_header Cache-Control 'no-store, no-cache, must-revalidate,
                proxy-revalidate, max-age=0';
        }
    }
}
