# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

---
- hosts: all
  become: true
  pre_tasks:
  - name: Include update packages tasks
    include_tasks: tasks/update-packages.yml

- hosts: HMR_Touch_Hosts
  become: true
  roles:
    - touchhostd
